-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 1 OF 23: Categories
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Categories
-- ---------------------------------------------------------------------------

insert into public.categories (id, slug, name, description, accent, icon, sort_order) values
  ('5364da32-b801-5422-903e-295b008b9416', 'phone-skills', 'Phone Skills', 'Etiquette, tone, and call handling for outbound and inbound calls.', 'green', 'speaking', 0),
  ('1e1fb7c1-f3f4-583c-9a84-0efc7eb68854', 'chat-support', 'Chat Support', 'Written support standards for Messenger and page inquiries.', 'blue', 'chat', 1),
  ('d034002e-71d8-5eeb-9c9e-de578918d2cc', 'sales-process', 'Sales Process', 'The structures that carry a conversation from greeting to order.', 'violet', 'finish', 2),
  ('8975413e-341a-5238-9895-0845fb7a889d', 'objection-handling', 'Objection Handling', 'The twelve objections KCO agents hear, and how to answer them.', 'amber', 'muscle', 3),
  ('e0f82390-0ad6-519b-9e95-a7c35d3ab972', 'training-activities', 'Training Activities', 'Facilitator-led exercises for huddles and training days.', 'rose', 'grad', 4),
  ('368390d7-eb90-5113-b515-2b75504c63e6', 'quick-reference', 'Quick Reference', 'Scripts, formulas, and wording you need mid-conversation.', 'slate', 'bolt', 5)
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  description = excluded.description,
  accent = excluded.accent,
  icon = excluded.icon,
  sort_order = excluded.sort_order
;

commit;
