-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 3 OF 23: Module 2: Sales Call Structure
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 2: Sales Call Structure
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'sales-call-structure', 'Sales Call Structure', 'The eight-step KCO call. Memorise the order, improvise the words, and never present before you discover.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 2, 'published', 'foundation', 30, array['sales', 'admin']::public.user_role[], array['Phone Sales', 'Field Sales']::text[], array['phone', 'structure', 'closing', 'discovery']::text[], true, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('3b939bd8-1328-58a9-981b-626e5846e524', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'The Eight Steps at a Glance', 'Memorise the order. Improvise the words.', 0, 'published'),
  ('52f8509a-2290-58ce-acf0-18717d1196ae', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 1 - Greet', 'Warm, clear, and identical every time.', 1, 'published'),
  ('acb4d277-b71e-5bbd-aae5-8a59a10567b9', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 2 - Introduce', 'Confirm the person, then place yourself.', 2, 'published'),
  ('1f9daf84-a6e6-55e8-b6ec-d99f7d0ec41f', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 3 - Purpose', 'Say why you called, then ask permission for the time.', 3, 'published'),
  ('9dccfe1c-41d1-5f07-b303-4127234a3f8d', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 4 - Discover', 'The step that makes every later step easier.', 4, 'published'),
  ('e84d866e-0ce0-5159-8563-a83e1f0a1be3', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 5 - Present', 'One recommendation, connected to what they told you.', 5, 'published'),
  ('6e2efdd8-4918-5de3-bc6e-7f8379f8bb5c', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 6 - Handle Objection', 'A.C.A.C. - the same four moves for every objection.', 6, 'published'),
  ('571b4028-108a-5f04-9cc9-3d54d27c6423', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 7 - Close', 'Ask for something small, specific, and dated.', 7, 'published'),
  ('76b3d2ae-baa6-5b6c-bf61-59f943908c48', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 'Step 8 - Confirm + End', 'Recap, state next steps, thank them by name.', 8, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('b130880c-048b-5073-8c9e-b9b0b7006801', '3b939bd8-1328-58a9-981b-626e5846e524', 'text', '{"text":"Every KCO sales call runs the same eight steps in the same order. The order matters more than the wording: presenting before discovering is the single most common reason a call ends in \"pag-iisipan ko pa\"."}'::jsonb, 0),
  ('f0f6f82e-ede9-59bb-bea6-d53aa9de9157', '3b939bd8-1328-58a9-981b-626e5846e524', 'formula', '{"name":"The 8-Step Sales Call","steps":[{"key":"1","label":"Greet","detail":"Time of day, your name, KCO Kangkong Chips."},{"key":"2","label":"Introduce","detail":"Confirm who you are speaking with and your role."},{"key":"3","label":"Purpose","detail":"One sentence on why you are calling, then ask for their time."},{"key":"4","label":"Discover","detail":"Three to four questions about their selling situation."},{"key":"5","label":"Present","detail":"Recommend one package, tied to what they just told you."},{"key":"6","label":"Handle Objection","detail":"Run A.C.A.C. - Acknowledge, Clarify, Address, Close."},{"key":"7","label":"Close","detail":"Ask for a specific, small, dated commitment."},{"key":"8","label":"Confirm + End","detail":"Recap the agreement, state next steps, thank them."}]}'::jsonb, 1),
  ('406e5dcb-3af8-5b4e-9d55-f917ace6d9e6', '3b939bd8-1328-58a9-981b-626e5846e524', 'quote', '{"text":"Don''t just sound like a salesperson. Sound like a professional who genuinely wants to help.","attribution":"KCO Golden Rule - Sales Calls"}'::jsonb, 2),
  ('88a2fc09-dab7-5ec2-9a5f-074fa26ee58c', '52f8509a-2290-58ce-acf0-18717d1196ae', 'script', '{"label":"Greet","language":"mixed","lines":["Good morning po!","This is Jason from KCO Kangkong Chips."]}'::jsonb, 0),
  ('7769b408-162a-5262-b598-570efdc7b190', '52f8509a-2290-58ce-acf0-18717d1196ae', 'bullets', '{"items":["Match the time of day - getting this wrong signals you are on autopilot.","Smile before the first word (Module 1, Section 02).","Say the company name fully; \"KCO\" alone means nothing to a new lead."]}'::jsonb, 1),
  ('e6a6f99d-9da5-57cf-bb5f-6deb74533b26', 'acb4d277-b71e-5bbd-aae5-8a59a10567b9', 'script', '{"label":"Introduce","language":"mixed","lines":["Am I speaking with Ms. Rivera?","I am part of the KCO reseller support team."]}'::jsonb, 0),
  ('368bbd41-cf51-5ddd-ac58-bbf1a97fa0bc', 'acb4d277-b71e-5bbd-aae5-8a59a10567b9', 'callout', '{"variant":"warning","title":"Wrong person?","text":"If it is not them, do not pitch. Ask when the right person is available, thank whoever answered, and log the callback. Pitching to the wrong person wastes the lead."}'::jsonb, 1),
  ('7e5b6047-9c3c-5b08-b6f4-8fb7f6723725', '1f9daf84-a6e6-55e8-b6ec-d99f7d0ec41f', 'script', '{"label":"Purpose","language":"mixed","lines":["I am following up on your inquiry about becoming a KCO reseller.","Do you have about two minutes so I can walk you through it?"]}'::jsonb, 0),
  ('bca268e5-95a2-5f07-8561-193d32d7faeb', '1f9daf84-a6e6-55e8-b6ec-d99f7d0ec41f', 'dosdonts', '{"dos":["Reference their own inquiry","Give a real time estimate","Accept a \"not now\" gracefully"],"donts":["Open with a price","Say \"quick question\" and then pitch for ten minutes","Skip permission and keep talking"]}'::jsonb, 1),
  ('0a0e2c4b-7445-54a9-92e3-201f260d10ee', '9dccfe1c-41d1-5f07-b303-4127234a3f8d', 'text', '{"text":"Discovery is where you earn the right to recommend. Four questions give you the package, the pitch angle, and an early read on which objection is coming."}'::jsonb, 0),
  ('3f917821-29c0-5b0d-a9e0-5e7b0246d9b1', '9dccfe1c-41d1-5f07-b303-4127234a3f8d', 'numbered', '{"items":["Are you planning to sell online, in a store, or both?","Have you resold food products before?","How many customers do you usually reach in a week?","What interested you in Kangkong Chips?"]}'::jsonb, 1),
  ('84de370a-0c98-5790-bc50-cccb97987626', '9dccfe1c-41d1-5f07-b303-4127234a3f8d', 'comparison', '{"caption":"Listen for the signal, pick the angle","columns":["What they say","What you lead with"],"rows":[["\"Online lang, sa Facebook.\"","Shareable content, no store rent, small starting pack."],["\"May sari-sari store kami.\"","Shelf visibility, repeat walk-in buyers, display support."],["\"First time ko magtinda.\"","Starter pack, step-by-step onboarding, low first commitment."],["\"Nagtinda na ako ng chips before.\"","Margins, resupply speed, product differentiation."]]}'::jsonb, 2),
  ('b62ce8cc-66ae-5bd4-b480-70b21e1637c4', '9dccfe1c-41d1-5f07-b303-4127234a3f8d', 'callout', '{"variant":"info","title":"Write it down","text":"Note their answers in the lead record while they talk. You will reuse their exact words in Step 5, and quoting a customer back to themselves is the most persuasive thing you can do."}'::jsonb, 3),
  ('2c521e81-a0db-5f66-841f-cfb0a3d4b82e', 'e84d866e-0ce0-5159-8563-a83e1f0a1be3', 'text', '{"text":"Do not read the catalogue. Recommend a single package and justify it with their own situation. Three options create hesitation; one clear recommendation creates a decision."}'::jsonb, 0),
  ('78484cd0-e35d-5f65-ac4c-b65dbb6935f1', 'e84d866e-0ce0-5159-8563-a83e1f0a1be3', 'script', '{"label":"Present - tied to discovery","language":"mixed","lines":["Based on what you said - online selling and first time as a reseller - ","the starter pack fits you best.","It is the smallest order we do, so your first commitment stays low,","and it gives you enough stock to test which flavour moves fastest.","We also send you the product photos and captions you can post right away."]}'::jsonb, 1),
  ('cc67b002-b456-5a2f-8a42-37b925186140', 'e84d866e-0ce0-5159-8563-a83e1f0a1be3', 'callout', '{"variant":"warning","title":"Illustrative only - pending Admin review","text":"Any income, ROI, or \"kita\" figure you mention must be presented as a training example, never as a guaranteed outcome. Use \"some resellers report\" framing, and never invent a number."}'::jsonb, 2),
  ('d088a4e6-cf19-5d13-b5a2-82bf1a945df1', '6e2efdd8-4918-5de3-bc6e-7f8379f8bb5c', 'formula', '{"name":"A.C.A.C.","steps":[{"key":"A","label":"Acknowledge","detail":"Validate the concern without agreeing that it kills the deal."},{"key":"C","label":"Clarify","detail":"Ask one question to find what is actually behind it."},{"key":"A","label":"Address","detail":"Answer that specific concern - not the generic version."},{"key":"C","label":"Close","detail":"Return to a small, dated next step."}]}'::jsonb, 0),
  ('4cd06880-650c-57f3-a9ef-7b71d683a16f', '6e2efdd8-4918-5de3-bc6e-7f8379f8bb5c', 'text', '{"text":"Objections are not rejections. An objection means the customer is still thinking about it. The full library of twelve KCO objections, each mapped to A.C.A.C., lives in Sales Resources → Objection Handling."}'::jsonb, 1),
  ('ea1e6a56-2a58-59ae-9ca4-70ba904bae8b', '571b4028-108a-5f04-9cc9-3d54d27c6423', 'text', '{"text":"A close is not pressure - it is a clear next action. \"I will send the details\" is not a close. \"Shall I reserve one starter pack for Friday delivery?\" is."}'::jsonb, 0),
  ('669b80ea-122d-5187-a672-7543c807254c', '571b4028-108a-5f04-9cc9-3d54d27c6423', 'comparison', '{"caption":"Weak vs. clear closes","columns":["Weak","Clear"],"rows":[["Let me know po if interested.","Shall I reserve a starter pack for Friday delivery?"],["I will send details.","I will send the details now - can I call you at 4 PM to confirm?"],["Sige, think about it.","Which works better for you, Friday or Monday delivery?"]]}'::jsonb, 1),
  ('3fd5c061-7362-52d0-91fe-8c188109afd3', '571b4028-108a-5f04-9cc9-3d54d27c6423', 'dosdonts', '{"dos":["Offer two dates instead of asking yes/no","Stay quiet after asking","Accept a smaller commitment"],"donts":["Ask three times in a row","Add a discount you cannot authorise","Fill the silence yourself"]}'::jsonb, 2),
  ('30610457-e770-5423-8efa-68ea6740ddbc', '76b3d2ae-baa6-5b6c-bf61-59f943908c48', 'script', '{"label":"Confirm and end","language":"mixed","lines":["To confirm po - one starter pack, delivery Friday, cash on delivery.","I will message you the order summary right after this call.","If anything changes, you can reply to that same thread.","Thank you for your time, Ms. Rivera. Enjoy your day!"]}'::jsonb, 0),
  ('a12a4bfc-4f6c-5a45-9329-3a2d08fb7947', '76b3d2ae-baa6-5b6c-bf61-59f943908c48', 'checklist', '{"items":[{"text":"Order details repeated back"},{"text":"Payment method confirmed"},{"text":"Delivery date confirmed"},{"text":"Written summary promised and sent"},{"text":"Lead record updated before the next call"}]}'::jsonb, 1),
  ('b9a26293-225e-5613-862f-8ed98b1a7a01', '76b3d2ae-baa6-5b6c-bf61-59f943908c48', 'quiz', '{"question":"A customer gives a clear buying signal during Step 4 (Discover). What should you do?","options":["Skip to Step 7 and close immediately.","Finish your remaining discovery questions exactly as written.","Acknowledge the signal, ask one confirming question, then present and close.","Ignore it - the steps must run in order."],"answerIndex":2,"explanation":"The order is a guide, not a cage. When a buying signal appears early, confirm it briefly and move to Present and Close - but never close without having recommended a specific package first."}'::jsonb, 2)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
