-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 10 OF 23: Module 9: Delivery & Payment Policies
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 9: Delivery & Payment Policies
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('6c61a72d-2149-5ad1-9cfe-73c5acdf132a', 'delivery-and-payment', 'Delivery & Payment Policies', 'Coverage areas, cut-off times, payment methods, and what agents may confirm on their own authority.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 9, 'published', 'foundation', 12, array['sales', 'admin']::public.user_role[], array['Phone Sales', 'Chat Support', 'Operations']::text[], array['delivery', 'payment', 'policy']::text[], false, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('0daaa54d-2beb-5137-8597-d2f3954e6845', '6c61a72d-2149-5ad1-9cfe-73c5acdf132a', 'What You May Confirm Yourself', 'Everything else goes to a team lead.', 0, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('f07a6217-d749-5c42-9eb4-45da74e138e5', '0daaa54d-2beb-5137-8597-d2f3954e6845', 'dosdonts', '{"dos":["Standard delivery windows for covered areas","Cash on delivery availability","Published reseller pricing and minimum order quantity"],"donts":["Custom discounts of any size","Instalment or credit terms","Exclusive territory arrangements","Refunds or replacements before a logistics ticket exists"]}'::jsonb, 0),
  ('23b59c40-f5df-5dba-8df6-0e5ee8a4b470', '0daaa54d-2beb-5137-8597-d2f3954e6845', 'callout', '{"variant":"info","title":"When in doubt, escalate","text":"Say: \"That is outside what I can approve - let me check with my team lead and come back to you within the hour.\" Then actually come back within the hour."}'::jsonb, 1)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
