-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 8 OF 23: Module 7: Professional Wording
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 7: Professional Wording
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'professional-wording', 'Professional Wording', 'A searchable swap library - the casual phrase, the professional version, and when it matters.', '368390d7-eb90-5113-b515-2b75504c63e6', 7, 'published', 'foundation', 20, array['sales', 'admin']::public.user_role[], array['Phone Sales', 'Chat Support', 'Field Sales', 'Operations']::text[], array['wording', 'reference', 'tone', 'compliance']::text[], false, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('91932ba1-9756-5a56-ae1f-6f9187135ecf', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Why Wording Matters', 'The same message, received completely differently.', 0, 'published'),
  ('34224fa3-34ac-5bf6-9b51-9eb9d55ce94a', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Buying Time and Clarifying', 'Hold, repeat, clarify, verify.', 1, 'published'),
  ('8a503a5d-f90e-56c3-afde-a327455dd884', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Saying No Without Losing the Customer', 'Every no needs an alternative attached.', 2, 'published'),
  ('758058f0-fb44-58a0-840e-45d4b9716f10', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Conflict, Complaints, and Blame', 'Stay factual, never assign fault.', 3, 'published'),
  ('da82020d-fe15-5871-b069-2d37ba48b650', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Price, Closing, and Callbacks', 'Where imprecise words cost money.', 4, 'published'),
  ('0bfaffac-22c4-551c-8277-22e21847d1ab', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Claims You Must Never Make', 'Earnings, guarantees, and false urgency.', 5, 'published'),
  ('b04d64b8-0534-52a7-bf1e-355e48f88c9c', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 'Chat Tone and Handovers', 'Written words last longer than spoken ones.', 6, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('8a577d27-2ac1-515c-a4ef-6bee60626923', '91932ba1-9756-5a56-ae1f-6f9187135ecf', 'text', '{"text":"Casual phrasing is not rude between friends. On a sales call it makes the company sound improvised, and improvised companies do not get orders worth ten thousand pesos from strangers. Every swap below carries identical information - only the delivery changes."}'::jsonb, 0),
  ('48eac3bc-513c-5123-bb64-edf68b01bf28', '91932ba1-9756-5a56-ae1f-6f9187135ecf', 'callout', '{"variant":"info","title":"Searchable from anywhere","text":"This library is available in Quick Reference and from both the Phone and Chat script pages. Press ⌘K and type a phrase to find the professional version mid-call."}'::jsonb, 1),
  ('a96e749d-4544-56e2-ae5f-91e8160e73cd', '34224fa3-34ac-5bf6-9b51-9eb9d55ce94a', 'wording', '{"pairs":[{"avoid":"Wait lang.","use":"May I ask you to hold for a moment?","note":"Always ask, never instruct."},{"avoid":"Hindi ko alam.","use":"Let me verify that for you.","note":"Add a time commitment: \"…and I will come back to you within the hour.\""},{"avoid":"Di ko gets.","use":"May I clarify what you mean?"},{"avoid":"Ha? Ano po?","use":"I am sorry, could you repeat that please?"},{"avoid":"sry d ko alam","use":"Let me verify that for you po."}]}'::jsonb, 0),
  ('2660845c-13a4-58da-b362-1c2180bf9677', '8a503a5d-f90e-56c3-afde-a327455dd884', 'wording', '{"pairs":[{"avoid":"Wala kami niyan.","use":"That variant is not available right now - may I suggest an alternative?"},{"avoid":"Hindi pwede yan.","use":"What I can do for you instead is…","note":"Always follow a no with an alternative."},{"avoid":"wla po eh","use":"Wala pa po sa ngayon, but restock is next week."},{"avoid":"Hindi po namin yan ginagawa.","use":"That is outside what I can approve - let me check with my team lead and come back to you."}]}'::jsonb, 0),
  ('aa916875-5a97-5540-90bc-af4450653749', '8a503a5d-f90e-56c3-afde-a327455dd884', 'callout', '{"variant":"warning","title":"The pattern","text":"State what you cannot do in one short clause, then immediately say what you can do. A bare no invites the customer to argue; a no plus an alternative invites them to choose."}'::jsonb, 1),
  ('2f4d84ba-4075-5f35-9d67-97da6097dc0b', '758058f0-fb44-58a0-840e-45d4b9716f10', 'wording', '{"pairs":[{"avoid":"Mali kayo.","use":"Let me check the details so we are looking at the same information."},{"avoid":"Bakit hindi niyo binasa?","use":"Let me walk you through that part again."},{"avoid":"Sabi na sa post eh.","use":"Yes po, and to make it clearer - here are the details again."},{"avoid":"Ganun talaga.","use":"I understand that is frustrating. Here is what I can do."},{"avoid":"Fault yun ng courier.","use":"I am sorry this happened. I am filing it with our logistics team today.","note":"Never blame a third party by name."}]}'::jsonb, 0),
  ('b80c41aa-285b-547b-bbec-d70fe1204f18', 'da82020d-fe15-5871-b069-2d37ba48b650', 'wording', '{"pairs":[{"avoid":"Sige, bye.","use":"Thank you for your time, Ms. Rivera. Have a good day!"},{"avoid":"Kelangan niyo mag-decide na.","use":"Would you like me to reserve one while you decide?"},{"avoid":"Yan na po ang pinakamura.","use":"That is our reseller price, and it already includes delivery within Metro Manila."},{"avoid":"Bili na po kayo.","use":"Gusto niyo po bang i-reserve ko para sa Friday delivery?"},{"avoid":"Tawag na lang po kayo ulit.","use":"I will call you back at 4 PM today - is that convenient?","note":"The agent owns the callback, never the customer."},{"avoid":"Magkano budget mo?","use":"May I ask what budget range you are comfortable with?"}]}'::jsonb, 0),
  ('0679944f-dde2-5a97-a60f-d3eed14e23ad', '0bfaffac-22c4-551c-8277-22e21847d1ab', 'callout', '{"variant":"danger","title":"These are compliance rules, not style preferences","text":"Guaranteed earnings, guaranteed payback periods, and invented scarcity are prohibited on every channel. If you are unsure whether a claim is approved, do not make it - escalate to Admin."}'::jsonb, 0),
  ('5adee26c-4926-5485-807e-3eabdd3da6c2', '0bfaffac-22c4-551c-8277-22e21847d1ab', 'wording', '{"pairs":[{"avoid":"Sure na po yan kikita kayo.","use":"Ang kita po ay depende sa selling price at area niyo - pwede natin i-compute base sa numbers niyo.","note":"Never guarantee earnings. See the objection card \"Magkano ang kita ko?\"."},{"avoid":"Last stock na po!","use":"Limited po ang natitira sa batch na ito - gusto niyo po bang i-hold ko para sa inyo?","note":"Only if it is actually true. False urgency is prohibited."}]}'::jsonb, 1),
  ('ff76448b-a1d3-5cda-b6a4-d461896fd93a', 'b04d64b8-0534-52a7-bf1e-355e48f88c9c', 'wording', '{"pairs":[{"avoid":"ok po sure","use":"Sure po! 😊"},{"avoid":"thnx po","use":"Thank you po!"},{"avoid":"Sino ba kausap niyo dati?","use":"Let me read the conversation so you do not have to repeat yourself."},{"avoid":"Ay sorry, na-forget ko.","use":"Apologies for the delay - here is the update I promised."}]}'::jsonb, 0),
  ('64e01937-ff2e-541b-b50e-ecd32b162b59', 'b04d64b8-0534-52a7-bf1e-355e48f88c9c', 'quiz', '{"question":"A customer asks a question you cannot answer without checking. Which reply is correct?","options":["\"Hindi ko po alam eh.\"","\"Let me verify that for you po - I will come back to you within the hour.\"","\"Siguro po mga 6 months yung shelf life.\"","\"Sa post po nakalagay lahat.\""],"answerIndex":1,"explanation":"Verify, and attach a time commitment. Guessing creates a promise the company has to honour, and deflecting to a post reads as dismissive."}'::jsonb, 1)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
