-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 4 OF 23: Module 3: Chat Etiquette
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 3: Chat Etiquette
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'chat-etiquette', 'Chat Etiquette', 'The 22 chat rules: greeting, response time, tone, emoji discipline, confirmations, and complaint handling.', '1e1fb7c1-f3f4-583c-9a84-0efc7eb68854', 3, 'published', 'foundation', 40, array['sales', 'admin']::public.user_role[], array['Chat Support', 'Phone Sales']::text[], array['chat', 'etiquette', 'messenger', 'foundation']::text[], false, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('ad7345e6-2765-5004-b423-c3477cfb5f1e', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Always Greet, Always Respond Promptly', 'Speed and a greeting do most of the work in chat.', 0, 'published'),
  ('0d7e5b42-d50e-557e-9bf6-198ca791cee7', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Never Use One-Word Answers', 'Answer, then add value, then ask something.', 1, 'published'),
  ('7505fd4e-1536-5655-b8f4-cd66795657ee', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Professional Language, Capitalisation, and Emoji', 'Friendly, not sloppy.', 2, 'published'),
  ('516e43cb-a388-5bc5-bcfd-6018905686ae', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Personalise, but Do Not Overload', 'Use their name. Send one idea per message.', 3, 'published'),
  ('01241980-ff9b-56b6-95c7-cf354f3eb0ce', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Never Argue, Never Guess, Never Overshare', 'Three rules that protect you and the company.', 4, 'published'),
  ('834a7dbd-8895-5d1f-baa3-2c74f42646bf', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'The Four Openers You Will See Every Day', '"Send details", "How much?", pressure, and "I''ll think about it".', 5, 'published'),
  ('7d82e3b8-0305-54d9-8dd2-06295f4896e2', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Read the Entire Conversation Before Replying', 'Especially when you inherit a thread.', 6, 'published'),
  ('96247feb-4a2a-5fb0-97d8-feec500fbb41', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Order Confirmation', 'Repeat it back in writing. Every time, no exceptions.', 7, 'published'),
  ('dbcd3704-ffe8-5e87-965f-ecd3accf8458', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Complaint Handling in Chat', 'Acknowledge, apologise, act, follow up.', 8, 'published'),
  ('dae04d0c-4232-5d1a-be50-75e50184fb15', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 'Professional Closing and Chat Don’ts', 'End every chat on purpose, not by trailing off.', 9, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('72bc8e50-dbf9-595e-9311-ba5d8f42cde1', 'ad7345e6-2765-5004-b423-c3477cfb5f1e', 'text', '{"text":"In chat, the customer is comparing you to every other page they messaged. A greeting within the first reply and a response inside two minutes is the difference between a conversation and a \"seen\"."}'::jsonb, 0),
  ('d9006539-eae1-579a-ac19-58ebc4e08641', 'ad7345e6-2765-5004-b423-c3477cfb5f1e', 'script', '{"label":"Opening a new chat","language":"mixed","lines":["Hi po! Good afternoon 😊","Thank you for messaging KCO Kangkong Chips.","This is Jason - how may I help you today?"]}'::jsonb, 1),
  ('1c359445-476e-573d-a7c2-c5b9367c301a', 'ad7345e6-2765-5004-b423-c3477cfb5f1e', 'comparison', '{"caption":"Response time targets","columns":["Situation","Target"],"rows":[["First reply to a new chat","Within 2 minutes"],["Follow-up inside an active chat","Within 1 minute"],["Needs verification from a team lead","Acknowledge in 1 min, answer within 30 min"],["Received outside business hours","First reply at open, with an apology for the wait"]]}'::jsonb, 2),
  ('a74faef3-8ee2-5304-92fb-c2cc804f8366', 'ad7345e6-2765-5004-b423-c3477cfb5f1e', 'callout', '{"variant":"info","title":"If you need time","text":"Never go silent while you check something. Send \"Let me check that for you po, one moment 😊\" - an acknowledged wait is not a wait."}'::jsonb, 3),
  ('414bc8dc-fee1-5e26-b4d6-0542397c7f04', '0d7e5b42-d50e-557e-9bf6-198ca791cee7', 'text', '{"text":"A one-word reply ends the conversation and puts all the work on the customer. Every reply should answer the question, add one useful detail, and hand the conversation back with a question."}'::jsonb, 0),
  ('c7f80b61-67bd-5821-b923-b82ff70a1add', '0d7e5b42-d50e-557e-9bf6-198ca791cee7', 'comparison', '{"caption":"The three-part reply","columns":["One-word reply","Complete reply"],"rows":[["Yes.","Yes po, available pa ang Original flavour! Ready for delivery this week. Ilan pong packs ang balak niyo?"],["200.","The starter pack is ₱200 per unit po. Nasa loob na po ang delivery within Metro Manila. Would you like me to compute for 50 packs?"],["Wala pa.","Not yet available po ang Spicy variant - restock is next week. Gusto niyo po ba i-reserve ko na para sa inyo?"]]}'::jsonb, 1),
  ('cd84c531-e0fa-56b9-b5a4-3e55bc34e073', '0d7e5b42-d50e-557e-9bf6-198ca791cee7', 'dosdonts', '{"dos":["Always end with a question","Add one detail they did not ask for but will need"],"donts":["Reply \"yes\", \"no\", \"wala\", or \"opo\" alone","Send a bare price with no context"]}'::jsonb, 2),
  ('a5585d76-5adf-507e-ae4e-c3a4486758f6', '7505fd4e-1536-5655-b8f4-cd66795657ee', 'text', '{"text":"Chat is informal, but you are still the company. Proper capitalisation and complete words signal that a real, competent person is on the other side. Taglish is fine - text-speak is not."}'::jsonb, 0),
  ('8bbce5cb-8179-581c-8aa0-e5ccded4fc21', '7505fd4e-1536-5655-b8f4-cd66795657ee', 'wording', '{"pairs":[{"avoid":"ok po sure","use":"Sure po! 😊"},{"avoid":"wla po eh","use":"Wala pa po sa ngayon, but restock is next week."},{"avoid":"MAGKANO PO ORDER NYO","use":"How many packs po would you like to order?"},{"avoid":"thnx po","use":"Thank you po!"},{"avoid":"sry d ko alam","use":"Let me verify that for you po."}]}'::jsonb, 1),
  ('22978fd7-5753-51aa-aa58-6171f4554d8d', '7505fd4e-1536-5655-b8f4-cd66795657ee', 'checklist', '{"items":[{"text":"Sentences start with a capital letter"},{"text":"No ALL CAPS except a single word for emphasis"},{"text":"No text-speak: nyo → niyo, d → hindi, pls → please"},{"text":"One or two emoji per message, maximum","hint":"😊 and 🙏 carry most of the warmth you need"},{"text":"Never an emoji in a complaint or refund thread"}]}'::jsonb, 2),
  ('e0edc08b-1cdc-59c7-b8f2-ae273941abd8', '7505fd4e-1536-5655-b8f4-cd66795657ee', 'callout', '{"variant":"warning","title":"Emoji discipline","text":"Emoji soften a friendly message and undermine a serious one. Use them in greetings, thanks, and confirmations. Drop them entirely when a customer is upset, when money is disputed, or when you are delivering bad news."}'::jsonb, 3),
  ('e1143538-596e-527f-a4d2-352ac3bf6b80', '516e43cb-a388-5bc5-bcfd-6018905686ae', 'text', '{"text":"A wall of text gets skimmed, and a skimmed message means the customer misses the price or the cut-off. Break your answer into short messages, one idea each - but do not send eight messages in a row either."}'::jsonb, 0),
  ('d25da2e1-dd51-5dc0-a829-ec4b308a9172', '516e43cb-a388-5bc5-bcfd-6018905686ae', 'dosdonts', '{"dos":["Use their name once early and once when you close","Split a long answer into two or three short messages","Send the price, then the inclusions, then your question"],"donts":["Paste the full catalogue into one message","Send every flavour, every price, and every promo unasked","Machine-gun ten one-line messages"]}'::jsonb, 1),
  ('8e07ea17-a6c2-5697-885b-9408d1596904', '516e43cb-a388-5bc5-bcfd-6018905686ae', 'scenario', '{"customer":"New lead, asked only about price","situation":"Ma’am, magkano po lahat ng flavors?","response":"Hi Ms. Rivera! 😊 Ang starter pack po ay ₱200 per unit, minimum 50 packs. Kasama na po ang delivery sa Metro Manila. May tatlong flavour po kami - Original, Spicy, at Cheese. Ano pong flavour ang interesado kayo?","why":"It answers the actual question first, adds the two details she will need next (minimum and delivery), and hands back one simple question instead of the entire product list."}'::jsonb, 2),
  ('c1e47860-d040-5cef-81f4-c83059a112dd', '01241980-ff9b-56b6-95c7-cf354f3eb0ce', 'text', '{"text":"Chat is written and permanent. A screenshot of an argument, a wrong guess, or internal information travels further than any sale you make that day."}'::jsonb, 0),
  ('87cd7676-504e-53a0-9331-e034d2be2edd', '01241980-ff9b-56b6-95c7-cf354f3eb0ce', 'dosdonts', '{"dos":["Stay calm and factual even when the customer is not","Say \"let me verify\" instead of guessing","Escalate anything about refunds, permits, or supplier terms"],"donts":["Argue, correct their grammar, or match their tone","Guess at ingredients, shelf life, permits, or delivery windows","Share supplier names, internal pricing, margins, or other customers’ details","Promise a discount, refund, or exclusivity you cannot authorise"]}'::jsonb, 1),
  ('846e7a15-7f0f-50bd-a456-aa534f296e6b', '01241980-ff9b-56b6-95c7-cf354f3eb0ce', 'callout', '{"variant":"danger","title":"Unauthorised information","text":"Supplier identities, factory locations, internal cost, other resellers’ territories and volumes, and any unapproved promo are not yours to share. If a customer presses, say it is company-confidential and offer what you can share instead."}'::jsonb, 2),
  ('f9bc29f1-3844-5241-9926-fbc545dc0c18', '834a7dbd-8895-5d1f-baa3-2c74f42646bf', 'text', '{"text":"Most KCO chats begin with one of four messages. Having a real answer ready for each one is most of the job."}'::jsonb, 0),
  ('4697206d-450d-5d55-a735-9420a4ff4683', '834a7dbd-8895-5d1f-baa3-2c74f42646bf', 'scenario', '{"customer":"\"Send details po\"","situation":"A one-line request with no context at all.","response":"Sure po! 😊 Before I send, may I ask - are you planning to sell online, sa physical store, or for personal use? Para po ma-send ko yung tamang package details para sa inyo.","why":"Sending a generic brochure gets ignored. One qualifying question turns a cold request into a conversation and lets you send the package that actually fits."}'::jsonb, 1),
  ('c1bd24d0-dd22-54dc-ba4c-b6ac79bf5b1d', '834a7dbd-8895-5d1f-baa3-2c74f42646bf', 'scenario', '{"customer":"\"How much?\"","situation":"Price-first message, no other information.","response":"Hi po! Ang starter pack po ay ₱200 per unit, minimum 50 packs, delivery included sa Metro Manila. Para po sa reseller pricing, ilan pong packs ang tinitignan niyo?","why":"Answer the price directly - dodging it destroys trust. Then add the minimum and delivery so there are no surprises, and ask a question that moves toward volume."}'::jsonb, 2),
  ('1ea487ce-e82e-5bbd-8a8f-7a560d2c5492', '834a7dbd-8895-5d1f-baa3-2c74f42646bf', 'scenario', '{"customer":"\"Pag-iisipan ko po\"","situation":"Soft exit after you sent the details.","response":"Of course po, Ms. Rivera - take your time 😊 May I ask, ano pong part ang pinag-iisipan niyo, yung price or yung pagbebenta? Baka po may matulong ako para mas madali ang decision.","why":"Accept it, then clarify once. Thinking about it is not a no - it is an unnamed concern. One respectful question usually surfaces it."}'::jsonb, 3),
  ('3fa4543f-a50b-57e5-bdce-31fc109088a7', '834a7dbd-8895-5d1f-baa3-2c74f42646bf', 'callout', '{"variant":"success","title":"No pressure selling","text":"Never send repeated \"buy na po\" messages, false urgency, or guilt. One helpful follow-up is service. Three is harassment, and it costs KCO the referral too."}'::jsonb, 4),
  ('18d8b75d-3ad7-5bd4-bf31-aad21e32366f', '7d82e3b8-0305-54d9-8dd2-06295f4896e2', 'text', '{"text":"Nothing makes a customer repeat themselves faster than an agent who did not scroll up. Before your first message in an inherited thread, read the whole history and pick up where the last agent stopped."}'::jsonb, 0),
  ('73b3b052-439f-50f3-999d-75c406bc27c2', '7d82e3b8-0305-54d9-8dd2-06295f4896e2', 'checklist', '{"items":[{"text":"Scroll to the start of the thread"},{"text":"Note what was already quoted - price, flavour, quantity"},{"text":"Note any promise made and whether it was kept"},{"text":"Acknowledge the history in your first message"}]}'::jsonb, 1),
  ('e16c6919-e5e1-58d9-8899-9578c284a51e', '7d82e3b8-0305-54d9-8dd2-06295f4896e2', 'script', '{"label":"Taking over a thread","language":"mixed","lines":["Hi Ms. Rivera, this is Jason from KCO 😊","I have read your conversation with my colleague.","I see you are looking at 50 packs of Original for Friday delivery.","Let me take it from here po - shall I confirm that order?"]}'::jsonb, 2),
  ('5eb0f6d8-3b23-54b1-ba21-dc423a3e39df', '96247feb-4a2a-5fb0-97d8-feec500fbb41', 'text', '{"text":"A written confirmation is what protects both sides when something goes wrong. Send it as one clean message the customer can screenshot."}'::jsonb, 0),
  ('51475dac-dfc2-55d3-a644-79af41ab4c29', '96247feb-4a2a-5fb0-97d8-feec500fbb41', 'script', '{"label":"Order summary message","language":"mixed","lines":["Confirming your order po, Ms. Rivera 😊","Item: Kangkong Chips - Original","Quantity: 50 packs","Total: ₱10,000","Delivery: Friday, within Metro Manila","Payment: Cash on delivery","Delivery address: [full address]","Contact number: [number]","Tama po ba lahat?"]}'::jsonb, 1),
  ('b4c65335-4de0-5ce1-ac42-9740a209f932', '96247feb-4a2a-5fb0-97d8-feec500fbb41', 'checklist', '{"items":[{"text":"Item and flavour"},{"text":"Quantity"},{"text":"Total amount"},{"text":"Delivery date"},{"text":"Payment method"},{"text":"Complete delivery address"},{"text":"Contact number"},{"text":"Explicit \"tama po ba?\" confirmation received"}]}'::jsonb, 2),
  ('220b8314-15c8-5892-9bd6-954c73708ebe', 'dbcd3704-ffe8-5e87-965f-ecd3accf8458', 'numbered', '{"items":["Reply fast - a complaint left on seen becomes a public post.","Acknowledge the specific problem in their own words.","Apologise for the experience without assigning blame.","State what you will do and by when.","Follow up when you said you would, even if there is no news yet."]}'::jsonb, 0),
  ('fc38967d-540a-5824-88fb-fe5221b8ad17', 'dbcd3704-ffe8-5e87-965f-ecd3accf8458', 'script', '{"label":"Damaged goods complaint","language":"mixed","lines":["I am really sorry about this, Ms. Rivera.","To confirm po - 6 out of 50 packs arrived crushed?","I am filing this with our logistics team right now.","I will update you before 5 PM today with the replacement schedule.","Thank you for the photo, malaking tulong po ito sa report."]}'::jsonb, 1),
  ('72ca6091-71f0-5537-8347-b7350069974c', 'dbcd3704-ffe8-5e87-965f-ecd3accf8458', 'dosdonts', '{"dos":["Ask for a photo early","Give a reference number","Keep every promised follow-up"],"donts":["Use emoji in a complaint thread","Blame the courier by name","Say \"that never happens\"","Go quiet while waiting for a decision"]}'::jsonb, 2),
  ('65bce367-bb77-51fa-baa1-02c06a186056', 'dae04d0c-4232-5d1a-be50-75e50184fb15', 'script', '{"label":"Closing a chat","language":"mixed","lines":["Thank you po for your time, Ms. Rivera! 😊","Nandito lang po ako kung may tanong pa kayo.","Have a great day po!"]}'::jsonb, 0),
  ('65e8472e-ea49-5ae8-b858-11b29d5ce305', 'dae04d0c-4232-5d1a-be50-75e50184fb15', 'bullets', '{"items":["Never leave a chat on seen without a closing message.","Never end with \"ok\" or \"noted\" alone.","Never leave a question unanswered because the sale did not happen.","Never argue for the last word.","Never send screenshots of internal conversations.","Never use another reseller as a comparison by name."]}'::jsonb, 1),
  ('4ddd27e5-91a5-5dd1-9d3b-fd979f8dac4b', 'dae04d0c-4232-5d1a-be50-75e50184fb15', 'quiz', '{"question":"A customer sends only \"Send details po.\" What is the best first reply?","options":["Send the complete price list, all flavours, and all promos immediately.","Ask one qualifying question about how they plan to sell, then send the matching package.","Reply \"Sure po\" and wait for them to ask something specific.","Send a link to the Facebook page and let them read it."],"answerIndex":1,"explanation":"A generic brochure gets ignored, and a bare \"Sure po\" stalls. One qualifying question lets you send details that actually fit and keeps the conversation alive."}'::jsonb, 2)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
