-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 9 OF 23: Module 8: Product Knowledge - Kangkong Chips Line
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 8: Product Knowledge - Kangkong Chips Line
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('32020b5e-0919-557c-99ef-2adf9e8e15cf', 'product-knowledge', 'Product Knowledge - Kangkong Chips Line', 'Flavours, packaging, shelf life, and the facts you are allowed to state without verifying.', '368390d7-eb90-5113-b515-2b75504c63e6', 8, 'draft', 'foundation', 15, array['sales', 'admin']::public.user_role[], array['Phone Sales', 'Chat Support']::text[], array['product', 'facts', 'reference']::text[], true, null)
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('91689ce7-ad8b-5de2-9bae-ba83c2bef15d', '32020b5e-0919-557c-99ef-2adf9e8e15cf', 'What You Can State Without Checking', 'Draft - pending Admin verification of every figure.', 0, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('9794ac14-8f6e-5406-8300-09689902394a', '91689ce7-ad8b-5de2-9bae-ba83c2bef15d', 'callout', '{"variant":"warning","title":"Draft content","text":"This material is unpublished. Nothing here may be quoted to a customer until Admin has verified each figure with Operations and published the material."}'::jsonb, 0),
  ('357dee50-f458-5b14-aa6d-44238081e948', '91689ce7-ad8b-5de2-9bae-ba83c2bef15d', 'bullets', '{"items":["Flavour line-up: Original, Spicy, Cheese.","Packaging format and net weight - pending confirmation.","Shelf life - pending confirmation from Operations.","Storage guidance - pending confirmation."]}'::jsonb, 1)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
