-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 5 OF 23: Module 4: The KCO Chat Formula
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 4: The KCO Chat Formula
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('be0e0b89-149d-53d9-ad67-5021c25f6403', 'kco-chat-formula', 'The KCO Chat Formula', 'G.A.L.P.H.C.F.R. - the eight-move map for a chat conversation that can pause for a day and still close.', '1e1fb7c1-f3f4-583c-9a84-0efc7eb68854', 4, 'published', 'intermediate', 25, array['sales', 'admin']::public.user_role[], array['Chat Support']::text[], array['chat', 'formula', 'structure', 'follow-up']::text[], true, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('fd2fd6cc-5e6b-5ccc-87cf-54a186c9ecb6', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'The KCO Chat Formula', 'Eight letters that carry a chat from hello to a logged outcome.', 0, 'published'),
  ('43305c41-7a0b-5cdb-8fb4-258f8a8f7b2a', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'G - Greet', 'Named, warm, and inside two minutes.', 1, 'published'),
  ('0dbe9b38-ec91-5cc2-bb2b-4ff685a65230', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'A - Ask', 'One question before any details leave your keyboard.', 2, 'published'),
  ('b8f78fe7-6378-5830-8db6-89520f55fbba', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'L - Listen', 'Read the whole message. Answer the real question.', 3, 'published'),
  ('e680734b-d6c3-5aec-91e4-0b1e674d291d', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'P - Present', 'One recommendation, in their words.', 4, 'published'),
  ('0c3e9c26-ab98-5de9-8860-76e72c901eab', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'H - Handle', 'A.C.A.C., in writing.', 5, 'published'),
  ('9b129473-e5c5-58ad-a4e0-127ef793aadb', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'C - Close', 'Specific, small, dated.', 6, 'published'),
  ('abef4657-17aa-5c81-a8f6-1d9b6985fdd1', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'F - Follow Up', 'One helpful message. Not three.', 7, 'published'),
  ('70319efc-df29-56a4-b7d9-38f957a7e123', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 'R - Report', 'The step everyone skips, and the one that makes the team work.', 8, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('30295428-9041-5bd9-ad19-b3e496da3aaa', 'fd2fd6cc-5e6b-5ccc-87cf-54a186c9ecb6', 'text', '{"text":"Phone calls have the 8-step structure. Chat has G.A.L.P.H.C.F.R. It exists because chat is asynchronous - the customer can vanish for a day and come back mid-thought, so you need a map you can rejoin at any point."}'::jsonb, 0),
  ('6c46eb59-94f6-5ed5-b6bf-132f6fa84d8c', 'fd2fd6cc-5e6b-5ccc-87cf-54a186c9ecb6', 'formula', '{"name":"G.A.L.P.H.C.F.R.","steps":[{"key":"G","label":"Greet","detail":"Warm greeting, your name, thanks for messaging."},{"key":"A","label":"Ask","detail":"One qualifying question before any details go out."},{"key":"L","label":"Listen","detail":"Read the whole message. Answer what was actually asked."},{"key":"P","label":"Present","detail":"Recommend one package, matched to their answer."},{"key":"H","label":"Handle","detail":"Run A.C.A.C. on whatever concern comes back."},{"key":"C","label":"Close","detail":"Ask for a specific, dated next step."},{"key":"F","label":"Follow Up","detail":"One helpful check-in if the thread goes quiet."},{"key":"R","label":"Report","detail":"Log the outcome so the next agent inherits context."}]}'::jsonb, 1),
  ('c0975dc6-557f-51f0-a859-12921bb6bb2d', 'fd2fd6cc-5e6b-5ccc-87cf-54a186c9ecb6', 'quote', '{"text":"Don''t just reply to the customer. Guide the customer toward the right solution.","attribution":"KCO Golden Rule - Chat Support"}'::jsonb, 2),
  ('6b087b5a-12df-5400-97d2-e69968896f08', '43305c41-7a0b-5cdb-8fb4-258f8a8f7b2a', 'script', '{"label":"Greet","language":"mixed","lines":["Hi po! Good morning 😊","Thank you for messaging KCO Kangkong Chips.","This is Jason - how may I help you today?"]}'::jsonb, 0),
  ('2108936b-cc08-5755-8773-e4ea853770fe', '43305c41-7a0b-5cdb-8fb4-258f8a8f7b2a', 'bullets', '{"items":["Give your name - customers trust a person more than a page.","Thank them for messaging before anything else.","If you are late, apologise for the wait in the same message."]}'::jsonb, 1),
  ('f29a7ee8-8017-54ee-8f50-be4e21b34668', '0dbe9b38-ec91-5cc2-bb2b-4ff685a65230', 'text', '{"text":"Asking first is what separates chat support from a vending machine. It costs one message and it changes everything you send afterwards."}'::jsonb, 0),
  ('f2e9c316-a0bb-57ee-a2be-d0ad29945e6f', '0dbe9b38-ec91-5cc2-bb2b-4ff685a65230', 'numbered', '{"items":["Are you planning to sell, or is this for personal use?","Online, physical store, or both?","Have you resold food products before?","Which area are you in? (for delivery options)"]}'::jsonb, 1),
  ('632718f1-a0d5-5bb2-8a87-8ab6cb48378f', '0dbe9b38-ec91-5cc2-bb2b-4ff685a65230', 'callout', '{"variant":"warning","title":"One question at a time","text":"Four questions in one message reads like a form and gets one answer at best. Ask the most useful one, wait, then ask the next."}'::jsonb, 2),
  ('258e6d7f-a271-5ea3-8362-d5173bcc0d56', 'b8f78fe7-6378-5830-8db6-89520f55fbba', 'text', '{"text":"Chat makes it easy to reply to the first line and miss the second. If a customer asks about price and delivery, answering only the price guarantees a follow-up you could have avoided."}'::jsonb, 0),
  ('ab0af028-a617-592d-b341-de9bf43f7259', 'b8f78fe7-6378-5830-8db6-89520f55fbba', 'comparison', '{"caption":"Answer everything they asked","columns":["Customer asked","A complete reply covers"],"rows":[["Magkano at kailan ma-deliver?","Price, delivery window, and cut-off for that window"],["May Spicy pa ba? Pwede ba 20 packs?","Stock status and the minimum order quantity"],["Pwede ba COD sa Cavite?","Payment options and Cavite delivery specifics"]]}'::jsonb, 1),
  ('bd6777b5-2419-5e7e-9caa-2ccb988905bb', 'b8f78fe7-6378-5830-8db6-89520f55fbba', 'dosdonts', '{"dos":["Re-read before hitting send","Answer in the order they asked"],"donts":["Answer only the easy half","Reply to a message you skimmed"]}'::jsonb, 2),
  ('88850171-c1bc-5e59-9757-d3fb65ff19a9', 'e680734b-d6c3-5aec-91e4-0b1e674d291d', 'script', '{"label":"Present in chat","language":"mixed","lines":["Since online selling po ang plan niyo and first time as reseller,","the starter pack is the best fit 😊","50 packs at ₱200 each, delivery included sa Metro Manila.","Kasama na rin po ang product photos at captions na pwede niyo agad i-post.","Gusto niyo po bang i-reserve ko na para sa Friday delivery?"]}'::jsonb, 0),
  ('8571a639-1610-5d27-8066-d3ac7ebda07a', 'e680734b-d6c3-5aec-91e4-0b1e674d291d', 'callout', '{"variant":"warning","title":"Illustrative only - pending Admin review","text":"If a customer asks about earnings, keep it clearly hypothetical and never guarantee an outcome. Margins depend on their own selling price, area, and effort."}'::jsonb, 1),
  ('32e0aa5f-a0ef-5286-83be-64374ecba252', '0c3e9c26-ab98-5de9-8860-76e72c901eab', 'formula', '{"name":"A.C.A.C. in chat","steps":[{"key":"A","label":"Acknowledge","detail":"\"I understand po\" - then stop. Do not defend yet."},{"key":"C","label":"Clarify","detail":"One question: which part is the concern?"},{"key":"A","label":"Address","detail":"Answer that exact concern, in two or three short messages."},{"key":"C","label":"Close","detail":"Return to a dated next step."}]}'::jsonb, 0),
  ('c1e47b30-246e-5f76-89aa-050a6eb1b352', '0c3e9c26-ab98-5de9-8860-76e72c901eab', 'scenario', '{"customer":"Price objection in chat","situation":"Ang mahal naman po. May mas mura ba?","response":"I understand po, Ms. Rivera 😊 May I ask - mahal po ba compared sa budget niyo, or compared sa iba pong supplier? … Kung budget po ang concern, the starter pack is our smallest order kaya mababa ang first commitment. Gusto niyo po bang i-compute natin per pack para makita niyo ang margin?","why":"It acknowledges without agreeing, clarifies which kind of \"expensive\" this is, addresses the actual version, and closes on a small next step rather than a hard ask."}'::jsonb, 1),
  ('c5e6567f-a8c0-5faf-91d1-6632caf0f71a', '9b129473-e5c5-58ad-a4e0-127ef793aadb', 'comparison', '{"caption":"Closes that work in chat","columns":["Avoid","Use"],"rows":[["Let me know po 😊","Gusto niyo po bang i-reserve ko para sa Friday?"],["Interested po ba kayo?","Friday or Monday po ang mas okay sa delivery?"],["Sige po, message lang kayo.","I will hold one starter pack for you until tomorrow - okay po ba?"]]}'::jsonb, 0),
  ('3c4c6d27-1592-5f88-8de4-f6744200dc43', '9b129473-e5c5-58ad-a4e0-127ef793aadb', 'checklist', '{"items":[{"text":"A specific action named"},{"text":"A date or time attached"},{"text":"Easy for the customer to say yes to"},{"text":"Asked once, not repeated"}]}'::jsonb, 1),
  ('fa831e0a-9223-52c1-87a8-8ca50100b613', 'abef4657-17aa-5c81-a8f6-1d9b6985fdd1', 'text', '{"text":"A follow-up should add something - a restock date, a photo, an answer you promised. A follow-up that only says \"po?\" is pressure, and pressure loses the referral even when it wins the order."}'::jsonb, 0),
  ('ecde05e0-d5d9-5934-a8b0-d5e143d145f5', 'abef4657-17aa-5c81-a8f6-1d9b6985fdd1', 'script', '{"label":"Follow-up that adds value","language":"mixed","lines":["Hi Ms. Rivera! 😊 Following up po sa inquiry niyo.","Ito po pala yung sample photos na pwede niyo i-post pag nag-start na kayo.","Nandito lang po ako kung may tanong kayo - no rush po."]}'::jsonb, 1),
  ('e7c5b3e8-f495-5528-a0e6-4ad74f6f8b54', 'abef4657-17aa-5c81-a8f6-1d9b6985fdd1', 'comparison', '{"caption":"Follow-up cadence","columns":["When","What to send"],"rows":[["24 hours after details sent","A useful asset plus an open offer to answer questions"],["3 days after that","A relevant update - restock, new flavour, delivery schedule"],["After that","Stop. Move the lead to the long-term list."]]}'::jsonb, 2),
  ('da358404-54c5-5ea8-9904-568f2a8fdd77', 'abef4657-17aa-5c81-a8f6-1d9b6985fdd1', 'callout', '{"variant":"danger","title":"Two follow-ups maximum","text":"After two unanswered follow-ups, stop messaging and log the lead as cold. Repeated messages get the page reported and cost far more than one lost sale."}'::jsonb, 3),
  ('8ca7697a-1c2c-524a-b43e-1aab6bced39d', '70319efc-df29-56a4-b7d9-38f957a7e123', 'text', '{"text":"The next agent to open that thread - maybe you, on a Monday - needs to know what was quoted, what was promised, and what the objection was. Reporting is how a chat becomes company knowledge instead of a private conversation."}'::jsonb, 0),
  ('cf3976f6-4207-5441-8aca-e884e2b47fc3', '70319efc-df29-56a4-b7d9-38f957a7e123', 'checklist', '{"items":[{"text":"Outcome logged","hint":"Ordered / interested / cold / complaint"},{"text":"Quantity and flavour quoted"},{"text":"Objection recorded in the customer’s own words"},{"text":"Any promise made, and its deadline"},{"text":"Next action and date"}]}'::jsonb, 1),
  ('0dbc9b64-5124-5cbf-97d2-cca9ff35f982', '70319efc-df29-56a4-b7d9-38f957a7e123', 'quiz', '{"question":"A chat lead has not replied to your details or your first follow-up. What does the formula say to do?","options":["Send a daily follow-up until they answer.","Send one more follow-up with something genuinely useful, then stop and log the lead as cold.","Stop immediately - one follow-up is the limit.","Call their number instead, repeatedly."],"answerIndex":1,"explanation":"Two follow-ups maximum, and each one must add value. After that, log the outcome (R - Report) and move on. Persistent messaging gets pages reported and damages the brand."}'::jsonb, 2)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
