-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 7 OF 23: Module 6: Training Activities
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 6: Training Activities
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('7925a399-92cf-5df4-8141-a93febf41e7c', 'training-activities', 'Training Activities', 'Eight facilitator-led exercises, matched to the specific habit each one fixes.', 'e0f82390-0ad6-519b-9e95-a7c35d3ab972', 6, 'published', 'intermediate', 30, array['admin', 'sales']::public.user_role[], array['Training', 'Phone Sales', 'Chat Support']::text[], array['activities', 'facilitation', 'huddle', 'roleplay']::text[], false, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('d89269d3-b060-504d-b83b-bede91b63de6', '7925a399-92cf-5df4-8141-a93febf41e7c', 'How to Run a Training Huddle', 'Thirty minutes, one skill, one visible improvement.', 0, 'published'),
  ('a86cf9c6-506e-5bde-99c5-4c4a8a0c3c80', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Don''t Say Yes or No', 'Break the habit of one-word answers and force agents to give complete, useful replies under pressure.', 1, 'published'),
  ('e52a4a57-c273-50df-beeb-7bf3edda9819', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Sell It in 10 Seconds', 'Force a sharp, benefit-first pitch by removing every spare second.', 2, 'published'),
  ('f431f2d5-138c-5edc-be21-6896f6766e9d', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Pass the Sales', 'Practise picking up a call mid-flow and continuing without restarting the pitch.', 3, 'published'),
  ('9010e04b-e44a-5b65-b4b1-188d707d9ac3', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Customer Acting', 'Build composure against difficult customer personalities before meeting one live.', 4, 'published'),
  ('6c05c39e-de59-5871-8f74-53513a6c40d5', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Bad Accent / Bad Sales', 'Show - by exaggeration - exactly which delivery habits lose a customer, so agents can hear them in themselves.', 5, 'published'),
  ('caf664c3-61a5-56f8-9a61-ec5a29ee4ded', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Two Truths, One Lie - Product Edition', 'Expose gaps in product knowledge and kill the habit of guessing.', 6, 'published'),
  ('f379eb85-773d-5116-b185-350deba63bd1', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Movie Trailer Sales Pitch', 'Practise storytelling and vocal energy in a low-stakes, memorable format.', 7, 'published'),
  ('7c65cbad-d937-5c5a-8d2c-f0fe1aeb9ae2', '7925a399-92cf-5df4-8141-a93febf41e7c', 'Dramatic Sales Pitch', 'Stretch emotional range so a normal call feels effortless by comparison.', 8, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('61d7f9e8-fd40-5d74-a307-b513a9e5d8b6', 'd89269d3-b060-504d-b83b-bede91b63de6', 'text', '{"text":"These activities work in a 20-30 minute huddle before shift. Pick one skill, run one activity, and end with each agent naming one thing they will do differently on their next call. Do not run three activities in a row - nothing sticks."}'::jsonb, 0),
  ('35178600-1c0c-5dc3-876e-035186c4e596', 'd89269d3-b060-504d-b83b-bede91b63de6', 'numbered', '{"items":["Name the skill in one sentence before you start.","Run the activity - keep it moving, do not over-explain.","Debrief with specifics: what worked, what broke, what to change.","Each agent commits to one concrete change out loud.","Log the session in Activity Logs so progress is visible."]}'::jsonb, 1),
  ('4a8368e5-fbb8-51e2-98f0-5d68d4c37c7e', 'd89269d3-b060-504d-b83b-bede91b63de6', 'callout', '{"variant":"success","title":"Facilitator rule","text":"Praise in public, correct in private. Never use an activity to embarrass an agent in front of the team - you will lose participation for weeks."}'::jsonb, 2),
  ('990d9b45-6431-5cbf-a0b3-ad6f09cd610c', 'd89269d3-b060-504d-b83b-bede91b63de6', 'comparison', '{"caption":"Match the activity to the problem","columns":["What the team is struggling with","Run this"],"rows":[["One-word chat replies","Don''t Say Yes or No"],["Rambling, unfocused pitches","Sell It in 10 Seconds"],["Making customers repeat themselves","Pass the Sales"],["Freezing on angry customers","Customer Acting"],["Flat, monotone delivery","Bad Accent / Bad Sales"],["Guessing product facts","Two Truths, One Lie"],["Low energy mid-week","Movie Trailer Sales Pitch"],["Tone that never varies","Dramatic Sales Pitch"]]}'::jsonb, 3),
  ('680e8473-94da-5778-b15c-ba8c5fc6c8ec', 'a86cf9c6-506e-5bde-99c5-4c4a8a0c3c80', 'activity', '{"activityId":"act-no-yes-no"}'::jsonb, 0),
  ('460d6a72-9560-52c1-9df8-c6b6a8db76f8', 'a86cf9c6-506e-5bde-99c5-4c4a8a0c3c80', 'numbered', '{"items":["Pair up. One is the customer, one is the agent.","The customer asks rapid questions designed to invite yes/no answers - \"May stock pa po?\", \"Pwede COD?\", \"Mahal ba?\"","The agent must answer completely without ever using the words yes, no, opo, or hindi.","Every complete answer must add one detail and end with a question.","Run 90 seconds, then swap roles.","Score one point per slip. Lowest score wins the round."]}'::jsonb, 1),
  ('567e73ea-874f-5bbb-afd0-f68a4a8ccdf8', 'a86cf9c6-506e-5bde-99c5-4c4a8a0c3c80', 'callout', '{"variant":"info","title":"Facilitator notes","text":"Keep the pace fast - the pressure is the point. Listen for the three-part reply: answer, added detail, question back. Call out good rephrasings out loud so the group hears the pattern. Common failure: agents pause too long searching for words. Tell them a short natural pause beats a wrong word."}'::jsonb, 2),
  ('75c2a17d-3d29-5274-a79d-8852c3f95851', 'a86cf9c6-506e-5bde-99c5-4c4a8a0c3c80', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents stop reflexively answering in one word and start building replies that keep the conversation moving."}'::jsonb, 3),
  ('4264484b-06d6-51f4-a4e3-8702d51dcc77', 'e52a4a57-c273-50df-beeb-7bf3edda9819', 'activity', '{"activityId":"act-10-seconds"}'::jsonb, 0),
  ('25a31e83-357e-58d9-a5bd-2a711b1e3c1c', 'e52a4a57-c273-50df-beeb-7bf3edda9819', 'numbered', '{"items":["Each agent gets 10 seconds to pitch Kangkong Chips to the group.","The pitch must include one benefit and one call to action.","The facilitator times strictly and cuts off at 10 seconds mid-word.","The group votes on the clearest pitch, not the loudest.","Second round: same agent, same 10 seconds, but a different audience - a sari-sari store owner, an online seller, a parent."]}'::jsonb, 1),
  ('bd389662-2a23-51b3-ab34-49a3cabd04f9', 'e52a4a57-c273-50df-beeb-7bf3edda9819', 'callout', '{"variant":"info","title":"Facilitator notes","text":"Cut people off exactly at 10 seconds. The discomfort is the lesson. Watch for feature-dumping - \"crunchy, healthy, affordable, three flavours\" is a list, not a pitch. The second round is where the learning lands: the same product needs a different angle per audience."}'::jsonb, 2),
  ('021c0fc5-7815-5cfb-9e22-caa23c3db9cc', 'e52a4a57-c273-50df-beeb-7bf3edda9819', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents can open with one benefit tied to the listener instead of reciting product features."}'::jsonb, 3),
  ('fd477cad-2b47-5b79-a2e1-90cac56dc3a2', 'f431f2d5-138c-5edc-be21-6896f6766e9d', 'activity', '{"activityId":"act-pass-the-sales"}'::jsonb, 0),
  ('7ba01a2a-9fd6-5a17-a14f-ca0b4019c68a', 'f431f2d5-138c-5edc-be21-6896f6766e9d', 'numbered', '{"items":["One facilitator plays a single customer for the whole round.","Agent 1 starts the call at Step 1 - Greet.","On the facilitator’s clap, the next agent continues from exactly where the last one stopped.","No restarting, no re-introducing, no repeating information already given.","The circle continues until the call reaches Step 8 - Confirm + End.","Debrief: where did the thread break, and why?"]}'::jsonb, 1),
  ('f9384a7e-8cfe-5524-8fc1-32d735f98055', 'f431f2d5-138c-5edc-be21-6896f6766e9d', 'callout', '{"variant":"info","title":"Facilitator notes","text":"Clap at awkward moments - mid-objection is the most useful place to hand over. Introduce a detail early (a name, a quantity) and see how many agents remember it. This mirrors a real inherited chat thread; connect it to Module 3, Section 07."}'::jsonb, 2),
  ('f8b78266-c806-5bba-8946-05d5293468c4', 'f431f2d5-138c-5edc-be21-6896f6766e9d', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents listen actively even when they are not speaking, and can resume a conversation without making the customer repeat themselves."}'::jsonb, 3),
  ('a5fa05d9-f549-59e7-92f7-1545f60bf6db', '9010e04b-e44a-5b65-b4b1-188d707d9ac3', 'activity', '{"activityId":"act-customer-acting"}'::jsonb, 0),
  ('3c7139a4-63be-5ee6-a6b7-dc6a5ef0a4be', '9010e04b-e44a-5b65-b4b1-188d707d9ac3', 'numbered', '{"items":["Draw a personality card: Angry, Sleepy, Confused, Cheap, Funny, Seen Zone, Super Curious, or \"I''m Busy\".","The customer plays that personality without telling the agent which card they drew.","The agent runs a real call and must adapt in the moment.","After three minutes, the agent guesses the personality.","Debrief: what tell gave it away, and what did the agent change in response?"]}'::jsonb, 1),
  ('9794b3a7-3089-5588-989b-37a23510d337', '9010e04b-e44a-5b65-b4b1-188d707d9ac3', 'callout', '{"variant":"info","title":"Facilitator notes","text":"Cap the Angry customer at three minutes - it gets heavy quickly. Remind actors to play a personality, not an insult; no personal attacks. The strongest agents change pace and question style, not their script. Pair with Practice Scenarios for solo repetition afterwards."}'::jsonb, 2),
  ('da989616-dc1d-58b7-b555-7a1771e72f68', '9010e04b-e44a-5b65-b4b1-188d707d9ac3', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents read customer mood quickly and adjust pace, tone, and question style instead of pushing the same pitch harder."}'::jsonb, 3),
  ('6d5f66b7-c72d-5769-8eb1-4c5e232508d6', '6c05c39e-de59-5871-8f74-53513a6c40d5', 'activity', '{"activityId":"act-bad-accent"}'::jsonb, 0),
  ('c1418652-c3ca-5c4a-ae73-7ffca84eb4c2', '6c05c39e-de59-5871-8f74-53513a6c40d5', 'numbered', '{"items":["Round 1: each agent deliberately performs the worst possible call - mumbling, rushing, interrupting, reading the script flatly.","The group notes every specific mistake they hear.","Round 2: the same agent runs the same call properly.","The group names the single biggest improvement between the two."]}'::jsonb, 1),
  ('f67e2c22-b7b0-5161-b1cb-038a2c2ab9a0', '6c05c39e-de59-5871-8f74-53513a6c40d5', 'callout', '{"variant":"info","title":"Facilitator notes","text":"This is a comedy exercise with a serious point - let the laughter happen, then get specific in the debrief. Never mock a real accent. The target is delivery habits: pace, clarity, interruption, monotone. Write the group’s list of \"bad habits\" on the board and keep it visible for the week."}'::jsonb, 2),
  ('bcfc9d06-9e79-5aba-9994-97300e69151d', '6c05c39e-de59-5871-8f74-53513a6c40d5', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents can name their own worst delivery habit and demonstrate the corrected version on demand."}'::jsonb, 3),
  ('cc814ab2-599b-5c0b-95aa-5a96184234d6', 'caf664c3-61a5-56f8-9a61-ec5a29ee4ded', 'activity', '{"activityId":"act-two-truths"}'::jsonb, 0),
  ('479a574b-c20e-50cb-89fb-9adf57dd79a5', 'caf664c3-61a5-56f8-9a61-ec5a29ee4ded', 'numbered', '{"items":["Each agent states three claims about KCO Kangkong Chips - two true, one invented.","The group votes on which is the lie.","The agent reveals the answer and cites where the true facts come from.","Any claim nobody can source goes on the \"verify with Admin\" list."]}'::jsonb, 1),
  ('378697ee-71b3-5937-a76d-68d0ad4214ab', 'caf664c3-61a5-56f8-9a61-ec5a29ee4ded', 'callout', '{"variant":"info","title":"Facilitator notes","text":"The \"verify\" list is the real output of this exercise - send it to Admin afterwards. Watch for confident wrong answers about shelf life, ingredients, and permits; these are the dangerous ones. Connect directly to Module 1, Section 10 - never invent product facts."}'::jsonb, 2),
  ('5d961db1-7b0b-511b-89cb-16eb164e11c3', 'caf664c3-61a5-56f8-9a61-ec5a29ee4ded', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents know which product facts they can state confidently and which they must verify before answering."}'::jsonb, 3),
  ('52eb3dbd-9720-586e-ad75-daff25cc41a1', 'f379eb85-773d-5116-b185-350deba63bd1', 'activity', '{"activityId":"act-movie-trailer"}'::jsonb, 0),
  ('308c0849-b035-5187-a8e6-6af312eb182d', 'f379eb85-773d-5116-b185-350deba63bd1', 'numbered', '{"items":["Each agent pitches Kangkong Chips as a movie trailer - \"In a world where merienda is boring…\"","The pitch must still contain one real product benefit and one real call to action.","Maximum 45 seconds.","The group votes for the most entertaining and the most persuasive - separately.","Debrief on the gap between those two winners."]}'::jsonb, 1),
  ('40b1810d-cebb-592f-b06a-ff4c3005f738', 'f379eb85-773d-5116-b185-350deba63bd1', 'callout', '{"variant":"info","title":"Facilitator notes","text":"The split vote is the whole point: entertaining is not the same as persuasive. Use this to talk about energy level - trailer energy is too much for a real call, but flat energy is too little. Best used mid-week, when energy dips."}'::jsonb, 2),
  ('29d29e71-32b6-50ad-914e-aeb7ee5a3415', 'f379eb85-773d-5116-b185-350deba63bd1', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents find a higher, more engaged vocal register and understand where the line between energetic and theatrical sits."}'::jsonb, 3),
  ('41ecca9f-9a80-5089-b5f3-f28058f91299', '7c65cbad-d937-5c5a-8d2c-f0fe1aeb9ae2', 'activity', '{"activityId":"act-dramatic-pitch"}'::jsonb, 0),
  ('ed683a31-dcd1-5072-8a2a-139543bcc058', '7c65cbad-d937-5c5a-8d2c-f0fe1aeb9ae2', 'numbered', '{"items":["Draw an emotion card: heartbroken, triumphant, mysterious, panicked, or deeply sincere.","Deliver the full 8-step call in that emotional register.","The partner scores whether every step still appeared, despite the drama.","Final round: deliver the same call in a normal professional register and compare how easy it feels."]}'::jsonb, 1),
  ('2eb8408d-fbd8-56a1-acbf-9c3118373b11', '7c65cbad-d937-5c5a-8d2c-f0fe1aeb9ae2', 'callout', '{"variant":"info","title":"Facilitator notes","text":"The final normal round is the actual exercise - everything before it is calibration. Check that the eight steps survive; drama often eats Discover and Confirm. Good closing activity for a training day."}'::jsonb, 2),
  ('8a08454a-8208-562a-beca-b5161961766e', '7c65cbad-d937-5c5a-8d2c-f0fe1aeb9ae2', 'callout', '{"variant":"success","title":"Expected outcome","text":"Agents control tone deliberately rather than defaulting to a flat register, and the standard call feels comfortable."}'::jsonb, 3)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
