-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 2 OF 23: Module 1: Phone Etiquette
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 1: Phone Etiquette
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('2e397237-467e-5050-a02a-677dbd0dab8d', 'phone-etiquette', 'Phone Etiquette', 'How to answer, hold, recover, and close on the phone - from the first seven seconds to the hang-up.', '5364da32-b801-5422-903e-295b008b9416', 1, 'published', 'foundation', 35, array['sales', 'admin']::public.user_role[], array['Phone Sales', 'Chat Support', 'Field Sales']::text[], array['phone', 'etiquette', 'tone', 'foundation']::text[], false, now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('7072367e-f0f1-5b8e-8d73-5f41ed68778d', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Answer Professionally', 'The first seven seconds decide whether the customer keeps listening.', 0, 'published'),
  ('5fcca47f-0017-5b68-be47-749b2a7a2aab', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Smile Before Speaking', 'A smile changes the shape of your mouth and the tone of your voice.', 1, 'published'),
  ('cd8ef471-a2f3-52d2-a7bc-2f44a6fbeb69', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Speak Clearly', 'Pace, volume, and articulation - before vocabulary.', 2, 'published'),
  ('1a5adcec-44ae-50f3-85f0-9d1040426a75', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Don''t Interrupt', 'Let the customer finish. The last three words usually carry the real objection.', 3, 'published'),
  ('1b68b92c-164b-520c-93ad-b4fcc52e50eb', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Use the Customer''s Name', 'Two or three times per call - enough to feel personal, not rehearsed.', 4, 'published'),
  ('a7d0b483-d0bf-593b-9d7a-57edaa5929a8', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Ask Questions', 'A discovery question is worth more than three product features.', 5, 'published'),
  ('8d816fd6-bcdf-5e3c-9720-1d09906709f3', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Don''t Sound Like You''re Reading a Script', 'Learn the structure, then speak like a person.', 6, 'published'),
  ('87970a56-2ba3-5da6-a652-bee329f5d62d', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Handling "I’m Busy"', 'Do not push. Take a smaller commitment instead.', 7, 'published'),
  ('63dcd26c-eac6-5536-9526-d97e8dcc3178', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Handling Angry Customers', 'Let them finish, own the problem, give the next step.', 8, 'published'),
  ('b56d3071-9cbd-5217-b56e-485435eda2f5', '2e397237-467e-5050-a02a-677dbd0dab8d', 'When You Don''t Know the Answer', 'Verify. Never invent.', 9, 'published'),
  ('006454d2-9d4c-5c1f-852a-79b8a4590b63', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Phone Hold Etiquette', 'Ask, explain, thank - and never exceed the time you promised.', 10, 'published'),
  ('1b1c848c-7536-5c76-b14c-4d60757b605e', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Call Drops', 'Whoever called, calls back. Always the agent.', 11, 'published'),
  ('2eec8ea3-c0d7-5102-ac43-4c1c22961c09', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Never Eat While on a Call', 'It is audible, and it reads as disrespect.', 12, 'published'),
  ('f0030f0a-212f-5093-9a6b-094de87665c7', '2e397237-467e-5050-a02a-677dbd0dab8d', 'Professional Wording', 'Same meaning, better delivery. The full library lives in Quick Reference.', 13, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('7f912431-747d-531e-b7f7-220862af0f0e', '7072367e-f0f1-5b8e-8d73-5f41ed68778d', 'text', '{"text":"A prospect cannot see your office, your ID, or your product. The only evidence they have that KCO is a real, professional company is the first sentence you say. Answer the same way every time so it becomes muscle memory."}'::jsonb, 0),
  ('fb785582-23b9-5d37-a6cc-86ed6c19063c', '7072367e-f0f1-5b8e-8d73-5f41ed68778d', 'script', '{"label":"Standard outbound opening","language":"mixed","lines":["Good morning! This is Jason from KCO Kangkong Chips.","Am I speaking with Ms. Rivera?","I am following up on your inquiry about becoming a KCO reseller.","Is now a good time for a quick two-minute call?"]}'::jsonb, 1),
  ('8159a878-5c69-5a85-af45-f706dcaf12c5', '7072367e-f0f1-5b8e-8d73-5f41ed68778d', 'checklist', '{"items":[{"text":"Greet with the time of day","hint":"Good morning / afternoon / evening"},{"text":"Give your first name"},{"text":"Say the company name in full - KCO Kangkong Chips"},{"text":"Confirm you are speaking to the right person"},{"text":"State why you are calling in one sentence"},{"text":"Ask permission for their time"}]}'::jsonb, 2),
  ('1634ccd9-dacc-5c6a-9099-e8ac7de2e7ad', '7072367e-f0f1-5b8e-8d73-5f41ed68778d', 'dosdonts', '{"dos":["Answer within three rings","Sit up straight - posture is audible","Have the inquiry details on screen before you dial"],"donts":["Answer with a bare \"Hello?\"","Mumble the company name","Launch into the offer before confirming who you are talking to"]}'::jsonb, 3),
  ('ced30f10-2b11-5211-a2d4-72c7246e6cc9', '5fcca47f-0017-5b68-be47-749b2a7a2aab', 'text', '{"text":"Smiling raises the pitch and softens the edges of your voice. The customer cannot see it, but they can hear the difference immediately - and so can you, if you record yourself twice and compare."}'::jsonb, 0),
  ('1bd739ff-95cd-52da-888a-1ea794ac8af5', '5fcca47f-0017-5b68-be47-749b2a7a2aab', 'callout', '{"variant":"info","title":"Try this before your first call of the day","text":"Say your opening line twice into a recorder: once flat, once smiling. Play both back. The smiling version is the one a customer trusts."}'::jsonb, 1),
  ('9dc51810-d7bd-5a3d-9de4-6ba7b226b224', '5fcca47f-0017-5b68-be47-749b2a7a2aab', 'bullets', '{"items":["Keep a small mirror at your station - it is the cheapest coaching tool available.","Stand up for difficult calls; your breath support improves and your energy carries.","If you have had a hard call, take ten seconds and reset before dialling the next one."]}'::jsonb, 2),
  ('10fc18ec-861e-5a9e-af44-041f2ceb2c8d', 'cd8ef471-a2f3-52d2-a7bc-2f44a6fbeb69', 'text', '{"text":"Most unclear calls are not accent problems. They are speed problems. When you are nervous you speed up, and the customer stops absorbing details like price, minimum order, and delivery time - exactly the details that close a sale."}'::jsonb, 0),
  ('b394ea2a-dcab-54b2-b05a-084bbcc5b096', 'cd8ef471-a2f3-52d2-a7bc-2f44a6fbeb69', 'comparison', '{"caption":"Slow down where it counts","columns":["Say this at normal pace","Slow down deliberately here"],"rows":[["Small talk and rapport","Prices and package amounts"],["Explaining the product story","Minimum order quantity"],["Answering general questions","Delivery timelines and cut-offs"],["Closing pleasantries","Your name and callback number"]]}'::jsonb, 1),
  ('81a5b749-b3b4-5f17-a9ce-ab281651eb73', 'cd8ef471-a2f3-52d2-a7bc-2f44a6fbeb69', 'checklist', '{"items":[{"text":"Numbers said twice","hint":"Say the figure, then repeat it"},{"text":"Mouth roughly a fist away from the mic"},{"text":"No gum, no food, no drink"},{"text":"Background noise checked before dialling"}]}'::jsonb, 2),
  ('7d387d2f-c490-5ab5-96b2-512cf6ea0ffa', '1a5adcec-44ae-50f3-85f0-9d1040426a75', 'text', '{"text":"Interrupting costs you the information you need most. When a customer trails off, they are often about to name the real hesitation - budget, a spouse who decides, a bad experience with another supplier."}'::jsonb, 0),
  ('487eaa22-1a23-5f49-ac95-da2249408f2d', '1a5adcec-44ae-50f3-85f0-9d1040426a75', 'dosdonts', '{"dos":["Wait a full beat after they stop speaking","Use short acknowledgements: \"I see\", \"Got it\", \"Understood\"","Take notes instead of talking"],"donts":["Finish their sentence for them","Talk over a complaint to defend the product","Jump to the price the moment you hear hesitation"]}'::jsonb, 1),
  ('97bd6570-5ca3-56ff-9207-a0733b6d4955', '1a5adcec-44ae-50f3-85f0-9d1040426a75', 'callout', '{"variant":"success","title":"The two-second rule","text":"Count two silent seconds after the customer finishes before you reply. It feels long to you and natural to them, and it almost eliminates accidental interruptions."}'::jsonb, 2),
  ('a50e573e-2177-54fd-8452-d3065e651a3f', '1b68b92c-164b-520c-93ad-b4fcc52e50eb', 'text', '{"text":"Using a name earns attention at the exact moments you need it: when you start, when you present the offer, and when you close. Use the honorific until they tell you otherwise."}'::jsonb, 0),
  ('0be32308-4696-523a-ba29-f8e1e0b9a7c3', '1b68b92c-164b-520c-93ad-b4fcc52e50eb', 'script', '{"label":"Placement that works","language":"mixed","lines":["Opening - \"Good afternoon, Ms. Rivera, this is Jason from KCO.\"","Presenting - \"Ms. Rivera, based on what you said about your store, the starter pack fits best.\"","Closing - \"Ms. Rivera, shall I reserve one for delivery this Friday?\""]}'::jsonb, 1),
  ('02843983-9019-5227-851f-9168e7087174', '1b68b92c-164b-520c-93ad-b4fcc52e50eb', 'dosdonts', '{"dos":["Confirm the spelling and pronunciation once","Default to Ms. / Mr. / Sir / Ma’am"],"donts":["Use the name in every second sentence - it sounds like a script","Guess a nickname you were never given","Switch to first names before they do"]}'::jsonb, 2),
  ('b3bb408a-b8ea-5afa-bce8-a0eb22b030b9', 'a7d0b483-d0bf-593b-9d7a-57edaa5929a8', 'text', '{"text":"You cannot recommend a package until you know what the customer is selling into. Four questions is usually enough to pick the right pack and the right talking points."}'::jsonb, 0),
  ('d887a94f-5c81-564c-925b-a5b5216927af', 'a7d0b483-d0bf-593b-9d7a-57edaa5929a8', 'numbered', '{"items":["Are you selling online, in a physical store, or both?","Have you resold snacks or food products before?","Roughly how many customers do you reach in a week?","What made you interested in Kangkong Chips specifically?"]}'::jsonb, 1),
  ('4623dce5-62a1-50bc-91a4-f7f5c5089812', 'a7d0b483-d0bf-593b-9d7a-57edaa5929a8', 'comparison', '{"caption":"Open questions gather; closed questions confirm","columns":["Open - use in discovery","Closed - use to confirm"],"rows":[["What are you selling right now?","So you are selling mainly online, correct?"],["How do your customers usually order?","Would delivery on Friday work?"],["What worried you about other suppliers?","Shall I reserve the starter pack for you?"]]}'::jsonb, 2),
  ('02f2279a-8244-5ea0-9163-8b2de1f0eff9', '8d816fd6-bcdf-5e3c-9720-1d09906709f3', 'text', '{"text":"Scripts exist so you never lose the thread - not so you can read them aloud. Memorise the eight steps of the call, keep the exact wording for prices and policies, and improvise everything in between."}'::jsonb, 0),
  ('b0867961-b2be-587a-8154-34f4ddca6655', '8d816fd6-bcdf-5e3c-9720-1d09906709f3', 'comparison', '{"caption":"Same information, different delivery","columns":["Read aloud","Spoken naturally"],"rows":[["We are pleased to offer our premium Kangkong Chips product line at competitive reseller pricing.","So the starter pack gives you 50 packs, and most resellers start there to test their market."],["Kindly be informed that the minimum order quantity is fifty units.","The smallest order we do is 50 packs - that keeps your cost per pack low."]]}'::jsonb, 1),
  ('0bf71970-d835-5d00-b6c8-f3812cff65eb', '8d816fd6-bcdf-5e3c-9720-1d09906709f3', 'callout', '{"variant":"warning","title":"Keep these word-for-word","text":"Prices, minimum order quantities, delivery cut-offs, and anything about returns. Improvising on these creates promises the company has to keep."}'::jsonb, 2),
  ('dd599979-0bc0-542a-b892-17a3c41894f2', '87970a56-2ba3-5da6-a652-bee329f5d62d', 'text', '{"text":"\"I am busy\" is rarely a refusal - it is a request for a different time. Acknowledge it, ask for a slot, and get off the phone quickly. Respecting their time is itself a sales argument."}'::jsonb, 0),
  ('aaf29c01-e656-5013-994b-650d92c9e2a5', '87970a56-2ba3-5da6-a652-bee329f5d62d', 'script', '{"label":"The 20-second exit","language":"mixed","lines":["Customer: Sorry, busy ako ngayon.","You: Naku, understood po - I will keep this short.","You: Would it be better if I call you back later today, or tomorrow morning?","Customer: Tomorrow morning na lang.","You: Perfect. I will call at 9 AM tomorrow. Thank you, Ms. Rivera!"]}'::jsonb, 1),
  ('3850753a-66e1-5fdb-8091-4d09a9a71c98', '87970a56-2ba3-5da6-a652-bee329f5d62d', 'dosdonts', '{"dos":["Offer two specific time options, not \"anytime\"","Confirm the callback time out loud","Log the callback immediately"],"donts":["Say \"this will only take a second\" and then talk for five minutes","Ask for the sale anyway","Call back at a time you did not agree on"]}'::jsonb, 2),
  ('6ab2731d-8357-5b81-9021-f8c1036a6abf', '63dcd26c-eac6-5536-9526-d97e8dcc3178', 'text', '{"text":"An angry customer is usually angry about a delivery, a damaged box, or a promise someone else made. None of that is personal. Your job is to absorb the first wave without arguing, then convert the call into a concrete next action."}'::jsonb, 0),
  ('abec922a-cf39-5014-8041-fd2052ac494f', '63dcd26c-eac6-5536-9526-d97e8dcc3178', 'numbered', '{"items":["Let them finish completely - do not defend anything yet.","Acknowledge the specific problem in their words.","Apologise for the experience, not for a fault you have not verified.","State exactly what you will do and by when.","Confirm the callback and follow through."]}'::jsonb, 1),
  ('4708d55d-0f7e-5ea9-b0b8-430b7614e448', '63dcd26c-eac6-5536-9526-d97e8dcc3178', 'script', '{"label":"Damaged delivery","language":"mixed","lines":["I hear you, Ms. Rivera, and I am sorry this happened with your delivery.","Let me make sure I have it right: six packs out of fifty arrived crushed. Correct po?","Here is what I will do - I will file this with our logistics team today and send you the reference number.","I will call you back before 5 PM with the replacement schedule."]}'::jsonb, 2),
  ('49f98b10-55f3-555d-971a-2fd217184e2e', '63dcd26c-eac6-5536-9526-d97e8dcc3178', 'callout', '{"variant":"danger","title":"Never do this on an angry call","text":"Do not raise your voice, do not blame the courier or a colleague by name, and do not promise a refund, discount, or replacement you are not authorised to approve. Escalate instead."}'::jsonb, 3),
  ('3254a97e-7b91-50f2-aa28-3a64b9381549', 'b56d3071-9cbd-5217-b56e-485435eda2f5', 'text', '{"text":"Guessing about shelf life, ingredients, permits, or pricing creates a problem the whole company inherits. Saying you will verify costs you nothing - customers read it as competence, not weakness."}'::jsonb, 0),
  ('60621eae-cbb4-5a76-85a9-cb77b8441af1', 'b56d3071-9cbd-5217-b56e-485435eda2f5', 'wording', '{"pairs":[{"avoid":"Hindi ko alam.","use":"Let me verify that for you and come right back."},{"avoid":"I think around 6 months siguro.","use":"I want to give you the exact shelf life - let me confirm and message you today."},{"avoid":"Basta approved yan.","use":"Let me send you the exact documentation so you have it in writing."}]}'::jsonb, 1),
  ('843bda15-0e3e-5c36-9a16-1246c6c68b65', 'b56d3071-9cbd-5217-b56e-485435eda2f5', 'checklist', '{"items":[{"text":"Say you will verify, with a time commitment"},{"text":"Write the question down before you hang up"},{"text":"Ask your team lead, not a fellow agent guessing"},{"text":"Follow up even if the answer is no"}]}'::jsonb, 2),
  ('6e62f599-c277-5927-b31f-7a4475e8ee79', '006454d2-9d4c-5c1f-852a-79b8a4590b63', 'script', '{"label":"Placing a customer on hold","language":"mixed","lines":["May I ask you to hold for a moment while I check your order details?","It should take about one minute. Is that okay po?","[on return] Thank you for waiting, Ms. Rivera."]}'::jsonb, 0),
  ('c354dcda-517e-5cf7-8cc5-54f0588a15dc', '006454d2-9d4c-5c1f-852a-79b8a4590b63', 'dosdonts', '{"dos":["Always ask permission first","Say why you need the hold","Give a time estimate and beat it","Check back in if it runs long","Thank them when you return"],"donts":["Say \"wait lang\" and drop the line","Leave anyone on hold past two minutes without checking in","Forget who is on the other line"]}'::jsonb, 1),
  ('dce8229d-9f2a-5d37-ac8d-7980c46457b3', '1b1c848c-7536-5c76-b14c-4d60757b605e', 'text', '{"text":"A dropped call is not the customer’s problem to solve. Call back within one minute, apologise briefly, and pick up exactly where you left off - do not restart the whole pitch."}'::jsonb, 0),
  ('6fa73119-b45d-5cf7-b4ce-2bdb90bddbe4', '1b1c848c-7536-5c76-b14c-4d60757b605e', 'script', '{"label":"Reconnecting","language":"mixed","lines":["Hi Ms. Rivera, sorry po - nadiscon ang linya.","This is Jason from KCO again. We were at the delivery schedule.","You mentioned Friday works for you - shall I confirm that?"]}'::jsonb, 1),
  ('b242e681-6cb5-5b3b-afac-d239e954826c', '1b1c848c-7536-5c76-b14c-4d60757b605e', 'bullets', '{"items":["If they do not pick up, send one short SMS or chat message with your name and callback time.","Log the drop so the next agent sees the history.","Two failed attempts - move to chat rather than calling a third time."]}'::jsonb, 2),
  ('5b9eb996-8c0d-5815-bbdf-1abfe060e97e', '2eec8ea3-c0d7-5102-ac43-4c1c22961c09', 'text', '{"text":"Headset microphones sit close to your mouth and pick up chewing, straws, and wrappers with uncomfortable clarity. Eating on a call tells the customer they are not worth full attention - and on a food product call it is worse."}'::jsonb, 0),
  ('3e04370e-ff9b-5197-b20a-5cd00f584c86', '2eec8ea3-c0d7-5102-ac43-4c1c22961c09', 'dosdonts', '{"dos":["Finish food before your shift block","Keep water within reach and sip between calls","Mute if you need to clear your throat"],"donts":["Chew gum","Eat during hold","Take a call with food in your mouth"]}'::jsonb, 1),
  ('2b2a0bfc-e9d3-5a63-8d5d-4126108a21b9', 'f0030f0a-212f-5093-9a6b-094de87665c7', 'text', '{"text":"Casual phrasing is not rude in daily conversation, but on a sales call it makes the company sound informal. These swaps are the highest-frequency ones on the phone."}'::jsonb, 0),
  ('4b97388c-d167-51cf-8574-520281b0faa8', 'f0030f0a-212f-5093-9a6b-094de87665c7', 'wording', '{"pairs":[{"avoid":"Wait lang.","use":"May I ask you to hold for a moment?"},{"avoid":"Hindi ko alam.","use":"Let me verify that for you."},{"avoid":"Di ko gets.","use":"May I clarify what you mean?"},{"avoid":"Ha? Ano po?","use":"I am sorry, could you repeat that please?"},{"avoid":"Wala kami niyan.","use":"That variant is not available right now - may I suggest an alternative?"},{"avoid":"Sige, bye.","use":"Thank you for your time, Ms. Rivera. Have a good day!"}]}'::jsonb, 1),
  ('a05e85f5-83d9-5638-8638-fc1c395b106e', 'f0030f0a-212f-5093-9a6b-094de87665c7', 'quiz', '{"question":"A customer asks for the exact shelf life and you are not sure. What is the correct response?","options":["Give your best estimate so the call keeps moving.","Tell them you will verify and commit to a time to come back with the exact figure.","Say it depends and change the subject to price.","Transfer the call without explanation."],"answerIndex":1,"explanation":"Never invent product facts. Committing to verify - with a specific callback time - protects the customer and the company, and customers consistently read it as professionalism."}'::jsonb, 2)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
