-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 11 OF 23: Module 10: Legacy Call Scripts (2025)
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Module 10: Legacy Call Scripts (2025)
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, teams, tags, needs_claim_review, published_at) values
  ('04ee5c06-93e5-5e55-9d68-645adb3ab3ca', 'legacy-call-scripts-2025', 'Legacy Call Scripts (2025)', 'Superseded by Sales Call Structure. Kept for reference only - do not use on live calls.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 10, 'archived', 'foundation', 18, array['admin']::public.user_role[], array['Training']::text[], array['legacy', 'archived']::text[], false, null)
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  teams = excluded.teams,
  tags = excluded.tags,
  needs_claim_review = excluded.needs_claim_review,
  published_at = excluded.published_at
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('5a64468e-e032-5435-8c93-bab958ca89c5', '04ee5c06-93e5-5e55-9d68-645adb3ab3ca', 'Archived', 'Replaced by the eight-step structure in Module 2.', 0, 'published')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('04e7fb76-060c-5208-a209-cf2995c08e73', '5a64468e-e032-5435-8c93-bab958ca89c5', 'callout', '{"variant":"danger","title":"Do not use on live calls","text":"These scripts predate the eight-step structure and quote pricing that is no longer accurate. They remain visible to Admin only, for historical reference."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
