-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 12 OF 23: Modules awaiting source content - created as drafts, never invented
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Modules awaiting source content - created as drafts, never invented
-- ---------------------------------------------------------------------------

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('81450e04-3754-500c-ae99-de1a67cd0166', 'office-rules-and-sales-reporting', 'Office Rules & Sales Reporting Guidelines', 'Attendance, punctuality, working hours, workstation discipline, and the daily sales reporting requirement.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 20, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('4c398a32-8dbe-5c4c-9e24-d6182afc6a49', '81450e04-3754-500c-ae99-de1a67cd0166', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('a191657f-b176-5b53-a520-f505dd13dcae', '4c398a32-8dbe-5c4c-9e24-d6182afc6a49', 'callout', '{"variant":"warning","title":"Admin content required","text":"This module needs the Office Rules & Sales Reporting Guidelines document. Company policies - working hours, attendance rules, reporting deadlines - must be entered exactly as management issued them, so nothing has been drafted here."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('5fa588b1-c71a-5437-be02-105f4268eec7', 'customer-communication-rules', 'Customer Communication & Chat Rules', 'Response-time standards, follow-up rules, escalation, and the boundaries of what an agent may commit to.', '1e1fb7c1-f3f4-583c-9a84-0efc7eb68854', 21, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('3be77908-d0f4-509f-9f37-c445422c03a2', '5fa588b1-c71a-5437-be02-105f4268eec7', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('fdd307ee-e661-55ea-95aa-a13012dfd29f', '3be77908-d0f4-509f-9f37-c445422c03a2', 'callout', '{"variant":"warning","title":"Admin content required","text":"Chat Etiquette and The KCO Chat Formula already cover technique. This module needs the company communication policy document for the rules themselves - response windows, follow-up cadence, and what requires a supervisor."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('cec917b8-755a-5256-a965-4d4308540087', 'product-mastery', 'Product Mastery', 'Flavours, sizes, shelf life, certifications, and the brand story behind Kangkong Chips Original.', '368390d7-eb90-5113-b515-2b75504c63e6', 22, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('e6075e5c-653a-5824-b353-8ac87d76aa09', 'cec917b8-755a-5256-a965-4d4308540087', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('52ea0090-6b55-5872-80ef-3c71b5b220a4', 'e6075e5c-653a-5824-b353-8ac87d76aa09', 'callout', '{"variant":"warning","title":"Admin content required","text":"Requires verified product data: the flavour range, pack sizes, shelf life, and any certifications. Product facts must come from management - an agent quoting an invented specification to a customer is a real problem, so this module stays empty until the data is supplied."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('8e8d0571-43a9-5592-8dfe-c1c14bd454f8', 'qualification-and-needs-analysis', 'Qualification & Needs Analysis', 'Qualifying a lead and uncovering the need before presenting anything.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 23, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('92001529-40f0-5801-827f-8478c67dfcd5', '8e8d0571-43a9-5592-8dfe-c1c14bd454f8', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('5861933b-0d98-5b8e-9f51-11f35ee7ec1b', '92001529-40f0-5801-827f-8478c67dfcd5', 'callout', '{"variant":"warning","title":"Admin content required","text":"Sales Call Structure covers the Discover step and Quick Reference holds the qualification questions. This module needs the dedicated qualification framework document to stand on its own."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('0e609677-8729-56fe-b30b-30a20b39a600', 'closing-skills', 'Closing Skills', 'Closing techniques, trial closes, and asking for the order without pressure.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 24, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('135ab07a-615e-5cdd-ac56-1d0e6a019ba4', '0e609677-8729-56fe-b30b-30a20b39a600', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('a75b2830-1345-5d62-9dc8-c934f99282ca', '135ab07a-615e-5cdd-ac56-1d0e6a019ba4', 'callout', '{"variant":"warning","title":"Admin content required","text":"Closing scripts are available in Quick Reference and inside Sales Call Structure. The full closing-techniques document is needed to build this out as a module."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('fa3f46b6-2e93-515d-99c1-6f82cdde01a4', 'follow-up-management', 'Follow-Up Management', 'Follow-up timing, the seen-zone problem, and keeping a pipeline warm.', 'd034002e-71d8-5eeb-9c9e-de578918d2cc', 25, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('579bb0cf-02f1-5525-95c7-83113ea4a606', 'fa3f46b6-2e93-515d-99c1-6f82cdde01a4', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('a0bdcff0-0918-5a46-b9af-49e69d679b85', '579bb0cf-02f1-5525-95c7-83113ea4a606', 'callout', '{"variant":"warning","title":"Admin content required","text":"Needs the follow-up rules document: how soon, how often, and when to stop. These are operational policies rather than technique, so they must come from management."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

insert into public.modules (id, slug, title, description, category_id, module_number, status, difficulty, duration_minutes, audience, tags) values
  ('ca760a97-7424-5338-8480-4b697b83bcaf', 'sales-performance-and-scorecard', 'Sales Performance & Scorecard', 'The Weekly Sales Scorecard, the metrics it tracks, and how performance is reviewed.', '368390d7-eb90-5113-b515-2b75504c63e6', 26, 'draft', 'foundation', 0, array['sales']::public.user_role[], array['awaiting-content']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  module_number = excluded.module_number,
  status = excluded.status,
  difficulty = excluded.difficulty,
  duration_minutes = excluded.duration_minutes,
  audience = excluded.audience,
  tags = excluded.tags
;

insert into public.lessons (id, module_id, title, summary, sort_order, status) values
  ('ec5eec17-5228-54e6-ab1d-dab5f4ae4aad', 'ca760a97-7424-5338-8480-4b697b83bcaf', 'Admin content required', 'This module is part of the training outline but its source document has not been supplied.', 0, 'draft')
on conflict (id) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order,
  status = excluded.status
;

insert into public.content_blocks (id, lesson_id, type, data, sort_order) values
  ('356da53b-1188-533b-9832-777b3b2d9305', 'ec5eec17-5228-54e6-ab1d-dab5f4ae4aad', 'callout', '{"variant":"warning","title":"Admin content required","text":"Needs the Weekly Sales Scorecard definition and its metric list. The brief is explicit that performance is not judged on chat volume alone, so the real scorecard must be supplied rather than approximated."}'::jsonb, 0)
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  type = excluded.type,
  data = excluded.data,
  sort_order = excluded.sort_order
;

commit;
