-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 13 OF 23: Learning paths
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Learning paths
-- ---------------------------------------------------------------------------

insert into public.learning_paths (id, slug, title, description, audience, accent, status, published_at) values
  ('5ca7b984-b5dc-5acb-9812-791c6e9a2772', 'new-hire-foundation', 'New Hire Foundation', 'The first week. Everything a new KCO agent needs before taking a live call or chat on their own.', array['sales']::public.user_role[], 'green', 'published', now()),
  ('afa85750-45ef-5736-b3a0-ac2e214953a9', 'chat-support-specialist', 'Chat Support Specialist', 'For agents working the Messenger queue full time - etiquette, the G.A.L.P.H.C.F.R. formula, and written objection handling.', array['sales']::public.user_role[], 'blue', 'published', now()),
  ('31962445-e608-57b2-8b5d-14149b78506c', 'closing-and-objections', 'Closing & Objections', 'For agents who open well but stall at the close. Structure, A.C.A.C., and the twelve objection cards.', array['sales']::public.user_role[], 'amber', 'published', now()),
  ('9c1f27f6-6e54-59bc-96cc-ad6c9ebd464f', 'facilitator-track', 'Facilitator Track', 'For team leads running huddles: how to pick, run, and debrief the eight training activities.', array['admin']::public.user_role[], 'rose', 'published', now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  audience = excluded.audience,
  accent = excluded.accent,
  status = excluded.status,
  published_at = excluded.published_at
;

-- Replace path items wholesale: their identity is position, not content.
delete from public.learning_path_items
 where path_id in ('5ca7b984-b5dc-5acb-9812-791c6e9a2772', 'afa85750-45ef-5736-b3a0-ac2e214953a9', '31962445-e608-57b2-8b5d-14149b78506c', '9c1f27f6-6e54-59bc-96cc-ad6c9ebd464f');

insert into public.learning_path_items (id, path_id, module_id, sort_order, required) values
  ('213ce717-64e4-5840-ba5f-a0d2bed5bd43', '5ca7b984-b5dc-5acb-9812-791c6e9a2772', '2e397237-467e-5050-a02a-677dbd0dab8d', 0, true),
  ('2b28a72c-5fe8-5df2-b084-732effc58476', '5ca7b984-b5dc-5acb-9812-791c6e9a2772', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 1, true),
  ('8076895c-4b03-53ff-ab0b-61f1d2aa268f', '5ca7b984-b5dc-5acb-9812-791c6e9a2772', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 2, true),
  ('47e36c3f-eb9c-5aa4-8384-a7b3cd92179f', '5ca7b984-b5dc-5acb-9812-791c6e9a2772', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 3, true),
  ('f21aad49-333f-5ebc-a99a-27bad6af9919', 'afa85750-45ef-5736-b3a0-ac2e214953a9', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 0, true),
  ('c0229448-b60c-5574-bd46-6ec8f3b12dd1', 'afa85750-45ef-5736-b3a0-ac2e214953a9', 'be0e0b89-149d-53d9-ad67-5021c25f6403', 1, true),
  ('e3003c2b-66d8-507f-8bd8-883d1ccfff9f', 'afa85750-45ef-5736-b3a0-ac2e214953a9', '7ee94025-2414-5db6-a733-cadbdfb4809c', 2, true),
  ('636bb487-d607-5471-8387-bedccb4666ac', 'afa85750-45ef-5736-b3a0-ac2e214953a9', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 3, true),
  ('21121253-7f7d-5c03-bdd5-90f4ff544584', '31962445-e608-57b2-8b5d-14149b78506c', '5efb088e-d8f8-5aad-8a27-bfde6c834c98', 0, true),
  ('951423cc-ecb0-546a-a1b3-428771d12094', '31962445-e608-57b2-8b5d-14149b78506c', '7ee94025-2414-5db6-a733-cadbdfb4809c', 1, true),
  ('8236f167-f504-5c2e-9ba8-a9e408c813ce', '31962445-e608-57b2-8b5d-14149b78506c', '6c61a72d-2149-5ad1-9cfe-73c5acdf132a', 2, true),
  ('7466f56a-c89b-549b-ae6e-724a31789fa0', '9c1f27f6-6e54-59bc-96cc-ad6c9ebd464f', '7925a399-92cf-5df4-8141-a93febf41e7c', 0, true),
  ('54a1c2a9-700b-56e0-88a9-58f52078f641', '9c1f27f6-6e54-59bc-96cc-ad6c9ebd464f', '7ee94025-2414-5db6-a733-cadbdfb4809c', 1, true),
  ('01e8c501-b661-5816-8646-ab24fdc26800', '9c1f27f6-6e54-59bc-96cc-ad6c9ebd464f', '2e397237-467e-5050-a02a-677dbd0dab8d', 2, true)
on conflict (id) do update set
  path_id = excluded.path_id,
  module_id = excluded.module_id,
  sort_order = excluded.sort_order,
  required = excluded.required
;

commit;
