-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 14 OF 23: Assessments, questions and choices
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Assessments, questions and choices
-- ---------------------------------------------------------------------------

insert into public.assessments (id, slug, title, description, module_id, passing_score, time_limit_minutes, attempts_allowed, status, published_at) values
  ('d904d1a1-a8cc-5ab7-b45c-320901bdf401', 'phone-etiquette-check', 'Phone Etiquette Check', 'Six questions on greeting, hold, recovery, and what you may never invent.', '2e397237-467e-5050-a02a-677dbd0dab8d', 80, 10, 3, 'published', now()),
  ('270bc430-0b9b-5995-bc10-307da96f8fd3', 'chat-standards-check', 'Chat Standards Check', 'Response times, tone, confirmations, and the four openers you see every day.', '5fbcccf1-db33-52cc-a92e-dcdc3504fef8', 80, 10, 3, 'published', now()),
  ('7d02cc99-602e-5c80-b104-81f68b3f1eb5', 'objection-handling-certification', 'Objection Handling Certification', 'A.C.A.C. applied under pressure, including the claims you are prohibited from making.', '7ee94025-2414-5db6-a733-cadbdfb4809c', 85, 15, 2, 'published', now()),
  ('7a783bc9-ba3d-5e1f-8bb2-38199a0358a4', 'professional-wording-drill', 'Professional Wording Drill', 'Quick swaps - the casual phrase in, the professional version out.', '1c917f14-e30e-5b9b-9cec-96227a26e9a9', 75, 5, 5, 'published', now())
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  description = excluded.description,
  module_id = excluded.module_id,
  passing_score = excluded.passing_score,
  time_limit_minutes = excluded.time_limit_minutes,
  attempts_allowed = excluded.attempts_allowed,
  status = excluded.status,
  published_at = excluded.published_at
;

insert into public.assessment_questions (id, assessment_id, type, prompt, explanation, points, sort_order) values
  ('5636b0d5-0471-52eb-aa53-4e7c37044830', 'd904d1a1-a8cc-5ab7-b45c-320901bdf401', 'multiple_choice', 'Which opening follows the KCO standard?', 'Time of day, your name, the full company name, and confirmation of who you are speaking with - before anything about the offer.', 1, 0),
  ('fe579c91-cf19-56c6-9531-7e66af902d22', 'd904d1a1-a8cc-5ab7-b45c-320901bdf401', 'multiple_choice', 'A customer needs to be placed on hold. What must happen first?', 'Ask, explain, estimate - then beat the estimate and thank them on return.', 1, 1),
  ('8bd2dbb6-9255-58a9-b84a-9295a10e7acc', 'd904d1a1-a8cc-5ab7-b45c-320901bdf401', 'multiple_choice', 'The call drops mid-conversation. Who calls back, and what do you do?', 'The agent always owns the callback, and resuming - not restarting - respects the customer’s time.', 1, 2),
  ('9c153f4a-a926-5b58-ad4f-d2b91e057d99', 'd904d1a1-a8cc-5ab7-b45c-320901bdf401', 'multiple_choice', 'You do not know the exact shelf life of the product. What do you say?', 'Never invent a product fact. Commit to verifying, attach a time, and follow through.', 1, 3),
  ('0920a9cc-e1e4-5bf3-a462-ec7d2348f89f', 'd904d1a1-a8cc-5ab7-b45c-320901bdf401', 'multiple_choice', 'A customer says "Sorry, busy ako ngayon." What is the correct response?', 'Two specific options get a real commitment; "anytime" gets nothing. Then log the callback and honour it.', 1, 4),
  ('0b3dedd8-9170-586c-b648-25fd2b1ee5c6', 'd904d1a1-a8cc-5ab7-b45c-320901bdf401', 'multiple_choice', 'An angry customer is describing a delivery problem. What do you do first?', 'Absorb the first wave without interrupting or defending. Only then acknowledge, commit to an action, and give a deadline.', 1, 5),
  ('ea86ef92-eda7-5488-9f1a-a86d7e838988', '270bc430-0b9b-5995-bc10-307da96f8fd3', 'multiple_choice', 'What is the target first-reply time for a new chat?', 'Two minutes for a first reply; one minute inside an active conversation.', 1, 0),
  ('9caa2098-4661-58b5-a217-f41b6b09a11f', '270bc430-0b9b-5995-bc10-307da96f8fd3', 'multiple_choice', 'A customer messages only "Send details po." What is the best reply?', 'One question turns a cold request into a conversation and lets you send something relevant.', 1, 1),
  ('b05527fb-cd89-5b27-887a-573be5d4ecef', '270bc430-0b9b-5995-bc10-307da96f8fd3', 'multiple_choice', 'Which message meets the KCO chat standard?', 'Answer, add a useful detail, hand back a question - with proper capitalisation and no text-speak.', 1, 2),
  ('bcd4a130-5899-5a97-a27e-274d1a57219a', '270bc430-0b9b-5995-bc10-307da96f8fd3', 'multiple_choice', 'When should you avoid emoji entirely?', 'Emoji soften friendly messages and undermine serious ones. Drop them when a customer is upset or money is disputed.', 1, 3),
  ('f830c054-dbf7-5f4a-bb08-5d1580f38eba', '270bc430-0b9b-5995-bc10-307da96f8fd3', 'multiple_choice', 'How many follow-ups may you send to an unresponsive lead?', 'Two maximum, and each must add something useful. After that, log the lead as cold and stop.', 1, 4),
  ('2b25c2d9-f7fc-5a31-9fcb-89e829e7d7d9', '270bc430-0b9b-5995-bc10-307da96f8fd3', 'multiple_choice', 'Which item is NOT required in an order confirmation message?', 'Supplier identity is confidential company information and never appears in a customer-facing message.', 1, 5),
  ('1b8e7954-91b7-5e0c-a7c7-ed2c72decb18', '7d02cc99-602e-5c80-b104-81f68b3f1eb5', 'multiple_choice', 'What does the second letter of A.C.A.C. stand for, and why does it matter?', 'Clarify is the most-skipped step. Without it you answer the generic objection instead of theirs.', 2, 0),
  ('ae43a3c9-1eb3-5cb7-a461-c9a6c59bdbd0', '7d02cc99-602e-5c80-b104-81f68b3f1eb5', 'multiple_choice', 'A customer asks "Magkano ang kita ko?" What may you say?', 'Guaranteed earnings are prohibited. Any computation must be built from the customer’s own assumptions and labelled as an example.', 2, 1),
  ('f3fe5ebd-282d-5e75-8c82-375647033605', '7d02cc99-602e-5c80-b104-81f68b3f1eb5', 'multiple_choice', 'A customer says "May supplier na ako." What is the correct approach?', 'Never ask them to break an agreement, never disparage a competitor, and never undercut with a price you cannot honour.', 2, 2),
  ('091e034c-bc93-5bb3-96f6-019d9e33470a', '7d02cc99-602e-5c80-b104-81f68b3f1eb5', 'multiple_choice', 'Which is an objection rather than a rejection?', 'An objection names a specific obstacle - the customer is still in the conversation. A rejection ends it, and should be accepted gracefully.', 1, 3),
  ('109d2e6c-212c-5369-9067-6fe3ce8d63c1', '7d02cc99-602e-5c80-b104-81f68b3f1eb5', 'multiple_choice', 'A customer says "Mahal naman." Your first move is to:', 'Acknowledge, then clarify. Discounting first teaches customers to wait for one, and arguing tells them their judgement is wrong.', 2, 4),
  ('9d19e5d1-32a8-5e21-81f9-0c44203f13cb', '7a783bc9-ba3d-5e1f-8bb2-38199a0358a4', 'multiple_choice', 'Replace: "Wait lang."', 'Hold is always requested, never instructed.', 1, 0),
  ('94141e05-4306-56ee-93a6-a722b2168394', '7a783bc9-ba3d-5e1f-8bb2-38199a0358a4', 'multiple_choice', 'Replace: "Hindi pwede yan."', 'Every no needs an alternative attached, or the customer has nothing to say yes to.', 1, 1),
  ('a73e7ef7-16af-5dce-b17e-09437c002d85', '7a783bc9-ba3d-5e1f-8bb2-38199a0358a4', 'multiple_choice', 'Replace: "Fault yun ng courier."', 'Never blame a third party by name. Own the next action instead.', 1, 2),
  ('86204656-3b6a-5681-a30a-7aa37b727e04', '7a783bc9-ba3d-5e1f-8bb2-38199a0358a4', 'multiple_choice', 'Replace: "Sure na po yan kikita kayo."', 'Guaranteed earnings are prohibited on every channel.', 2, 3)
on conflict (id) do update set
  assessment_id = excluded.assessment_id,
  type = excluded.type,
  prompt = excluded.prompt,
  explanation = excluded.explanation,
  points = excluded.points,
  sort_order = excluded.sort_order
;

insert into public.assessment_choices (id, question_id, text, is_correct, sort_order) values
  ('ea2e246e-eb6d-5bd3-94cd-5affa87e55cc', '5636b0d5-0471-52eb-aa53-4e7c37044830', 'Hello? Sino po ito?', false, 0),
  ('ae50f3b9-aa51-5f90-b036-bc7f62989717', '5636b0d5-0471-52eb-aa53-4e7c37044830', 'Good morning! This is Jason from KCO Kangkong Chips. Am I speaking with Ms. Rivera?', true, 1),
  ('132a040a-f514-57b4-96ff-c0c53430e5cb', '5636b0d5-0471-52eb-aa53-4e7c37044830', 'Hi, calling about the chips inquiry.', false, 2),
  ('105c0e2f-4999-59e4-8c1d-856ea08b336a', '5636b0d5-0471-52eb-aa53-4e7c37044830', 'Good morning, KCO here, we have a promo today.', false, 3),
  ('fbd8b51c-9975-5ea9-945d-6c7381af2b1b', 'fe579c91-cf19-56c6-9531-7e66af902d22', 'Tell them "wait lang po" and mute.', false, 0),
  ('07852693-72b2-5ad6-9bc2-71a4d4786e71', 'fe579c91-cf19-56c6-9531-7e66af902d22', 'Ask permission, say why, and give a time estimate.', true, 1),
  ('c2af529d-d07d-50fa-918f-7af27a3832dc', 'fe579c91-cf19-56c6-9531-7e66af902d22', 'Put them on hold and explain when you return.', false, 2),
  ('02c9fbdf-33ca-5134-93b0-1e64f832dc2a', 'fe579c91-cf19-56c6-9531-7e66af902d22', 'Transfer them to a colleague instead.', false, 3),
  ('ac046d18-0f47-5537-825c-2243177c4493', '8bd2dbb6-9255-58a9-b84a-9295a10e7acc', 'Wait for the customer to call back.', false, 0),
  ('802c5262-2dc5-5800-ae14-a9ba4f2a963d', '8bd2dbb6-9255-58a9-b84a-9295a10e7acc', 'Call back within a minute, apologise briefly, and resume where you stopped.', true, 1),
  ('45046420-ee47-5f53-82c9-4425e509c1f1', '8bd2dbb6-9255-58a9-b84a-9295a10e7acc', 'Call back and restart the pitch from the greeting.', false, 2),
  ('d0ba96cb-d61b-5672-a9d2-59461bb89d72', '8bd2dbb6-9255-58a9-b84a-9295a10e7acc', 'Send a chat message and wait.', false, 3),
  ('3c954da6-fc34-5bc2-9964-2c422e7e4b6d', '9c153f4a-a926-5b58-ad4f-d2b91e057d99', '"Mga 6 months po siguro."', false, 0),
  ('99e2dc70-dd83-5e94-bcee-c82be2cdb9ab', '9c153f4a-a926-5b58-ad4f-d2b91e057d99', '"Hindi ko po alam."', false, 1),
  ('6ecf1a05-f1ad-5dcc-8ff1-254fc63f6a08', '9c153f4a-a926-5b58-ad4f-d2b91e057d99', '"Let me verify that for you and come back to you within the hour."', true, 2),
  ('fe26cd86-25c6-5cab-8b4b-49e33c05e065', '9c153f4a-a926-5b58-ad4f-d2b91e057d99', '"Nasa packaging po yun."', false, 3),
  ('cc30c0f1-d6b9-52ea-8816-fbbec9dc8467', '0920a9cc-e1e4-5bf3-a462-ec7d2348f89f', 'Explain that it will only take a second and continue.', false, 0),
  ('d55be0cc-93d3-53f1-b8fb-4a73ce4964f4', '0920a9cc-e1e4-5bf3-a462-ec7d2348f89f', 'Acknowledge, offer two specific callback times, confirm one, and end the call.', true, 1),
  ('423a8e66-4967-5adf-8329-7b0b7ec1df57', '0920a9cc-e1e4-5bf3-a462-ec7d2348f89f', 'Ask for the sale quickly before they hang up.', false, 2),
  ('f3f00245-c283-5c4e-a176-96a2d77e77b6', '0920a9cc-e1e4-5bf3-a462-ec7d2348f89f', 'Say you will call back anytime and hang up.', false, 3),
  ('38855ec4-d441-5c39-b29d-a826865c90fb', '0b3dedd8-9170-586c-b648-25fd2b1ee5c6', 'Explain the courier’s delivery process.', false, 0),
  ('b0ba7bf0-8fc9-5913-8a67-a730bd7a4a04', '0b3dedd8-9170-586c-b648-25fd2b1ee5c6', 'Let them finish completely without defending anything.', true, 1),
  ('d838d5f0-02a6-509f-be4a-03cd693699f1', '0b3dedd8-9170-586c-b648-25fd2b1ee5c6', 'Offer a replacement immediately.', false, 2),
  ('58528f29-2a89-5cf1-becd-cc3a53eddfc0', '0b3dedd8-9170-586c-b648-25fd2b1ee5c6', 'Transfer them to a supervisor.', false, 3),
  ('c6a7b95f-fba2-5e69-a7a2-4425b76aff7a', 'ea86ef92-eda7-5488-9f1a-a86d7e838988', 'Within 30 seconds', false, 0),
  ('02467f07-e32c-5094-a4b4-70c26cdbe647', 'ea86ef92-eda7-5488-9f1a-a86d7e838988', 'Within 2 minutes', true, 1),
  ('a6939e68-74eb-5013-8d93-bbc00fd1824b', 'ea86ef92-eda7-5488-9f1a-a86d7e838988', 'Within 15 minutes', false, 2),
  ('291e68c8-d920-5dfe-aae1-8de32e4dcd12', 'ea86ef92-eda7-5488-9f1a-a86d7e838988', 'Same day', false, 3),
  ('d04611ef-ff78-505e-b65a-a046718f1ac1', '9caa2098-4661-58b5-a217-f41b6b09a11f', 'Send the full price list and every flavour.', false, 0),
  ('3c00d3f5-c10e-5c6d-80bd-10e33d35d3ce', '9caa2098-4661-58b5-a217-f41b6b09a11f', 'Ask one qualifying question, then send the package that matches.', true, 1),
  ('e226033b-05fc-53db-b8d8-4c75a4a3bd99', '9caa2098-4661-58b5-a217-f41b6b09a11f', 'Reply "Sure po" and wait.', false, 2),
  ('6550e768-cd73-5114-946c-bf419fe06f03', '9caa2098-4661-58b5-a217-f41b6b09a11f', 'Send a link to the page.', false, 3),
  ('b89b5f49-11b2-5ebc-8693-fbee165a3514', 'b05527fb-cd89-5b27-887a-573be5d4ecef', 'wla po eh', false, 0),
  ('bd86701f-b351-55ae-b35e-18bfa006900d', 'b05527fb-cd89-5b27-887a-573be5d4ecef', 'Wala pa po sa ngayon, but restock is next week. Gusto niyo po bang i-reserve ko?', true, 1),
  ('29eff694-e95f-535d-ac0f-0b4f70a3893f', 'b05527fb-cd89-5b27-887a-573be5d4ecef', 'WALA PO STOCK', false, 2),
  ('f6e3c203-e0c9-54a4-a6ce-22293f439038', 'b05527fb-cd89-5b27-887a-573be5d4ecef', 'no', false, 3),
  ('785a9dfc-5582-55ed-9c6d-c3c33b29f3cf', 'bcd4a130-5899-5a97-a27e-274d1a57219a', 'In greetings', false, 0),
  ('024d4146-6870-5e7a-ae75-8b2a7ad2a207', 'bcd4a130-5899-5a97-a27e-274d1a57219a', 'When confirming an order', false, 1),
  ('0f48e525-cd96-57c7-927e-6804f0e3841b', 'bcd4a130-5899-5a97-a27e-274d1a57219a', 'In complaint, refund, or bad-news threads', true, 2),
  ('a6837e6e-063b-5713-8758-74a3d66865f2', 'bcd4a130-5899-5a97-a27e-274d1a57219a', 'Never - always use emoji', false, 3),
  ('506de457-7321-5270-af26-a7d6927a2713', 'f830c054-dbf7-5f4a-bb08-5d1580f38eba', 'As many as needed', false, 0),
  ('8ee39ee4-e95c-573d-882e-0086fefb790a', 'f830c054-dbf7-5f4a-bb08-5d1580f38eba', 'One', false, 1),
  ('873e13ea-3914-56ff-b475-432a87fc16a8', 'f830c054-dbf7-5f4a-bb08-5d1580f38eba', 'Two, each adding value', true, 2),
  ('1267365d-16c7-5c4c-8a57-0d1f43ae5c7d', 'f830c054-dbf7-5f4a-bb08-5d1580f38eba', 'Daily until they reply', false, 3),
  ('c0c096ae-a58e-5762-aecf-305065b80b67', '2b25c2d9-f7fc-5a31-9fcb-89e829e7d7d9', 'Delivery date and payment method', false, 0),
  ('979b3742-8012-588b-a178-2f705197b4a8', '2b25c2d9-f7fc-5a31-9fcb-89e829e7d7d9', 'Quantity, flavour, and total', false, 1),
  ('0fbcee73-f5d3-5c51-8e11-b619e5ab8fa9', '2b25c2d9-f7fc-5a31-9fcb-89e829e7d7d9', 'The name of the supplier who produced the batch', true, 2),
  ('b014b009-2fd9-566d-ac10-c234c71fb0f4', '2b25c2d9-f7fc-5a31-9fcb-89e829e7d7d9', 'Complete delivery address and contact number', false, 3),
  ('06a3f837-9423-55c2-b45c-5622dd3c79f9', '1b8e7954-91b7-5e0c-a7c7-ed2c72decb18', 'Close - because you should always ask for the sale early.', false, 0),
  ('84ec7c11-942c-5f79-a9b7-a0e99bccfd1c', '1b8e7954-91b7-5e0c-a7c7-ed2c72decb18', 'Clarify - because "mahal" against a budget and "mahal" against a competitor need different answers.', true, 1),
  ('9adf9933-3311-53cc-a04a-6a1b13c673de', '1b8e7954-91b7-5e0c-a7c7-ed2c72decb18', 'Confirm - because you need the order details in writing.', false, 2),
  ('0a251040-5546-52ae-a9d4-ac2baaca1aed', '1b8e7954-91b7-5e0c-a7c7-ed2c72decb18', 'Convince - because the customer needs persuading.', false, 3),
  ('ae45683a-3644-51e8-98e8-5b11e0ea9dac', 'ae43a3c9-1eb3-5cb7-a461-c9a6c59bdbd0', 'Quote the average monthly earnings of your top resellers.', false, 0),
  ('cb7173f8-4685-5174-837b-e114508fee58', 'ae43a3c9-1eb3-5cb7-a461-c9a6c59bdbd0', 'Promise they will recover their capital within a month.', false, 1),
  ('fcb2185c-7f24-5a4c-81d2-efe670f95061', 'ae43a3c9-1eb3-5cb7-a461-c9a6c59bdbd0', 'Explain that margin depends on their selling price and offer to compute an example from their own numbers.', true, 2),
  ('70bda899-599e-5ffd-9b30-7687cad079bc', 'ae43a3c9-1eb3-5cb7-a461-c9a6c59bdbd0', 'Say earnings are guaranteed by the company.', false, 3),
  ('dcd4145b-83b3-51f0-b49e-a3098ea3b210', 'f3fe5ebd-282d-5e75-8c82-375647033605', 'Ask who the supplier is so you can compare.', false, 0),
  ('04ab6da3-0454-563b-a6f8-3668ce22108e', 'f3fe5ebd-282d-5e75-8c82-375647033605', 'Offer a price below theirs immediately.', false, 1),
  ('4acc89f0-b29e-5e3e-80fe-ab427f8671fa', 'f3fe5ebd-282d-5e75-8c82-375647033605', 'Acknowledge it, ask how consistent their supply is, and position KCO as a backup with no exclusivity requirement.', true, 2),
  ('41b66e6c-d104-5176-8a7c-e5c2bbaf361b', 'f3fe5ebd-282d-5e75-8c82-375647033605', 'Explain why their supplier is unreliable.', false, 3),
  ('17245395-3a77-59ef-a8b8-b9d4bbcec768', '091e034c-bc93-5bb3-96f6-019d9e33470a', '"Please do not contact me again."', false, 0),
  ('015cb673-372c-555e-8668-15c6250476c3', '091e034c-bc93-5bb3-96f6-019d9e33470a', '"Wrong number po."', false, 1),
  ('ab23e792-a8f2-52eb-88db-948eed2c15ac', '091e034c-bc93-5bb3-96f6-019d9e33470a', '"Baka hindi ko mabenta."', true, 2),
  ('0744afe0-2bde-5763-99a2-b7e9fd580dbe', '091e034c-bc93-5bb3-96f6-019d9e33470a', '"Hindi po ako interesado, salamat."', false, 3),
  ('6aab3d84-4b92-5ec8-8588-784929cace71', '109d2e6c-212c-5369-9067-6fe3ce8d63c1', 'Offer a discount.', false, 0),
  ('cf7eee89-b605-5a45-9de4-e8f2cfaeae66', '109d2e6c-212c-5369-9067-6fe3ce8d63c1', 'Explain that the price is actually reasonable.', false, 1),
  ('214d3cec-f28a-5d1e-aab2-b144c394efd6', '109d2e6c-212c-5369-9067-6fe3ce8d63c1', 'Acknowledge the concern, then ask whether it is expensive against their budget or against another supplier.', true, 2),
  ('cd18e625-5e8e-5991-b9d7-37d0a2fb0755', '109d2e6c-212c-5369-9067-6fe3ce8d63c1', 'Move to a cheaper product immediately.', false, 3),
  ('319846c5-ce8a-5890-b691-e2fd4cc4ad95', '9d19e5d1-32a8-5e21-81f9-0c44203f13cb', 'Hold on.', false, 0),
  ('b8ce39e5-7d7d-5cc2-9e52-3234f0536bdd', '9d19e5d1-32a8-5e21-81f9-0c44203f13cb', 'May I ask you to hold for a moment?', true, 1),
  ('719620ab-66a9-5511-a447-0ee2e29da429', '9d19e5d1-32a8-5e21-81f9-0c44203f13cb', 'Sandali lang po.', false, 2),
  ('883de8a1-7f21-59d9-9b1b-7d4553956948', '9d19e5d1-32a8-5e21-81f9-0c44203f13cb', 'One sec.', false, 3),
  ('c5a14849-4f75-5000-854d-58f50019ecd9', '94141e05-4306-56ee-93a6-a722b2168394', 'That is not possible.', false, 0),
  ('af8c6624-6a17-5d7a-bdbe-b157c3452263', '94141e05-4306-56ee-93a6-a722b2168394', 'What I can do for you instead is…', true, 1),
  ('1f56e14c-15c4-55a3-abf3-a928050b5284', '94141e05-4306-56ee-93a6-a722b2168394', 'Sorry, no.', false, 2),
  ('f2dfa9c6-ae0f-5e1f-909f-d67ae392f943', '94141e05-4306-56ee-93a6-a722b2168394', 'Bawal po yan.', false, 3),
  ('2f4b49c4-8e50-540b-b7d7-18b9763b0797', 'a73e7ef7-16af-5dce-b17e-09437c002d85', 'The courier made a mistake.', false, 0),
  ('fa88120f-1527-545a-9f11-2d2ad638ea91', 'a73e7ef7-16af-5dce-b17e-09437c002d85', 'I am sorry this happened. I am filing it with our logistics team today.', true, 1),
  ('d4ccb667-3eed-53f4-9807-685611007a44', 'a73e7ef7-16af-5dce-b17e-09437c002d85', 'Hindi po namin kasalanan yan.', false, 2),
  ('21f63dbd-885e-538e-b937-9cc5557d67c0', 'a73e7ef7-16af-5dce-b17e-09437c002d85', 'That is a delivery issue, not ours.', false, 3),
  ('c678fc61-c399-5bfa-8694-88e0e4b7cada', '86204656-3b6a-5681-a30a-7aa37b727e04', 'You will definitely earn from this.', false, 0),
  ('5b696176-c357-5994-8167-eb8e7e804985', '86204656-3b6a-5681-a30a-7aa37b727e04', 'Ang kita po ay depende sa selling price at area niyo - pwede natin i-compute base sa numbers niyo.', true, 1),
  ('043c8697-a83c-510d-92a0-3d4fd00e7917', '86204656-3b6a-5681-a30a-7aa37b727e04', 'Most resellers earn well.', false, 2),
  ('74542fa7-7cb8-531e-9d84-220a2f7406a4', '86204656-3b6a-5681-a30a-7aa37b727e04', 'Guaranteed po ang kita.', false, 3)
on conflict (id) do update set
  question_id = excluded.question_id,
  text = excluded.text,
  is_correct = excluded.is_correct,
  sort_order = excluded.sort_order
;

commit;
