-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 15 OF 23: Training activities
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Training activities
-- ---------------------------------------------------------------------------

insert into public.training_activities (id, slug, title, objective, duration_minutes, participants, difficulty, instructions, facilitator_notes, expected_outcome, materials, tags, status) values
  ('c78553b4-75c7-5cd5-866a-935ec598f5fe', 'dont-say-yes-or-no', 'Don''t Say Yes or No', 'Break the habit of one-word answers and force agents to give complete, useful replies under pressure.', 15, '4-12, in pairs', 'foundation', array['Pair up. One is the customer, one is the agent.', 'The customer asks rapid questions designed to invite yes/no answers - "May stock pa po?", "Pwede COD?", "Mahal ba?"', 'The agent must answer completely without ever using the words yes, no, opo, or hindi.', 'Every complete answer must add one detail and end with a question.', 'Run 90 seconds, then swap roles.', 'Score one point per slip. Lowest score wins the round.']::text[], array['Keep the pace fast - the pressure is the point.', 'Listen for the three-part reply: answer, added detail, question back.', 'Call out good rephrasings out loud so the group hears the pattern.', 'Common failure: agents pause too long searching for words. Tell them a short natural pause beats a wrong word.']::text[], 'Agents stop reflexively answering in one word and start building replies that keep the conversation moving.', '{}', array['chat', 'phone', 'warm-up']::text[], 'published'),
  ('37f3161b-838a-5b3e-80a1-a5076fc4f208', 'sell-it-in-10-seconds', 'Sell It in 10 Seconds', 'Force a sharp, benefit-first pitch by removing every spare second.', 20, '5-15, whole group', 'intermediate', array['Each agent gets 10 seconds to pitch Kangkong Chips to the group.', 'The pitch must include one benefit and one call to action.', 'The facilitator times strictly and cuts off at 10 seconds mid-word.', 'The group votes on the clearest pitch, not the loudest.', 'Second round: same agent, same 10 seconds, but a different audience - a sari-sari store owner, an online seller, a parent.']::text[], array['Cut people off exactly at 10 seconds. The discomfort is the lesson.', 'Watch for feature-dumping - "crunchy, healthy, affordable, three flavours" is a list, not a pitch.', 'The second round is where the learning lands: the same product needs a different angle per audience.']::text[], 'Agents can open with one benefit tied to the listener instead of reciting product features.', '{}', array['phone', 'pitch', 'competitive']::text[], 'published'),
  ('a90811ac-1509-5716-9ef1-ed2cb42b94d2', 'pass-the-sales', 'Pass the Sales', 'Practise picking up a call mid-flow and continuing without restarting the pitch.', 25, '6-12, in a circle', 'intermediate', array['One facilitator plays a single customer for the whole round.', 'Agent 1 starts the call at Step 1 - Greet.', 'On the facilitator’s clap, the next agent continues from exactly where the last one stopped.', 'No restarting, no re-introducing, no repeating information already given.', 'The circle continues until the call reaches Step 8 - Confirm + End.', 'Debrief: where did the thread break, and why?']::text[], array['Clap at awkward moments - mid-objection is the most useful place to hand over.', 'Introduce a detail early (a name, a quantity) and see how many agents remember it.', 'This mirrors a real inherited chat thread; connect it to Module 3, Section 07.']::text[], 'Agents listen actively even when they are not speaking, and can resume a conversation without making the customer repeat themselves.', '{}', array['phone', 'teamwork', 'listening']::text[], 'published'),
  ('574bdd14-8298-5fe3-b758-7aa749eb2ead', 'customer-acting', 'Customer Acting', 'Build composure against difficult customer personalities before meeting one live.', 30, '4-10, in pairs with rotation', 'intermediate', array['Draw a personality card: Angry, Sleepy, Confused, Cheap, Funny, Seen Zone, Super Curious, or "I''m Busy".', 'The customer plays that personality without telling the agent which card they drew.', 'The agent runs a real call and must adapt in the moment.', 'After three minutes, the agent guesses the personality.', 'Debrief: what tell gave it away, and what did the agent change in response?']::text[], array['Cap the Angry customer at three minutes - it gets heavy quickly.', 'Remind actors to play a personality, not an insult; no personal attacks.', 'The strongest agents change pace and question style, not their script.', 'Pair with Practice Scenarios for solo repetition afterwards.']::text[], 'Agents read customer mood quickly and adjust pace, tone, and question style instead of pushing the same pitch harder.', '{}', array['phone', 'chat', 'roleplay', 'objections']::text[], 'published'),
  ('761fe7b8-2d1d-5274-a986-655b8daf0424', 'bad-accent-bad-sales', 'Bad Accent / Bad Sales', 'Show - by exaggeration - exactly which delivery habits lose a customer, so agents can hear them in themselves.', 20, '5-15, whole group', 'foundation', array['Round 1: each agent deliberately performs the worst possible call - mumbling, rushing, interrupting, reading the script flatly.', 'The group notes every specific mistake they hear.', 'Round 2: the same agent runs the same call properly.', 'The group names the single biggest improvement between the two.']::text[], array['This is a comedy exercise with a serious point - let the laughter happen, then get specific in the debrief.', 'Never mock a real accent. The target is delivery habits: pace, clarity, interruption, monotone.', 'Write the group’s list of "bad habits" on the board and keep it visible for the week.']::text[], 'Agents can name their own worst delivery habit and demonstrate the corrected version on demand.', '{}', array['phone', 'delivery', 'warm-up']::text[], 'published'),
  ('93f82e58-8950-505c-9c51-6976d6b2053b', 'two-truths-one-lie-product', 'Two Truths, One Lie - Product Edition', 'Expose gaps in product knowledge and kill the habit of guessing.', 20, '4-12, whole group', 'foundation', array['Each agent states three claims about KCO Kangkong Chips - two true, one invented.', 'The group votes on which is the lie.', 'The agent reveals the answer and cites where the true facts come from.', 'Any claim nobody can source goes on the "verify with Admin" list.']::text[], array['The "verify" list is the real output of this exercise - send it to Admin afterwards.', 'Watch for confident wrong answers about shelf life, ingredients, and permits; these are the dangerous ones.', 'Connect directly to Module 1, Section 10 - never invent product facts.']::text[], 'Agents know which product facts they can state confidently and which they must verify before answering.', '{}', array['product-knowledge', 'accuracy']::text[], 'published'),
  ('3c4be56d-8fbe-568c-8302-36c30fb057aa', 'movie-trailer-sales-pitch', 'Movie Trailer Sales Pitch', 'Practise storytelling and vocal energy in a low-stakes, memorable format.', 20, '5-12, whole group', 'advanced', array['Each agent pitches Kangkong Chips as a movie trailer - "In a world where merienda is boring…"', 'The pitch must still contain one real product benefit and one real call to action.', 'Maximum 45 seconds.', 'The group votes for the most entertaining and the most persuasive - separately.', 'Debrief on the gap between those two winners.']::text[], array['The split vote is the whole point: entertaining is not the same as persuasive.', 'Use this to talk about energy level - trailer energy is too much for a real call, but flat energy is too little.', 'Best used mid-week, when energy dips.']::text[], 'Agents find a higher, more engaged vocal register and understand where the line between energetic and theatrical sits.', '{}', array['phone', 'energy', 'storytelling']::text[], 'published'),
  ('1eae4780-0553-5788-b9fe-b58a711ff8e9', 'dramatic-sales-pitch', 'Dramatic Sales Pitch', 'Stretch emotional range so a normal call feels effortless by comparison.', 25, '4-10, in pairs', 'advanced', array['Draw an emotion card: heartbroken, triumphant, mysterious, panicked, or deeply sincere.', 'Deliver the full 8-step call in that emotional register.', 'The partner scores whether every step still appeared, despite the drama.', 'Final round: deliver the same call in a normal professional register and compare how easy it feels.']::text[], array['The final normal round is the actual exercise - everything before it is calibration.', 'Check that the eight steps survive; drama often eats Discover and Confirm.', 'Good closing activity for a training day.']::text[], 'Agents control tone deliberately rather than defaulting to a flat register, and the standard call feels comfortable.', '{}', array['phone', 'energy', 'structure']::text[], 'published')
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  objective = excluded.objective,
  duration_minutes = excluded.duration_minutes,
  participants = excluded.participants,
  difficulty = excluded.difficulty,
  instructions = excluded.instructions,
  facilitator_notes = excluded.facilitator_notes,
  expected_outcome = excluded.expected_outcome,
  materials = excluded.materials,
  tags = excluded.tags,
  status = excluded.status
;

commit;
