-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 18 OF 23: Script library - 22 scripts extracted from the source material
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Script library - 22 scripts extracted from the source material
-- ---------------------------------------------------------------------------

insert into public.scripts (id, slug, title, kind, channel, situation, language, lines, notes, tags, sort_order, status) values
  ('4debac69-1d35-5cd6-8032-f8e454fc4bee', 'answer-professionally-standard-outbound-opening', 'Standard outbound opening', 'phone', 'both', 'Answer Professionally', 'mixed', array['Good morning! This is Jason from KCO Kangkong Chips.', 'Am I speaking with Ms. Rivera?', 'I am following up on your inquiry about becoming a KCO reseller.', 'Is now a good time for a quick two-minute call?']::text[], 'Source: Phone Etiquette - Answer Professionally', array['phone', 'etiquette', 'tone', 'foundation']::text[], 0, 'published'),
  ('7a280012-55e8-5e04-814c-1d24433020f3', 'use-the-customer-s-name-placement-that-works', 'Placement that works', 'phone', 'both', 'Use the Customer''s Name', 'mixed', array['Opening - "Good afternoon, Ms. Rivera, this is Jason from KCO."', 'Presenting - "Ms. Rivera, based on what you said about your store, the starter pack fits best."', 'Closing - "Ms. Rivera, shall I reserve one for delivery this Friday?"']::text[], 'Source: Phone Etiquette - Use the Customer''s Name', array['phone', 'etiquette', 'tone', 'foundation']::text[], 1, 'published'),
  ('c576dd0b-3376-5bf4-a4ad-707c7ac38c56', 'handling-i-m-busy-the-20-second-exit', 'The 20-second exit', 'phone', 'both', 'Handling "I’m Busy"', 'mixed', array['Customer: Sorry, busy ako ngayon.', 'You: Naku, understood po - I will keep this short.', 'You: Would it be better if I call you back later today, or tomorrow morning?', 'Customer: Tomorrow morning na lang.', 'You: Perfect. I will call at 9 AM tomorrow. Thank you, Ms. Rivera!']::text[], 'Source: Phone Etiquette - Handling "I’m Busy"', array['phone', 'etiquette', 'tone', 'foundation']::text[], 2, 'published'),
  ('a3212e00-206e-5bf1-8f8c-f4cbef3b2654', 'handling-angry-customers-damaged-delivery', 'Damaged delivery', 'complaint', 'both', 'Handling Angry Customers', 'mixed', array['I hear you, Ms. Rivera, and I am sorry this happened with your delivery.', 'Let me make sure I have it right: six packs out of fifty arrived crushed. Correct po?', 'Here is what I will do - I will file this with our logistics team today and send you the reference number.', 'I will call you back before 5 PM with the replacement schedule.']::text[], 'Source: Phone Etiquette - Handling Angry Customers', array['phone', 'etiquette', 'tone', 'foundation']::text[], 3, 'published'),
  ('fb65167f-2370-52b5-985c-8a6094657296', 'phone-hold-etiquette-placing-a-customer-on-hold', 'Placing a customer on hold', 'phone', 'phone', 'Phone Hold Etiquette', 'mixed', array['May I ask you to hold for a moment while I check your order details?', 'It should take about one minute. Is that okay po?', '[on return] Thank you for waiting, Ms. Rivera.']::text[], 'Source: Phone Etiquette - Phone Hold Etiquette', array['phone', 'etiquette', 'tone', 'foundation']::text[], 4, 'published'),
  ('2d54b2d9-e04f-5483-9101-66fec8e6b916', 'call-drops-reconnecting', 'Reconnecting', 'phone', 'phone', 'Call Drops', 'mixed', array['Hi Ms. Rivera, sorry po - nadiscon ang linya.', 'This is Jason from KCO again. We were at the delivery schedule.', 'You mentioned Friday works for you - shall I confirm that?']::text[], 'Source: Phone Etiquette - Call Drops', array['phone', 'etiquette', 'tone', 'foundation']::text[], 5, 'published'),
  ('3fc1d1f2-838e-58f9-b605-a19c297a16d0', 'step-1-greet-greet', 'Greet', 'phone', 'both', 'Step 1 - Greet', 'mixed', array['Good morning po!', 'This is Jason from KCO Kangkong Chips.']::text[], 'Source: Sales Call Structure - Step 1 - Greet', array['phone', 'structure', 'closing', 'discovery']::text[], 6, 'published'),
  ('4740a11e-1a24-5c45-a5ed-76bae0593165', 'step-2-introduce-introduce', 'Introduce', 'phone', 'both', 'Step 2 - Introduce', 'mixed', array['Am I speaking with Ms. Rivera?', 'I am part of the KCO reseller support team.']::text[], 'Source: Sales Call Structure - Step 2 - Introduce', array['phone', 'structure', 'closing', 'discovery']::text[], 7, 'published'),
  ('0fbb27ac-b0b3-51bd-bf68-01a4c8008ebc', 'step-3-purpose-purpose', 'Purpose', 'phone', 'both', 'Step 3 - Purpose', 'mixed', array['I am following up on your inquiry about becoming a KCO reseller.', 'Do you have about two minutes so I can walk you through it?']::text[], 'Source: Sales Call Structure - Step 3 - Purpose', array['phone', 'structure', 'closing', 'discovery']::text[], 8, 'published'),
  ('9ff89a7a-4589-55ea-abd0-1e31e8a3caa5', 'step-5-present-present-tied-to-discovery', 'Present - tied to discovery', 'qualification', 'both', 'Step 5 - Present', 'mixed', array['Based on what you said - online selling and first time as a reseller - ', 'the starter pack fits you best.', 'It is the smallest order we do, so your first commitment stays low,', 'and it gives you enough stock to test which flavour moves fastest.', 'We also send you the product photos and captions you can post right away.']::text[], 'Source: Sales Call Structure - Step 5 - Present', array['phone', 'structure', 'closing', 'discovery']::text[], 9, 'published'),
  ('4aaebdaf-7810-520d-8d8a-9ebc82f08f67', 'step-8-confirm-end-confirm-and-end', 'Confirm and end', 'closing', 'both', 'Step 8 - Confirm + End', 'mixed', array['To confirm po - one starter pack, delivery Friday, cash on delivery.', 'I will message you the order summary right after this call.', 'If anything changes, you can reply to that same thread.', 'Thank you for your time, Ms. Rivera. Enjoy your day!']::text[], 'Source: Sales Call Structure - Step 8 - Confirm + End', array['phone', 'structure', 'closing', 'discovery']::text[], 10, 'published'),
  ('7b1b2682-ad5d-5374-9520-b1e5ce94488a', 'always-greet-always-respond-promptly-opening-a-new-chat', 'Opening a new chat', 'chat', 'chat', 'Always Greet, Always Respond Promptly', 'mixed', array['Hi po! Good afternoon 😊', 'Thank you for messaging KCO Kangkong Chips.', 'This is Jason - how may I help you today?']::text[], 'Source: Chat Etiquette - Always Greet, Always Respond Promptly', array['chat', 'etiquette', 'messenger', 'foundation']::text[], 11, 'published'),
  ('69aa7469-a232-5ebd-9607-5e3a570bdcec', 'read-the-entire-conversation-before-replying-taking-over-a-t', 'Taking over a thread', 'follow-up', 'both', 'Read the Entire Conversation Before Replying', 'mixed', array['Hi Ms. Rivera, this is Jason from KCO 😊', 'I have read your conversation with my colleague.', 'I see you are looking at 50 packs of Original for Friday delivery.', 'Let me take it from here po - shall I confirm that order?']::text[], 'Source: Chat Etiquette - Read the Entire Conversation Before Replying', array['chat', 'etiquette', 'messenger', 'foundation']::text[], 12, 'published'),
  ('6ecf8b82-c066-5eb0-939a-d432cad5a361', 'order-confirmation-order-summary-message', 'Order summary message', 'closing', 'both', 'Order Confirmation', 'mixed', array['Confirming your order po, Ms. Rivera 😊', 'Item: Kangkong Chips - Original', 'Quantity: 50 packs', 'Total: ₱10,000', 'Delivery: Friday, within Metro Manila', 'Payment: Cash on delivery', 'Delivery address: [full address]', 'Contact number: [number]', 'Tama po ba lahat?']::text[], 'Source: Chat Etiquette - Order Confirmation', array['chat', 'etiquette', 'messenger', 'foundation']::text[], 13, 'published'),
  ('aa0db095-90f0-5b47-a5db-fd132be161ad', 'complaint-handling-in-chat-damaged-goods-complaint', 'Damaged goods complaint', 'complaint', 'both', 'Complaint Handling in Chat', 'mixed', array['I am really sorry about this, Ms. Rivera.', 'To confirm po - 6 out of 50 packs arrived crushed?', 'I am filing this with our logistics team right now.', 'I will update you before 5 PM today with the replacement schedule.', 'Thank you for the photo, malaking tulong po ito sa report.']::text[], 'Source: Chat Etiquette - Complaint Handling in Chat', array['chat', 'etiquette', 'messenger', 'foundation']::text[], 14, 'published'),
  ('30b1c282-7434-5b4a-a2be-b2ce560f5c52', 'professional-closing-and-chat-don-ts-closing-a-chat', 'Closing a chat', 'closing', 'both', 'Professional Closing and Chat Don’ts', 'mixed', array['Thank you po for your time, Ms. Rivera! 😊', 'Nandito lang po ako kung may tanong pa kayo.', 'Have a great day po!']::text[], 'Source: Chat Etiquette - Professional Closing and Chat Don’ts', array['chat', 'etiquette', 'messenger', 'foundation']::text[], 15, 'published'),
  ('f4b81d96-8001-534d-b783-cba53cfea77d', 'g-greet-greet', 'Greet', 'phone', 'both', 'G - Greet', 'mixed', array['Hi po! Good morning 😊', 'Thank you for messaging KCO Kangkong Chips.', 'This is Jason - how may I help you today?']::text[], 'Source: The KCO Chat Formula - G - Greet', array['chat', 'formula', 'structure', 'follow-up']::text[], 16, 'published'),
  ('679305ff-af9c-5c1f-9c0f-a1e6d3a6af0c', 'p-present-present-in-chat', 'Present in chat', 'chat', 'chat', 'P - Present', 'mixed', array['Since online selling po ang plan niyo and first time as reseller,', 'the starter pack is the best fit 😊', '50 packs at ₱200 each, delivery included sa Metro Manila.', 'Kasama na rin po ang product photos at captions na pwede niyo agad i-post.', 'Gusto niyo po bang i-reserve ko na para sa Friday delivery?']::text[], 'Source: The KCO Chat Formula - P - Present', array['chat', 'formula', 'structure', 'follow-up']::text[], 17, 'published'),
  ('1de932cf-e93c-5614-b4ef-3759d4210a70', 'f-follow-up-follow-up-that-adds-value', 'Follow-up that adds value', 'follow-up', 'both', 'F - Follow Up', 'mixed', array['Hi Ms. Rivera! 😊 Following up po sa inquiry niyo.', 'Ito po pala yung sample photos na pwede niyo i-post pag nag-start na kayo.', 'Nandito lang po ako kung may tanong kayo - no rush po.']::text[], 'Source: The KCO Chat Formula - F - Follow Up', array['chat', 'formula', 'structure', 'follow-up']::text[], 18, 'published'),
  ('91c6209a-fb08-5a55-b199-23a0a3061170', 'phone-opening-phone-opening', 'Phone Opening', 'phone', 'phone', 'Phone Opening', 'mixed', array['Good morning! This is Jason from KCO Kangkong Chips.', 'Am I speaking with Ms. Rivera?', 'I am following up on your inquiry about becoming a KCO reseller.', 'Is now a good time for a quick two-minute call?']::text[], 'Source: Quick Reference - Phone Opening', array['script']::text[], 19, 'published'),
  ('f0daa1a5-c2e0-59be-aefc-733bf897c101', 'chat-opening-chat-opening', 'Chat Opening', 'chat', 'chat', 'Chat Opening', 'mixed', array['Hi po! Good afternoon 😊', 'Thank you for messaging KCO Kangkong Chips.', 'This is Jason - how may I help you today?']::text[], 'Source: Quick Reference - Chat Opening', array['script']::text[], 20, 'published'),
  ('eae17e7d-5b4a-57e9-96c6-7db574716d10', 'order-confirmation-send-as-one-message-they-can-screenshot', 'Send as one message they can screenshot', 'closing', 'both', 'Order Confirmation', 'mixed', array['Confirming your order po 😊', 'Item: Kangkong Chips - Original', 'Quantity: 50 packs', 'Total: ₱10,000', 'Delivery: Friday, Metro Manila', 'Payment: Cash on delivery', 'Tama po ba lahat?']::text[], 'Source: Quick Reference - Order Confirmation', array['checklist']::text[], 21, 'published')
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  kind = excluded.kind,
  channel = excluded.channel,
  situation = excluded.situation,
  language = excluded.language,
  lines = excluded.lines,
  notes = excluded.notes,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  status = excluded.status
;

commit;
