-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 19 OF 23: Professional wording - avoid / use pairs
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Professional wording - avoid / use pairs
-- ---------------------------------------------------------------------------

insert into public.wording_pairs (id, avoid, use, context, note, tags, sort_order, status) values
  ('dd50b65a-2c0a-5f9a-9af3-b9470ff946c7', 'Wait lang.', 'May I ask you to hold for a moment?', 'phone', 'Always ask, never instruct.', array['hold']::text[], 0, 'published'),
  ('672a589f-8563-559b-969c-590c5a93bfb8', 'Hindi ko alam.', 'Let me verify that for you.', 'both', 'Add a time commitment: "…and I will come back to you within the hour."', array['accuracy']::text[], 1, 'published'),
  ('60a00429-a14e-5826-a085-951d4f1aafca', 'Di ko gets.', 'May I clarify what you mean?', 'both', '', array['clarify']::text[], 2, 'published'),
  ('22ac3281-7578-558e-8467-8813d9bb8fe9', 'Ha? Ano po?', 'I am sorry, could you repeat that please?', 'phone', '', array['clarify']::text[], 3, 'published'),
  ('ec8bd791-5b1a-5f75-b631-4d216a3f6836', 'Wala kami niyan.', 'That variant is not available right now - may I suggest an alternative?', 'both', '', array['stock']::text[], 4, 'published'),
  ('5cb30692-5e0a-5861-af8d-db33592ee0db', 'Sige, bye.', 'Thank you for your time, Ms. Rivera. Have a good day!', 'phone', '', array['closing']::text[], 5, 'published'),
  ('7cf650e8-19d6-56da-a089-e667986c6996', 'Hindi pwede yan.', 'What I can do for you instead is…', 'both', 'Always follow a no with an alternative.', array['boundaries']::text[], 6, 'published'),
  ('2cdf3b1c-2668-56fe-ada5-43450574331b', 'Mali kayo.', 'Let me check the details so we are looking at the same information.', 'both', '', array['conflict']::text[], 7, 'published'),
  ('24f37894-ba34-5475-9f0b-dc0c03bc39ac', 'Bakit hindi niyo binasa?', 'Let me walk you through that part again.', 'both', '', array['conflict']::text[], 8, 'published'),
  ('3c905dec-9631-5337-9470-845cce6471be', 'Kelangan niyo mag-decide na.', 'Would you like me to reserve one while you decide?', 'both', '', array['closing']::text[], 9, 'published'),
  ('edd8ee67-8d7e-5206-bc20-74b12518673d', 'Yan na po ang pinakamura.', 'That is our reseller price, and it already includes delivery within Metro Manila.', 'both', '', array['price']::text[], 10, 'published'),
  ('41228b02-579c-5dcd-a670-63aa9e6dec41', 'ok po sure', 'Sure po! 😊', 'chat', '', array['tone']::text[], 11, 'published'),
  ('51910982-3245-5a74-883e-a31afaecf2ad', 'wla po eh', 'Wala pa po sa ngayon, but restock is next week.', 'chat', '', array['stock']::text[], 12, 'published'),
  ('dafef794-0a50-5a1e-8760-0f70b6617072', 'thnx po', 'Thank you po!', 'chat', '', array['tone']::text[], 13, 'published'),
  ('64399f02-9d8f-575f-a216-1bc7a62dae02', 'sry d ko alam', 'Let me verify that for you po.', 'chat', '', array['accuracy']::text[], 14, 'published'),
  ('fa284f42-c973-5ed7-a103-67ba41d08537', 'Sino ba kausap niyo dati?', 'Let me read the conversation so you do not have to repeat yourself.', 'chat', '', array['handover']::text[], 15, 'published'),
  ('6b0a3a3a-ff41-5013-b4fe-2e5431846933', 'Sabi na sa post eh.', 'Yes po, and to make it clearer - here are the details again.', 'chat', '', array['conflict']::text[], 16, 'published'),
  ('6557a5c8-850d-5ded-8ae6-19b74110c6da', 'Bili na po kayo.', 'Gusto niyo po bang i-reserve ko para sa Friday delivery?', 'chat', '', array['closing']::text[], 17, 'published'),
  ('40a4c24d-ff5d-5acf-8762-34e22675ef78', 'Sure na po yan kikita kayo.', 'Ang kita po ay depende sa selling price at area niyo - pwede natin i-compute base sa numbers niyo.', 'both', 'Never guarantee earnings. See the objection card "Magkano ang kita ko?".', array['claims']::text[], 18, 'published'),
  ('a1ea9f13-c4c7-5fbe-b709-2222927802ce', 'Last stock na po!', 'Limited po ang natitira sa batch na ito - gusto niyo po bang i-hold ko para sa inyo?', 'both', 'Only if it is actually true. False urgency is prohibited.', array['claims']::text[], 19, 'published'),
  ('70199edc-b4a7-53f4-a793-d8322ceb9f9b', 'Ay sorry, na-forget ko.', 'Apologies for the delay - here is the update I promised.', 'both', '', array['tone']::text[], 20, 'published'),
  ('424847ed-27f4-54e5-894f-e3104cd4da0c', 'Tawag na lang po kayo ulit.', 'I will call you back at 4 PM today - is that convenient?', 'phone', 'The agent owns the callback, never the customer.', array['callback']::text[], 21, 'published'),
  ('4f6ac077-49c6-5c96-8d43-74a535142ba1', 'Ganun talaga.', 'I understand that is frustrating. Here is what I can do.', 'both', '', array['complaints']::text[], 22, 'published'),
  ('a32e6c97-d54b-5930-9958-d7e471c7c98b', 'Fault yun ng courier.', 'I am sorry this happened. I am filing it with our logistics team today.', 'both', 'Never blame a third party by name.', array['complaints']::text[], 23, 'published'),
  ('a21f2b6d-202d-54fc-add9-dd6047adcf1b', 'Magkano budget mo?', 'May I ask what budget range you are comfortable with?', 'both', '', array['discovery']::text[], 24, 'published'),
  ('a06cbeb7-b508-5be7-9712-71035d62696b', 'Hindi po namin yan ginagawa.', 'That is outside what I can approve - let me check with my team lead and come back to you.', 'both', '', array['escalation']::text[], 25, 'published')
on conflict (id) do update set
  avoid = excluded.avoid,
  use = excluded.use,
  context = excluded.context,
  note = excluded.note,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  status = excluded.status
;

commit;
