-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 20 OF 23: Quick reference cards
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Quick reference cards
-- ---------------------------------------------------------------------------

insert into public.quick_reference_items (id, slug, title, kicker, kind, channel, blocks, sort_order, status) values
  ('0fca40e6-c788-5bdb-82a8-ddf93732d2bf', 'phone-opening', 'Phone Opening', 'The first seven seconds', 'script', 'phone', '[{"id":"qr-po-b1","type":"script","language":"mixed","lines":["Good morning! This is Jason from KCO Kangkong Chips.","Am I speaking with Ms. Rivera?","I am following up on your inquiry about becoming a KCO reseller.","Is now a good time for a quick two-minute call?"]},{"id":"qr-po-b2","type":"checklist","items":[{"text":"Time of day"},{"text":"Your name"},{"text":"Full company name"},{"text":"Confirm the person"},{"text":"One-sentence purpose"},{"text":"Ask for their time"}]}]'::jsonb, 0, 'published'),
  ('3363d68f-a3c0-5ced-b05b-c2dc6e44cd9f', 'chat-opening', 'Chat Opening', 'Reply within two minutes', 'script', 'chat', '[{"id":"qr-co-b1","type":"script","language":"mixed","lines":["Hi po! Good afternoon 😊","Thank you for messaging KCO Kangkong Chips.","This is Jason - how may I help you today?"]},{"id":"qr-co-b2","type":"callout","variant":"info","title":"Then ask before you send","text":"Are you planning to sell online, sa physical store, or for personal use? One question before any details go out."}]'::jsonb, 1, 'published'),
  ('91b41ac2-9819-5443-bc0f-38175217acbb', 'sales-call-structure', 'Sales Call Structure', 'Eight steps, in order', 'formula', 'phone', '[{"id":"qr-cs-b1","type":"formula","name":"8-Step Sales Call","steps":[{"key":"1","label":"Greet","detail":"Time of day, name, KCO Kangkong Chips."},{"key":"2","label":"Introduce","detail":"Confirm the person and your role."},{"key":"3","label":"Purpose","detail":"One sentence, then ask for their time."},{"key":"4","label":"Discover","detail":"Three to four questions."},{"key":"5","label":"Present","detail":"One package, tied to their answers."},{"key":"6","label":"Handle Objection","detail":"A.C.A.C."},{"key":"7","label":"Close","detail":"Specific, small, dated."},{"key":"8","label":"Confirm + End","detail":"Recap, next step, thank them."}]}]'::jsonb, 2, 'published'),
  ('6503d1f8-90b7-5a5d-b6ca-8c38a36c0896', 'kco-chat-formula', 'KCO Chat Formula', 'G.A.L.P.H.C.F.R.', 'formula', 'chat', '[{"id":"qr-cf-b1","type":"formula","name":"G.A.L.P.H.C.F.R.","steps":[{"key":"G","label":"Greet","detail":"Name, thanks, warmth."},{"key":"A","label":"Ask","detail":"One qualifying question first."},{"key":"L","label":"Listen","detail":"Answer everything they asked."},{"key":"P","label":"Present","detail":"One package, their words."},{"key":"H","label":"Handle","detail":"A.C.A.C. in writing."},{"key":"C","label":"Close","detail":"Specific and dated."},{"key":"F","label":"Follow Up","detail":"Two maximum, each adds value."},{"key":"R","label":"Report","detail":"Log the outcome."}]}]'::jsonb, 3, 'published'),
  ('b8600687-2270-5821-bb70-1d2503155901', 'acac-objection-formula', 'A.C.A.C. Objection Formula', 'Works on all twelve objections', 'formula', 'both', '[{"id":"qr-acac-b1","type":"formula","name":"A.C.A.C.","steps":[{"key":"A","label":"Acknowledge","detail":"Validate the concern in one sentence."},{"key":"C","label":"Clarify","detail":"One question to find the real version of it."},{"key":"A","label":"Address","detail":"Answer that specific concern only."},{"key":"C","label":"Close","detail":"Return to a small, dated next step."}]},{"id":"qr-acac-b2","type":"callout","variant":"warning","title":"Clarify is the step people skip","text":"Without it you answer the generic objection instead of theirs."}]'::jsonb, 4, 'published'),
  ('6a27a907-1ce9-5f51-ab54-c86163de42f5', 'order-confirmation', 'Order Confirmation', 'Eight fields, every time', 'checklist', 'both', '[{"id":"qr-oc-b1","type":"checklist","items":[{"text":"Item and flavour"},{"text":"Quantity"},{"text":"Total amount"},{"text":"Delivery date"},{"text":"Payment method"},{"text":"Complete delivery address"},{"text":"Contact number"},{"text":"Explicit \"tama po ba?\" confirmation"}]},{"id":"qr-oc-b2","type":"script","label":"Send as one message they can screenshot","language":"mixed","lines":["Confirming your order po 😊","Item: Kangkong Chips - Original","Quantity: 50 packs","Total: ₱10,000","Delivery: Friday, Metro Manila","Payment: Cash on delivery","Tama po ba lahat?"]}]'::jsonb, 5, 'published'),
  ('231b77d5-a6aa-56ca-acbf-9f8e1f9b1855', 'complaint-handling', 'Complaint Handling', 'Acknowledge → Apologise → Act → Follow up', 'checklist', 'both', '[{"id":"qr-cp-b1","type":"numbered","items":["Let them finish. Defend nothing.","Acknowledge the specific problem in their words.","Apologise for the experience, not for unverified fault.","State what you will do and by when.","Follow up when you said you would."]},{"id":"qr-cp-b2","type":"dosdonts","dos":["Ask for a photo early","Give a reference number","Keep every promised follow-up"],"donts":["Emoji in a complaint thread","Blame the courier by name","Promise a refund you cannot approve","Go silent while waiting"]}]'::jsonb, 6, 'published'),
  ('96781659-78da-5ef4-aa93-0f0d3603a8ee', 'closing-scripts', 'Closing Scripts', 'Specific, small, dated', 'script', 'both', '[{"id":"qr-cl-b1","type":"comparison","caption":"Swap the weak close for the clear one","columns":["Weak","Clear"],"rows":[["Let me know po if interested.","Shall I reserve a starter pack for Friday delivery?"],["I will send details.","I will send it now - can I call you at 4 PM to confirm?"],["Sige, think about it.","Which works better, Friday or Monday delivery?"],["Interested po ba kayo?","I will hold one pack for you until tomorrow - okay po ba?"]]},{"id":"qr-cl-b2","type":"callout","variant":"success","title":"Then stop talking","text":"After you ask, stay quiet. Filling the silence yourself is how a close becomes a discount."}]'::jsonb, 7, 'published'),
  ('dabf3c29-7747-5166-a768-d6938e189ae1', 'professional-wording', 'Professional Wording', 'The full swap library', 'rule', 'both', '[{"id":"qr-w-b1","type":"wording","pairs":[{"avoid":"Wait lang.","use":"May I ask you to hold for a moment?"},{"avoid":"Hindi ko alam.","use":"Let me verify that for you."},{"avoid":"Di ko gets.","use":"May I clarify what you mean?"},{"avoid":"Hindi pwede yan.","use":"What I can do for you instead is…"},{"avoid":"Ganun talaga.","use":"I understand that is frustrating. Here is what I can do."}]},{"id":"qr-w-b2","type":"text","text":"The searchable library of all 26 swaps lives in Learning → Professional Wording, and in the wording search on this page."}]'::jsonb, 8, 'published'),
  ('dc551208-c799-55b8-8106-8968520c71dc', 'golden-rules', 'Golden Rules', 'The two sentences that decide everything else', 'rule', 'both', '[{"id":"qr-gr-b1","type":"quote","text":"Don''t just sound like a salesperson. Sound like a professional who genuinely wants to help.","attribution":"Sales Calls"},{"id":"qr-gr-b2","type":"quote","text":"Don''t just reply to the customer. Guide the customer toward the right solution.","attribution":"Chat Support"},{"id":"qr-gr-b3","type":"callout","variant":"danger","title":"And the hard rule","text":"Never guarantee earnings, a payback period, or that stock will sell. Never invent a product fact. Never promise what you cannot authorise."}]'::jsonb, 9, 'published')
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  kicker = excluded.kicker,
  kind = excluded.kind,
  channel = excluded.channel,
  blocks = excluded.blocks,
  sort_order = excluded.sort_order,
  status = excluded.status
;

commit;
