-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 21 OF 23: Competency framework - the documented 1-5 scale
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Competency framework - the documented 1-5 scale
-- ---------------------------------------------------------------------------

insert into public.competency_levels (level, label, description) values
  (1, 'Needs Significant Improvement', ''),
  (2, 'Developing', ''),
  (3, 'Competent', ''),
  (4, 'Proficient', ''),
  (5, 'Exceptional', '')
on conflict (level) do update set
  label = excluded.label,
  description = excluded.description
;

insert into public.competencies (id, slug, name, definition, cluster, behavioral_indicators, sort_order, status) values
  ('4c8bb17a-929b-5faa-869c-b7bb8c93448d', 'customer-focus', 'Customer Focus', '', 'core', '{}', 0, 'published'),
  ('d84fcdbe-6c8f-5167-8be9-1e23c68fb0a3', 'communication-skills', 'Communication Skills', '', 'core', '{}', 1, 'published'),
  ('bf6200db-0cb2-583d-b192-739b7c8abe0f', 'active-listening', 'Active Listening', '', 'core', '{}', 2, 'published'),
  ('a901b108-be6e-5a77-bfc0-a06fbc05118c', 'product-knowledge', 'Product Knowledge', '', 'core', '{}', 3, 'published'),
  ('fe3b22c7-b89c-5d5e-88bd-a8f4aca6bb41', 'professionalism', 'Professionalism', '', 'core', '{}', 4, 'published'),
  ('1a4ffe0a-2fee-5582-b849-2e4d87751894', 'sales-ability', 'Sales Ability', '', 'sales', '{}', 5, 'published'),
  ('a81f6608-e166-52fc-aa2d-7a9bb10d1548', 'needs-analysis', 'Needs Analysis', '', 'sales', '{}', 6, 'published'),
  ('4d586709-b69d-5905-9752-5e33d25cacbf', 'persuasion-influencing', 'Persuasion & Influencing', '', 'sales', '{}', 7, 'published'),
  ('bb351282-31d3-5c26-8155-380e07fbb5d8', 'objection-handling', 'Objection Handling', '', 'sales', '{}', 8, 'published'),
  ('81d7e3cb-8f16-5b53-b8ac-c44378f339bd', 'closing-skills', 'Closing Skills', '', 'sales', '{}', 9, 'published'),
  ('7c5f0acb-b508-5c39-aaa0-d2a6a319d256', 'follow-up-management', 'Follow-Up Management', '', 'sales', '{}', 10, 'published'),
  ('6badb52d-0b0e-58f7-8314-87cef31cdeb8', 'chat-etiquette', 'Chat Etiquette', '', 'chat', '{}', 11, 'published'),
  ('18d7500b-c441-5c28-9582-c00673256b6d', 'chat-conversion', 'Chat Conversion', '', 'chat', '{}', 12, 'published'),
  ('bba75e86-f190-521c-ab1c-8e55df4e0068', 'multitasking-response-management', 'Multitasking & Response Management', '', 'chat', '{}', 13, 'published')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  definition = excluded.definition,
  cluster = excluded.cluster,
  behavioral_indicators = excluded.behavioral_indicators,
  sort_order = excluded.sort_order,
  status = excluded.status
;

commit;
