-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 22 OF 23: Sales Bible - structure seeded, values left for management
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- Sales Bible - structure seeded, values left for management
-- ---------------------------------------------------------------------------

insert into public.sales_bible_sections (id, slug, title, summary, sort_order) values
  ('70d2890c-a052-5f2f-97fc-1506c47dbdff', 'product', 'Product', 'What the product is. Every field here must be verified before an agent quotes it.', 0),
  ('7f362b12-16d9-5f78-9a76-9434fbb0498c', 'negosyo', 'Negosyo', 'Reseller packages and pricing. Nothing in this section may be quoted to a customer until it is marked verified.', 1),
  ('f76b29df-1197-5e0d-a832-3dff6b243a04', 'sales', 'Sales', 'The conversation itself. These are populated from the training modules already in the library.', 2),
  ('1c6cdd60-064d-573d-b391-5b42edf56be2', 'faq', 'FAQ', 'The questions customers ask most. Answers must match actual company policy.', 3)
on conflict (id) do update set
  slug = excluded.slug,
  title = excluded.title,
  summary = excluded.summary,
  sort_order = excluded.sort_order
;

insert into public.sales_bible_entries (id, section_id, label, value, detail, verified, requires_approval, sort_order) values
  ('5146b9e2-fbbe-5842-8cac-28e4e113b18a', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Product name', null, 'Full product name as it appears on packaging.', false, false, 0),
  ('bb8680b9-d08c-5710-8c26-75d02c8cb0a9', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Available flavours', null, 'The complete flavour range currently in production.', false, false, 1),
  ('3e58a94f-cd95-58f0-ad8a-29538af3761a', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Pack sizes', null, 'Every size offered, with net weight.', false, false, 2),
  ('75bddb92-0729-53b5-85f5-cbab959273bb', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Shelf life', null, 'From manufacture date, and the storage conditions it assumes.', false, false, 3),
  ('2d6882a7-07a5-5cc5-b054-151bbb4eb747', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Certifications', null, 'FDA, LTO, halal or other certifications actually held.', false, false, 4),
  ('20c4e882-4d6e-5adc-9e55-100b4cb01c1f', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Brand story', null, 'The approved short version an agent may tell a customer.', false, false, 5),
  ('6d40c19e-b26d-5664-9303-665fbd69d4c5', '70d2890c-a052-5f2f-97fc-1506c47dbdff', 'Ingredients', null, 'For allergen questions.', false, false, 6),
  ('e9d0cda3-d292-529f-a349-65bb24db7e37', '7f362b12-16d9-5f78-9a76-9434fbb0498c', 'Package inclusions', null, 'Exactly what a reseller package contains.', false, false, 0),
  ('557273b5-47f7-544c-9332-fd470db54ad7', '7f362b12-16d9-5f78-9a76-9434fbb0498c', 'Package price', null, 'The price management has approved for quoting.', false, false, 1),
  ('2e8e86d0-b04d-59d0-9641-e28f6497b4c1', '7f362b12-16d9-5f78-9a76-9434fbb0498c', 'Reseller price per pack', null, 'Wholesale price at each tier, if tiers exist.', false, false, 2),
  ('c2e8fb83-c1f2-5b7d-8c1a-105c7abfbf2d', '7f362b12-16d9-5f78-9a76-9434fbb0498c', 'Suggested retail price', null, 'SRP as approved - not a figure an agent estimates.', false, false, 3),
  ('a6265bdd-838a-5a98-aece-d14b7ed48c99', '7f362b12-16d9-5f78-9a76-9434fbb0498c', 'Minimum order', null, 'Minimum quantity or value for a reseller order.', false, false, 4),
  ('f4d57c45-31b4-5db5-b48b-40d3cd848185', '7f362b12-16d9-5f78-9a76-9434fbb0498c', 'Sample profit computation', null, 'An illustrative computation only. Must be labelled potential gross profit, never guaranteed income (§46).', false, true, 5),
  ('c396a0e5-00a5-5850-9eea-921f37728d75', 'f76b29df-1197-5e0d-a832-3dff6b243a04', 'Opening script', null, 'See Quick Reference - Phone Opening and Chat Opening.', false, false, 0),
  ('220e54da-3312-5d35-8fd0-5f806f6bc7c0', 'f76b29df-1197-5e0d-a832-3dff6b243a04', 'Qualification questions', null, 'See Quick Reference - Qualification Questions.', false, false, 1),
  ('a2ddb13e-7c82-553b-a30f-455f52c88f65', 'f76b29df-1197-5e0d-a832-3dff6b243a04', 'Pitch', null, 'Needs the approved product pitch, which depends on verified product data.', false, false, 2),
  ('34b70c1c-d032-5950-9809-27c633f034ac', 'f76b29df-1197-5e0d-a832-3dff6b243a04', 'Objection handling', null, 'See the Objection Handling library - 12 objections with A.C.A.C. responses.', false, false, 3),
  ('1b232da1-10d0-5802-9953-0dab44854edf', 'f76b29df-1197-5e0d-a832-3dff6b243a04', 'Closing scripts', null, 'See Quick Reference - Closing Scripts.', false, false, 4),
  ('2c355af9-acbd-5ce0-9bdc-cb8524bd54bd', '1c6cdd60-064d-573d-b391-5b42edf56be2', 'Delivery', null, 'Areas covered, lead times, and who shoulders the cost.', false, false, 0),
  ('31c5ddfe-e8eb-517d-ae3e-05ca19934850', '1c6cdd60-064d-573d-b391-5b42edf56be2', 'Payment', null, 'Accepted methods, and whether COD is available.', false, false, 1),
  ('67dfe40a-4887-5a6f-bd09-4dcdf3108bac', '1c6cdd60-064d-573d-b391-5b42edf56be2', 'Minimum order', null, 'For retail customers as distinct from resellers.', false, false, 2),
  ('061d840e-4c6e-5d35-a2ce-d060456462c5', '1c6cdd60-064d-573d-b391-5b42edf56be2', 'Reordering', null, 'How an existing reseller places a repeat order.', false, false, 3),
  ('6f2e4897-c9f4-5c8b-81c8-97ff38a6213c', '1c6cdd60-064d-573d-b391-5b42edf56be2', 'Reselling', null, 'Territory rules and any exclusivity arrangements.', false, false, 4),
  ('ad4666c1-e720-515b-a2ce-f4863eb37c8e', '1c6cdd60-064d-573d-b391-5b42edf56be2', 'Marketing support', null, 'What materials or support a reseller actually receives.', false, false, 5)
on conflict (id) do update set
  section_id = excluded.section_id,
  label = excluded.label,
  value = excluded.value,
  detail = excluded.detail,
  verified = excluded.verified,
  requires_approval = excluded.requires_approval,
  sort_order = excluded.sort_order
;

commit;
