-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- PART 23 OF 23: Seed verification (§68)
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- Seed verification (§68)
-- ---------------------------------------------------------------------------

-- Every count below must be non-zero, and every integrity check must be 0.
select 'categories' as table, count(*) from public.categories
union all select 'modules', count(*) from public.modules
union all select 'lessons', count(*) from public.lessons
union all select 'content_blocks', count(*) from public.content_blocks
union all select 'learning_paths', count(*) from public.learning_paths
union all select 'learning_path_items', count(*) from public.learning_path_items
union all select 'assessments', count(*) from public.assessments
union all select 'assessment_questions', count(*) from public.assessment_questions
union all select 'assessment_choices', count(*) from public.assessment_choices
union all select 'training_activities', count(*) from public.training_activities
union all select 'practice_scenarios', count(*) from public.practice_scenarios
union all select 'objections', count(*) from public.objections
union all select 'scripts', count(*) from public.scripts
union all select 'wording_pairs', count(*) from public.wording_pairs
union all select 'quick_reference_items', count(*) from public.quick_reference_items
union all select 'competencies', count(*) from public.competencies
union all select 'sales_bible_entries', count(*) from public.sales_bible_entries
order by 1;

select 'lessons with no module' as check, count(*) from public.lessons l
  left join public.modules m on m.id = l.module_id where m.id is null
union all
select 'blocks with no lesson', count(*) from public.content_blocks b
  left join public.lessons l on l.id = b.lesson_id where l.id is null
union all
select 'path items with no module', count(*) from public.learning_path_items i
  left join public.modules m on m.id = i.module_id
  where i.module_id is not null and m.id is null
union all
select 'questions with no correct choice', count(*) from public.assessment_questions q
  where q.type <> 'short_answer'
    and not exists (select 1 from public.assessment_choices c
                     where c.question_id = q.id and c.is_correct)
union all
select 'published modules with no lessons', count(*) from public.modules m
  where m.status = 'published'
    and not exists (select 1 from public.lessons l where l.module_id = m.id)
union all
select 'sales bible entries with unverified values', count(*)
  from public.sales_bible_entries where value is not null and not verified;

