/**
 * Seed generator (§42).
 *
 * Reads the authored content in `src/data` - which is where the source
 * training documents were transcribed - and emits one idempotent SQL script.
 *
 *   ./scripts/seed.sh            # writes supabase/seed/seed.sql
 *
 * Design rules this follows:
 *
 *  - **Deterministic ids.** Every row's uuid is hashed from a stable natural
 *    key, so re-running produces the same ids and `on conflict do update`
 *    updates rather than duplicating (§42, §68).
 *
 *  - **No invented business data.** Nothing is synthesised here. The only rows
 *    this file creates that are not in src/data are the Sales Bible slots and
 *    the competency framework, and those are written with `value = null`,
 *    which is what the UI reads as "Admin content required" (§78, §43).
 *
 *  - **Content only.** No users, no progress, no assessment attempts. Those
 *    belong to real people using the system; seeding them would be the fake
 *    data §71 rules out.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { categories } from '@/data/categories'
import { materials } from '@/data/materials'
import { learningPaths } from '@/data/paths'
import { assessments } from '@/data/assessments'
import { trainingActivities } from '@/data/activities'
import { practiceScenarios } from '@/data/scenarios'
import { objections } from '@/data/objections'
import { quickReferenceCards } from '@/data/quickReference'
import { wordingPairs } from '@/data/wording'
import type { ContentBlock, Material } from '@/types'
import { banner, bool, enumArray, json, lit, num, stableUuid, textArray, upsert } from './sql'
import { COMPETENCIES, COMPETENCY_LEVELS } from './competencies'
import { SALES_BIBLE, STUB_MODULES } from './stubs'

/* ------------------------------------------------------------------ ids ---- */

const catId = (slug: string) => stableUuid(`category:${slug}`)
const modId = (slug: string) => stableUuid(`module:${slug}`)
const lessonId = (modSlug: string, index: number) => stableUuid(`lesson:${modSlug}:${index}`)
const blockId = (modSlug: string, li: number, bi: number) =>
  stableUuid(`block:${modSlug}:${li}:${bi}`)
const pathId = (slug: string) => stableUuid(`path:${slug}`)
const assessId = (slug: string) => stableUuid(`assessment:${slug}`)
const questionId = (aSlug: string, i: number) => stableUuid(`question:${aSlug}:${i}`)
const choiceId = (aSlug: string, qi: number, ci: number) =>
  stableUuid(`choice:${aSlug}:${qi}:${ci}`)

/** src/data references categories by their local id, e.g. 'cat-phone'. */
const catSlugByLocalId = new Map(categories.map((c) => [c.id, c.slug]))
/** ...and materials by 'mat-phone-etiquette'. */
const matSlugByLocalId = new Map(materials.map((m) => [m.id, m.slug]))

/**
 * Output is collected into named parts.
 *
 * The whole seed is 228 kB, which the Supabase SQL Editor refuses to save as a
 * snippet. Emitting it as several files that each stand on their own means it
 * can be pasted in pieces - and because every part is its own transaction, a
 * failure part-way leaves the earlier parts applied rather than needing the
 * lot re-run.
 *
 * Parts must stay in order: a module references a category, a lesson a module,
 * a path item a module. The numbering in the filename is that order.
 */
interface Part {
  slug: string
  title: string
  lines: string[]
}

const parts: Part[] = []
let current: Part = { slug: '00-preamble', title: 'Preamble', lines: [] }
parts.push(current)

const w = (s: string) => current.lines.push(s)

/** Opens a new part. Everything written after this lands in it. */
function part(slug: string, title: string): void {
  current = { slug, title, lines: [] }
  parts.push(current)
  w(banner(title))
}

/* --------------------------------------------------------------- preamble -- */

w(`-- ===========================================================================
-- KCO LMS - content seed
--
-- GENERATED by supabase/seed/generate.ts. Do not edit.
-- Regenerate with:  ./scripts/seed.sh
--
-- Safe to run repeatedly: every row has a deterministic id and is upserted,
-- so a second run updates content in place and creates no duplicates.
--
-- Seeds CONTENT ONLY. No users, no progress, no assessment attempts - those
-- are created by people using the system.
--
-- Source: the training documents transcribed into src/data/. Where a document
-- refers to information it does not supply (product specifications, package
-- prices, flavours), the row is seeded with a null value so the UI shows
-- "Admin content required" instead of an invented figure.
-- ===========================================================================
`)

/* ------------------------------------------------------------- categories -- */

part('01-categories', 'Categories')
w(
  upsert(
    'categories',
    ['id', 'slug', 'name', 'description', 'accent', 'icon', 'sort_order'],
    categories.map((c, i) => [
      lit(catId(c.slug)),
      lit(c.slug),
      lit(c.name),
      lit(c.description),
      lit(c.accent),
      lit(c.icon),
      num(i),
    ]),
  ),
)

/* ---------------------------------------------------------------- modules -- */

/**
 * A module's lessons live in `material.sections`, and each section's blocks
 * become content_blocks rows. The three-level walk happens once, here, so the
 * ordering of lessons and blocks in the database matches the order they were
 * authored in - which is the order they are read in.
 */
function emitModule(m: Material, moduleNumber: number) {
  const categorySlug = catSlugByLocalId.get(m.categoryId)

  w(
    upsert(
      'modules',
      [
        'id',
        'slug',
        'title',
        'description',
        'category_id',
        'module_number',
        'status',
        'difficulty',
        'duration_minutes',
        'audience',
        'teams',
        'tags',
        'needs_claim_review',
        'published_at',
      ],
      [
        [
          lit(modId(m.slug)),
          lit(m.slug),
          lit(m.title),
          lit(m.description),
          categorySlug ? lit(catId(categorySlug)) : 'null',
          num(moduleNumber),
          lit(m.status),
          lit(m.difficulty),
          num(m.duration),
          enumArray(m.audience, 'user_role'),
          textArray(m.teams),
          textArray(m.tags),
          bool(Boolean(m.needsClaimReview)),
          // The check constraint requires a timestamp on anything published.
          m.status === 'published' ? 'now()' : 'null',
        ],
      ],
    ),
  )

  if (m.sections.length === 0) return

  w(
    upsert(
      'lessons',
      ['id', 'module_id', 'title', 'summary', 'sort_order', 'status'],
      m.sections.map((s, i) => [
        lit(lessonId(m.slug, i)),
        lit(modId(m.slug)),
        lit(s.title),
        lit(s.summary ?? ''),
        num(i),
        lit('published'),
      ]),
    ),
  )

  const blockRows: string[][] = []
  m.sections.forEach((s, li) => {
    s.blocks.forEach((b, bi) => {
      const { id: _dropped, type, ...data } = b as ContentBlock & { id: string }
      blockRows.push([
        lit(blockId(m.slug, li, bi)),
        lit(lessonId(m.slug, li)),
        lit(type),
        json(data),
        num(bi),
      ])
    })
  })

  if (blockRows.length > 0) {
    w(upsert('content_blocks', ['id', 'lesson_id', 'type', 'data', 'sort_order'], blockRows))
  }
}

/*
 * A part per module rather than one for all of them. The transcribed content
 * is 231 blocks of JSON; kept together they make a 119 kB file, which is what
 * the SQL Editor chokes on. Per module each file is 5-25 kB.
 */
materials.forEach((m, i) => {
  part(
    `02-${String(i + 1).padStart(2, '0')}-module-${m.slug}`,
    `Module ${m.moduleNumber}: ${m.title}`,
  )
  emitModule(m, m.moduleNumber)
})

/**
 * The remaining modules from the §43 outline.
 *
 * The source documents for these were not available, so they are created as
 * empty drafts with a single explanatory lesson rather than being filled with
 * plausible-sounding training copy. An admin completes them through the CMS;
 * until then they stay in draft and no learner sees them.
 */
part('03-module-stubs', 'Modules awaiting source content - created as drafts, never invented')

// Fail at generation time rather than emitting SQL that dies on a foreign key
// halfway through applying. A typo in a category slug should be a loud error
// here, with the offending value named.
const knownCategorySlugs = new Set(categories.map((c) => c.slug))
STUB_MODULES.forEach((s) => {
  if (!knownCategorySlugs.has(s.categorySlug)) {
    throw new Error(
      `Stub module "${s.slug}" references unknown category "${s.categorySlug}". ` +
        `Known slugs: ${[...knownCategorySlugs].join(', ')}`,
    )
  }
})

STUB_MODULES.forEach((s) => {
  w(
    upsert(
      'modules',
      [
        'id',
        'slug',
        'title',
        'description',
        'category_id',
        'module_number',
        'status',
        'difficulty',
        'duration_minutes',
        'audience',
        'tags',
      ],
      [
        [
          lit(modId(s.slug)),
          lit(s.slug),
          lit(s.title),
          lit(s.description),
          lit(catId(s.categorySlug)),
          num(s.moduleNumber),
          lit('draft'),
          lit('foundation'),
          num(0),
          enumArray(['sales'], 'user_role'),
          textArray(['awaiting-content']),
        ],
      ],
    ),
  )

  w(
    upsert(
      'lessons',
      ['id', 'module_id', 'title', 'summary', 'sort_order', 'status'],
      [
        [
          lit(lessonId(s.slug, 0)),
          lit(modId(s.slug)),
          lit('Admin content required'),
          lit('This module is part of the training outline but its source document has not been supplied.'),
          num(0),
          lit('draft'),
        ],
      ],
    ),
  )

  w(
    upsert(
      'content_blocks',
      ['id', 'lesson_id', 'type', 'data', 'sort_order'],
      [
        [
          lit(blockId(s.slug, 0, 0)),
          lit(lessonId(s.slug, 0)),
          lit('callout'),
          json({
            variant: 'warning',
            title: 'Admin content required',
            text: s.awaiting,
          }),
          num(0),
        ],
      ],
    ),
  )
})

/* ---------------------------------------------------------- learning paths -- */

part('04-learning-paths', 'Learning paths')
w(
  upsert(
    'learning_paths',
    ['id', 'slug', 'title', 'description', 'audience', 'accent', 'status', 'published_at'],
    learningPaths.map((p) => [
      lit(pathId(p.slug)),
      lit(p.slug),
      lit(p.title),
      lit(p.description),
      enumArray(p.audience, 'user_role'),
      lit(p.accent),
      lit(p.status),
      p.status === 'published' ? 'now()' : 'null',
    ]),
  ),
)

/**
 * Path items are deleted and reinserted rather than upserted.
 *
 * Their identity is (path, position), and reordering a path changes which
 * module sits at which position. Upserting by id would leave a stale item
 * behind whenever a step is removed, so the set is replaced wholesale.
 */
w(`-- Replace path items wholesale: their identity is position, not content.
delete from public.learning_path_items
 where path_id in (${learningPaths.map((p) => lit(pathId(p.slug))).join(', ')});
`)

const pathItemRows: string[][] = []
learningPaths.forEach((p) => {
  p.materialIds.forEach((localId, i) => {
    const slug = matSlugByLocalId.get(localId)
    if (!slug) {
      // A path referencing a material that no longer exists is a content bug,
      // not something to paper over with a null row.
      throw new Error(`Learning path "${p.slug}" references unknown material "${localId}"`)
    }
    pathItemRows.push([
      lit(stableUuid(`path-item:${p.slug}:${i}`)),
      lit(pathId(p.slug)),
      lit(modId(slug)),
      num(i),
      bool(true),
    ])
  })
})
w(
  upsert(
    'learning_path_items',
    ['id', 'path_id', 'module_id', 'sort_order', 'required'],
    pathItemRows,
  ),
)

/* ------------------------------------------------------------ assessments -- */

part('05-assessments', 'Assessments, questions and choices')
w(
  upsert(
    'assessments',
    [
      'id',
      'slug',
      'title',
      'description',
      'module_id',
      'passing_score',
      'time_limit_minutes',
      'attempts_allowed',
      'status',
      'published_at',
    ],
    assessments.map((a) => {
      const modSlug = a.materialId ? matSlugByLocalId.get(a.materialId) : undefined
      return [
        lit(assessId(a.slug)),
        lit(a.slug),
        lit(a.title),
        lit(a.description),
        modSlug ? lit(modId(modSlug)) : 'null',
        num(a.passingScore),
        num(a.timeLimitMinutes ?? null),
        num(a.attemptsAllowed),
        lit(a.status),
        a.status === 'published' ? 'now()' : 'null',
      ]
    }),
  ),
)

w(
  upsert(
    'assessment_questions',
    ['id', 'assessment_id', 'type', 'prompt', 'explanation', 'points', 'sort_order'],
    assessments.flatMap((a) =>
      a.questions.map((q, i) => [
        lit(questionId(a.slug, i)),
        lit(assessId(a.slug)),
        // The authored bank is all single-answer; true/false is detected so it
        // renders with the right control instead of a two-option radio list.
        lit(isTrueFalse(q.options) ? 'true_false' : 'multiple_choice'),
        lit(q.prompt),
        lit(q.explanation),
        num(q.points),
        num(i),
      ]),
    ),
  ),
)

w(
  upsert(
    'assessment_choices',
    ['id', 'question_id', 'text', 'is_correct', 'sort_order'],
    assessments.flatMap((a) =>
      a.questions.flatMap((q, qi) =>
        q.options.map((opt, ci) => [
          lit(choiceId(a.slug, qi, ci)),
          lit(questionId(a.slug, qi)),
          lit(opt),
          bool(ci === q.answerIndex),
          num(ci),
        ]),
      ),
    ),
  ),
)

function isTrueFalse(options: string[]): boolean {
  if (options.length !== 2) return false
  const set = options.map((o) => o.trim().toLowerCase()).sort()
  return (
    (set[0] === 'false' && set[1] === 'true') ||
    (set[0] === 'hindi' && set[1] === 'oo') ||
    (set[0] === 'mali' && set[1] === 'tama')
  )
}

/* ------------------------------------------------------ training activities -- */

part('06-training-activities', 'Training activities')
w(
  upsert(
    'training_activities',
    [
      'id',
      'slug',
      'title',
      'objective',
      'duration_minutes',
      'participants',
      'difficulty',
      'instructions',
      'facilitator_notes',
      'expected_outcome',
      'materials',
      'tags',
      'status',
    ],
    trainingActivities.map((a) => [
      lit(stableUuid(`activity:${a.slug}`)),
      lit(a.slug),
      lit(a.title),
      lit(a.objective),
      num(a.durationMinutes),
      lit(a.participants),
      lit(a.difficulty),
      textArray(a.instructions),
      textArray(a.facilitatorNotes),
      lit(a.expectedOutcome),
      textArray(a.materials ?? []),
      textArray(a.tags),
      lit(a.status),
    ]),
  ),
)

/* ------------------------------------------------------- practice scenarios -- */

part('07-practice-scenarios', 'Practice scenarios')
w(
  upsert(
    'practice_scenarios',
    [
      'id',
      'slug',
      'title',
      'channel',
      'personality',
      'difficulty',
      'setup',
      'goal',
      'turns',
      'coaching',
      'status',
    ],
    practiceScenarios.map((s) => [
      lit(stableUuid(`scenario:${s.slug}`)),
      lit(s.slug),
      lit(s.title),
      lit(s.channel),
      lit(s.personality),
      lit(s.difficulty),
      lit(s.setup),
      lit(s.goal),
      json(s.turns),
      textArray(s.coaching),
      lit('published'),
    ]),
  ),
)

/* --------------------------------------------------------------- objections -- */

part('08-objections', 'Objection handling library')
w(
  upsert(
    'objections',
    [
      'id',
      'slug',
      'objection',
      'translation',
      'category',
      'frequency',
      'acknowledge',
      'clarify',
      'address',
      'close',
      'pitfalls',
      'claim_sensitive',
      'status',
    ],
    objections.map((o) => [
      lit(stableUuid(`objection:${o.slug}`)),
      lit(o.slug),
      lit(o.objection),
      lit(o.translation),
      lit(o.category),
      lit(o.frequency),
      lit(o.acknowledge),
      lit(o.clarify),
      lit(o.address),
      lit(o.close),
      textArray(o.pitfalls),
      bool(o.claimSensitive),
      lit('published'),
    ]),
  ),
)

/* ------------------------------------------------------------------ scripts -- */

/**
 * The script library (§24) is DERIVED, not authored separately.
 *
 * Scripts already exist in the source material as `script` blocks inside
 * lessons and quick-reference cards. Extracting them into their own table
 * makes them searchable, copyable and admin-editable as §24 requires, without
 * creating a second copy of the same words that could drift from the lesson
 * it came from. `source_ref` in the notes records where each one came from.
 */
interface DerivedScript {
  slug: string
  title: string
  kind: 'phone' | 'chat' | 'closing' | 'qualification' | 'follow-up' | 'complaint' | 'wording'
  channel: 'phone' | 'chat' | 'both'
  situation: string
  language: 'en' | 'fil' | 'mixed'
  lines: string[]
  notes: string
  tags: string[]
}

/** Classifies a script by the words in its label and the context it sits in. */
function classify(label: string, context: string): { kind: DerivedScript['kind']; channel: DerivedScript['channel'] } {
  const h = `${label} ${context}`.toLowerCase()
  if (/complaint|angry|damaged|refund|escalat/.test(h)) return { kind: 'complaint', channel: 'both' }
  if (/clos|order|confirm|reserve/.test(h)) return { kind: 'closing', channel: 'both' }
  if (/follow.?up|seen|reply|balik/.test(h)) return { kind: 'follow-up', channel: 'both' }
  if (/qualif|discover|question|need/.test(h)) return { kind: 'qualification', channel: 'both' }
  if (/chat|messenger|message/.test(h)) return { kind: 'chat', channel: 'chat' }
  if (/phone|call|hold|ring/.test(h)) return { kind: 'phone', channel: 'phone' }
  return { kind: 'phone', channel: 'both' }
}

const derived: DerivedScript[] = []
const seenScriptSlugs = new Set<string>()

function addScript(
  labelRaw: string,
  context: string,
  language: 'en' | 'fil' | 'mixed',
  lines: string[],
  source: string,
  tags: string[],
) {
  const label = labelRaw.trim() || 'Script'
  const base = `${context}-${label}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)

  // Two lessons can carry a script under the same label; keep both, since the
  // wording differs, but give them distinct slugs.
  let slug = base
  let n = 2
  while (seenScriptSlugs.has(slug)) slug = `${base}-${n++}`
  seenScriptSlugs.add(slug)

  const { kind, channel } = classify(label, context)
  derived.push({
    slug,
    title: label,
    kind,
    channel,
    situation: context,
    language,
    lines,
    notes: `Source: ${source}`,
    tags,
  })
}

materials.forEach((m) => {
  m.sections.forEach((s) => {
    s.blocks.forEach((b) => {
      if (b.type !== 'script') return
      addScript(b.label ?? s.title, s.title, b.language, b.lines, `${m.title} - ${s.title}`, m.tags)
    })
  })
})

quickReferenceCards.forEach((c) => {
  c.blocks.forEach((b) => {
    if (b.type !== 'script') return
    addScript(b.label ?? c.title, c.title, b.language, b.lines, `Quick Reference - ${c.title}`, [c.kind])
  })
})

part('09-scripts', `Script library - ${derived.length} scripts extracted from the source material`)
w(
  upsert(
    'scripts',
    ['id', 'slug', 'title', 'kind', 'channel', 'situation', 'language', 'lines', 'notes', 'tags', 'sort_order', 'status'],
    derived.map((s, i) => [
      lit(stableUuid(`script:${s.slug}`)),
      lit(s.slug),
      lit(s.title),
      lit(s.kind),
      lit(s.channel),
      lit(s.situation),
      lit(s.language),
      textArray(s.lines),
      lit(s.notes),
      textArray(s.tags),
      num(i),
      lit('published'),
    ]),
  ),
)

part('10-wording', 'Professional wording - avoid / use pairs')
w(
  upsert(
    'wording_pairs',
    ['id', 'avoid', 'use', 'context', 'note', 'tags', 'sort_order', 'status'],
    wordingPairs.map((p, i) => [
      lit(stableUuid(`wording:${p.id}`)),
      lit(p.avoid),
      lit(p.use),
      lit(p.context),
      lit(p.note ?? ''),
      textArray(p.tags),
      num(i),
      lit('published'),
    ]),
  ),
)

/* ---------------------------------------------------------- quick reference -- */

part('11-quick-reference', 'Quick reference cards')
w(
  upsert(
    'quick_reference_items',
    ['id', 'slug', 'title', 'kicker', 'kind', 'channel', 'blocks', 'sort_order', 'status'],
    quickReferenceCards.map((q, i) => [
      lit(stableUuid(`qr:${q.slug}`)),
      lit(q.slug),
      lit(q.title),
      lit(q.kicker),
      lit(q.kind),
      lit(q.channel),
      json(q.blocks),
      num(i),
      lit('published'),
    ]),
  ),
)

/* ------------------------------------------------------------- competencies -- */

part('12-competencies', 'Competency framework - the documented 1-5 scale')
w(
  upsert(
    'competency_levels',
    ['level', 'label', 'description'],
    COMPETENCY_LEVELS.map((l) => [num(l.level), lit(l.label), lit(l.description)]),
    'level',
  ),
)

w(
  upsert(
    'competencies',
    ['id', 'slug', 'name', 'definition', 'cluster', 'behavioral_indicators', 'sort_order', 'status'],
    COMPETENCIES.map((c, i) => [
      lit(stableUuid(`competency:${c.slug}`)),
      lit(c.slug),
      lit(c.name),
      lit(c.definition),
      lit(c.cluster),
      textArray(c.indicators),
      num(i),
      lit('published'),
    ]),
  ),
)

/* --------------------------------------------------------------- sales bible -- */

part('13-sales-bible', 'Sales Bible - structure seeded, values left for management')
w(
  upsert(
    'sales_bible_sections',
    ['id', 'slug', 'title', 'summary', 'sort_order'],
    SALES_BIBLE.map((s, i) => [
      lit(stableUuid(`bible-section:${s.slug}`)),
      lit(s.slug),
      lit(s.title),
      lit(s.summary),
      num(i),
    ]),
  ),
)

w(
  upsert(
    'sales_bible_entries',
    ['id', 'section_id', 'label', 'value', 'detail', 'verified', 'requires_approval', 'sort_order'],
    SALES_BIBLE.flatMap((s) =>
      s.entries.map((e, i) => [
        lit(stableUuid(`bible-entry:${s.slug}:${e.label}`)),
        lit(stableUuid(`bible-section:${s.slug}`)),
        lit(e.label),
        // null, never a plausible placeholder. This is the field the UI reads
        // to decide between showing a value and showing "not yet configured".
        e.value === undefined ? 'null' : lit(e.value),
        lit(e.detail ?? ''),
        bool(e.value !== undefined),
        bool(Boolean(e.requiresApproval)),
        num(i),
      ]),
    ),
  ),
)

/* ------------------------------------------------------------ verification -- */

part('99-verify', 'Seed verification (§68)')

w(`-- Every count below must be non-zero, and every integrity check must be 0.
select 'categories' as table, count(*) from public.categories
union all select 'modules', count(*) from public.modules
union all select 'lessons', count(*) from public.lessons
union all select 'content_blocks', count(*) from public.content_blocks
union all select 'learning_paths', count(*) from public.learning_paths
union all select 'learning_path_items', count(*) from public.learning_path_items
union all select 'assessments', count(*) from public.assessments
union all select 'assessment_questions', count(*) from public.assessment_questions
union all select 'assessment_choices', count(*) from public.assessment_choices
union all select 'training_activities', count(*) from public.training_activities
union all select 'practice_scenarios', count(*) from public.practice_scenarios
union all select 'objections', count(*) from public.objections
union all select 'scripts', count(*) from public.scripts
union all select 'wording_pairs', count(*) from public.wording_pairs
union all select 'quick_reference_items', count(*) from public.quick_reference_items
union all select 'competencies', count(*) from public.competencies
union all select 'sales_bible_entries', count(*) from public.sales_bible_entries
order by 1;

select 'lessons with no module' as check, count(*) from public.lessons l
  left join public.modules m on m.id = l.module_id where m.id is null
union all
select 'blocks with no lesson', count(*) from public.content_blocks b
  left join public.lessons l on l.id = b.lesson_id where l.id is null
union all
select 'path items with no module', count(*) from public.learning_path_items i
  left join public.modules m on m.id = i.module_id
  where i.module_id is not null and m.id is null
union all
select 'questions with no correct choice', count(*) from public.assessment_questions q
  where q.type <> 'short_answer'
    and not exists (select 1 from public.assessment_choices c
                     where c.question_id = q.id and c.is_correct)
union all
select 'published modules with no lessons', count(*) from public.modules m
  where m.status = 'published'
    and not exists (select 1 from public.lessons l where l.module_id = m.id)
union all
select 'sales bible entries with unverified values', count(*)
  from public.sales_bible_entries where value is not null and not verified;
`)

/* ----------------------------------------------------------------- output -- */

const preamble = parts[0]!.lines.join('\n')

/**
 * A part, ready to paste.
 *
 * Wrapped in its own transaction so a failure rolls back only that part, and
 * carrying the preamble header so a file opened on its own still says what it
 * is and how to regenerate it. The verification part is not wrapped - it only
 * reads.
 */
function render(p: Part, index: number, total: number): string {
  const header = `${preamble}
-- ---------------------------------------------------------------------------
-- PART ${index} OF ${total}: ${p.title}
--
-- Run the parts in filename order. Each is idempotent on its own, so a part
-- can be re-run safely; running them out of order will fail on a foreign key.
-- ---------------------------------------------------------------------------
`
  const body = p.lines.join('\n')
  const readOnly = p.slug === '99-verify'

  return readOnly ? `${header}\n${body}\n` : `${header}\nbegin;\n${body}\ncommit;\n`
}

const outDirArg = process.argv.indexOf('--out-dir')

if (outDirArg !== -1) {
  const dir = process.argv[outDirArg + 1]
  if (!dir) throw new Error('--out-dir needs a path')

  const content = parts.slice(1)
  mkdirSync(dir, { recursive: true })

  const written = content.map((p, i) => {
    const file = join(dir, `${p.slug}.sql`)
    const sql = render(p, i + 1, content.length)
    writeFileSync(file, sql)
    return { file, bytes: Buffer.byteLength(sql), lines: sql.split('\n').length }
  })

  // A manifest, so it is obvious what to paste and in what order.
  const manifest = [
    '# Seed parts',
    '',
    'GENERATED by supabase/seed/generate.ts - do not edit.',
    'Regenerate with `./scripts/seed.sh`.',
    '',
    'The full seed is too large for the Supabase SQL Editor to save as one',
    'snippet, so it is emitted in parts. Paste and run them in this order:',
    '',
    '| # | File | Size |',
    '| - | ---- | ---- |',
    ...written.map(
      (w, i) => `| ${i + 1} | \`${w.file.split('/').pop()}\` | ${Math.ceil(w.bytes / 1024)} kB |`,
    ),
    '',
    'Every part is idempotent, so re-running one is safe. Running them out of',
    'order will fail on a foreign key rather than corrupt anything.',
    '',
  ].join('\n')
  writeFileSync(join(dir, 'README.md'), manifest)

  written.forEach((w) => {
    process.stderr.write(`  ${w.file}  ${String(Math.ceil(w.bytes / 1024)).padStart(4)} kB\n`)
  })
  process.stderr.write(`  ${join(dir, 'README.md')}\n`)
} else {
  // Single-file output, for psql and the verification scripts.
  const all = parts
    .slice(1)
    .map((p) => p.lines.join('\n'))
    .join('\n')
  process.stdout.write(`${preamble}\nbegin;\n${all}\ncommit;\n`)
}
