-- ===========================================================================
-- KCO LMS schema - PART 2 OF 7
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;


-- ---------------------------------------------------------------- attempts --

create table public.assessment_attempts (
  id             uuid primary key default gen_random_uuid(),
  assessment_id  uuid not null references public.assessments (id) on delete cascade,
  user_id        uuid not null references public.profiles (id) on delete cascade,

  attempt_number int not null check (attempt_number > 0),
  status         public.attempt_status not null default 'in_progress',

  -- Written only by submit_assessment_attempt(); see the policy in 0007 that
  -- prevents a learner from setting their own score.
  score          int,
  max_score      int,
  percentage     numeric(5,2),
  passed         boolean,

  started_at     timestamptz not null default now(),
  submitted_at   timestamptz,

  constraint attempts_unique_number unique (user_id, assessment_id, attempt_number),
  constraint attempts_submitted_is_scored check (
    status <> 'submitted'
    or (score is not null and percentage is not null and passed is not null and submitted_at is not null)
  )
);

create index attempts_user_idx       on public.assessment_attempts (user_id, submitted_at desc);
create index attempts_assessment_idx on public.assessment_attempts (assessment_id);
create index attempts_status_idx     on public.assessment_attempts (status);

-- ----------------------------------------------------------------- answers --

create table public.assessment_answers (
  id           uuid primary key default gen_random_uuid(),
  attempt_id   uuid not null references public.assessment_attempts (id) on delete cascade,
  question_id  uuid not null references public.assessment_questions (id) on delete cascade,

  -- Choice ids for choice questions; free text for short answers.
  choice_ids   uuid[] not null default '{}',
  text_answer  text,

  -- Filled in by the scoring function at submission, not by the client.
  is_correct   boolean,
  points_awarded int not null default 0,

  answered_at  timestamptz not null default now(),

  constraint answers_unique_question unique (attempt_id, question_id)
);

create index assessment_answers_attempt_idx on public.assessment_answers (attempt_id);

-- ---------------------------------------------------------------------------
-- Scoring.
--
-- Runs SECURITY DEFINER so it can read is_correct, which the calling learner
-- cannot. This is the only path by which a score is ever written: the RLS
-- policy in 0007 forbids a client from updating score/passed directly, so a
-- learner cannot award themselves a pass.
-- ---------------------------------------------------------------------------
create or replace function public.submit_assessment_attempt(p_attempt_id uuid)
returns public.assessment_attempts
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_attempt public.assessment_attempts;
  v_pass    int;
  v_total   int := 0;
  v_earned  int := 0;
  v_pct     numeric(5,2);
  r         record;
begin
  select * into v_attempt from public.assessment_attempts where id = p_attempt_id for update;

  if v_attempt is null then
    raise exception 'Attempt % not found', p_attempt_id;
  end if;

  -- An attempt belongs to exactly one person and only they may submit it.
  if v_attempt.user_id <> auth.uid() then
    raise exception 'You cannot submit an attempt that is not yours';
  end if;

  if v_attempt.status <> 'in_progress' then
    raise exception 'This attempt has already been submitted';
  end if;

  select passing_score into v_pass from public.assessments where id = v_attempt.assessment_id;

  -- Score every question on the assessment, not merely the answered ones, so
  -- skipping a question costs its points rather than shrinking the denominator.
  for r in
    select q.id, q.type, q.points, q.correct_text,
           a.choice_ids, a.text_answer
      from public.assessment_questions q
      left join public.assessment_answers a
        on a.question_id = q.id and a.attempt_id = p_attempt_id
     where q.assessment_id = v_attempt.assessment_id
  loop
    v_total := v_total + r.points;

    declare
      v_ok boolean := false;
      v_correct uuid[];
    begin
      if r.type = 'short_answer' then
        v_ok := r.text_answer is not null
                and lower(trim(r.text_answer)) = lower(trim(r.correct_text));
      else
        select coalesce(array_agg(c.id order by c.id), '{}')
          into v_correct
          from public.assessment_choices c
         where c.question_id = r.id and c.is_correct;

        -- Set equality: every correct choice selected and nothing else. For
        -- multiple_select this means partial credit is not awarded, which
        -- matches how the results screen reports a question as right or wrong.
        v_ok := v_correct <> '{}'
                and (select coalesce(array_agg(x order by x), '{}')
                       from unnest(coalesce(r.choice_ids, '{}')) x) = v_correct;
      end if;

      if v_ok then
        v_earned := v_earned + r.points;
      end if;

      -- Record the verdict so the review screen does not re-derive it.
      update public.assessment_answers
         set is_correct = v_ok,
             points_awarded = case when v_ok then r.points else 0 end
       where attempt_id = p_attempt_id and question_id = r.id;
    end;
  end loop;

  v_pct := case when v_total > 0 then round((v_earned::numeric / v_total) * 100, 2) else 0 end;

  update public.assessment_attempts
     set status = 'submitted',
         score = v_earned,
         max_score = v_total,
         percentage = v_pct,
         passed = v_pct >= v_pass,
         submitted_at = now()
   where id = p_attempt_id
   returning * into v_attempt;

  return v_attempt;
end;
$$;

-- Opens an attempt, allocating the next attempt number and refusing to exceed
-- the configured limit. Server-side because the limit is a rule, not a hint.
create or replace function public.start_assessment_attempt(p_assessment_id uuid)
returns public.assessment_attempts
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_allowed int;
  v_status  public.content_status;
  v_used    int;
  v_attempt public.assessment_attempts;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select attempts_allowed, status into v_allowed, v_status
    from public.assessments where id = p_assessment_id;

  if v_status is null then
    raise exception 'Assessment not found';
  end if;

  -- Admins may open a draft to test it; learners may not.
  if v_status <> 'published' and not public.is_admin() then
    raise exception 'This assessment is not available';
  end if;

  select count(*) into v_used
    from public.assessment_attempts
   where user_id = auth.uid() and assessment_id = p_assessment_id
     and status = 'submitted';

  if v_allowed > 0 and v_used >= v_allowed then
    raise exception 'You have used all % attempts for this assessment', v_allowed;
  end if;

  -- Reuse an abandoned in-progress attempt rather than stacking up rows when
  -- a learner closes the tab and comes back.
  select * into v_attempt
    from public.assessment_attempts
   where user_id = auth.uid() and assessment_id = p_assessment_id and status = 'in_progress'
   order by started_at desc limit 1;

  if v_attempt.id is not null then
    return v_attempt;
  end if;

  insert into public.assessment_attempts (assessment_id, user_id, attempt_number)
  values (p_assessment_id, auth.uid(), v_used + 1)
  returning * into v_attempt;

  return v_attempt;
end;
$$;


-- ###########################################################################
-- ## 20260910090400_training_and_resources.sql
-- ###########################################################################

-- ============================================================================
-- 0005 - Training activities, practice scenarios, and the sales resource
--        libraries (objections, scripts, wording, quick reference, Sales Bible,
--        competencies).
--
-- These are all admin-authored reference content with the same lifecycle as a
-- module, so they share the content_status enum and the published/draft rules.
-- ============================================================================

-- ----------------------------------------------------- training activities --

create table public.training_activities (
  id               uuid primary key default gen_random_uuid(),
  slug             text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title            text not null check (length(trim(title)) between 1 and 160),
  objective        text not null default '',
  description      text not null default '',
  duration_minutes int  not null default 15 check (duration_minutes > 0),
  participants     text not null default '',
  difficulty       public.difficulty not null default 'foundation',
  instructions     text[] not null default '{}',
  facilitator_notes text[] not null default '{}',
  expected_outcome text not null default '',
  materials        text[] not null default '{}',
  tags             text[] not null default '{}',
  category_id      uuid references public.categories (id) on delete set null,
  status           public.content_status not null default 'draft',
  created_by       uuid references public.profiles (id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index training_activities_status_idx on public.training_activities (status);
create index training_activities_tags_idx   on public.training_activities using gin (tags);

create trigger training_activities_set_updated_at before update on public.training_activities
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------ practice scenarios --

-- §21: seeded with scripted branches today. `turns` is jsonb precisely so an
-- AI roleplay engine can later generate turns at runtime without a migration -
-- the table shape does not encode the assumption that they are pre-written.
create table public.practice_scenarios (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title       text not null,
  channel     text not null check (channel in ('phone','chat','objection')),
  personality text not null,
  difficulty  public.difficulty not null default 'foundation',
  setup       text not null default '',
  goal        text not null default '',
  turns       jsonb not null default '[]'::jsonb,
  coaching    text[] not null default '{}',
  status      public.content_status not null default 'draft',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index practice_scenarios_status_idx on public.practice_scenarios (status);

create trigger practice_scenarios_set_updated_at before update on public.practice_scenarios
  for each row execute function public.set_updated_at();

-- Records a run so "practice regular" progress and admin reporting have data.
create table public.scenario_runs (
  id          uuid primary key default gen_random_uuid(),
  scenario_id uuid not null references public.practice_scenarios (id) on delete cascade,
  user_id     uuid not null references public.profiles (id) on delete cascade,
  best_count  int not null default 0,
  turn_count  int not null default 0,
  completed_at timestamptz not null default now()
);

create index scenario_runs_user_idx on public.scenario_runs (user_id, completed_at desc);

-- --------------------------------------------------------------- objections --

create table public.objections (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  objection   text not null,
  -- The concern underneath the words - the thing the rep actually answers.
  translation text not null default '',
  category    text not null default 'price'
                check (category in ('price','risk','capability','competition','capital','timing','market')),
  frequency   text not null default 'medium'
                check (frequency in ('very-high','high','medium','low')),
  difficulty  public.difficulty not null default 'foundation',

  -- A.C.A.C. (§23). Stored as four columns rather than one blob because the
  -- resource page renders them as four labelled steps and admins edit them
  -- individually.
  acknowledge text not null default '',
  clarify     text not null default '',
  address     text not null default '',
  close       text not null default '',

  pitfalls    text[] not null default '{}',
  notes       text not null default '',
  -- §44: the answer touches earnings/ROI and must stay illustrative.
  claim_sensitive boolean not null default false,
  status      public.content_status not null default 'published',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index objections_category_idx on public.objections (category);
create index objections_status_idx   on public.objections (status);
create index objections_trgm_idx     on public.objections using gin (objection extensions.gin_trgm_ops);

create trigger objections_set_updated_at before update on public.objections
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ scripts --

-- §24: scripts live in the database, never inside a React component, so an
-- admin can fix wording without a deploy.
create table public.scripts (
  id         uuid primary key default gen_random_uuid(),
  slug       text not null unique,
  title      text not null,
  kind       text not null check (kind in
               ('phone','chat','closing','qualification','follow-up','complaint','wording')),
  channel    text not null default 'both' check (channel in ('phone','chat','both')),
  situation  text not null default '',
  language   text not null default 'mixed' check (language in ('en','fil','mixed')),
  lines      text[] not null default '{}',
  notes      text not null default '',
  tags       text[] not null default '{}',
  status     public.content_status not null default 'published',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index scripts_kind_idx   on public.scripts (kind, sort_order);
create index scripts_status_idx on public.scripts (status);
create index scripts_trgm_idx   on public.scripts using gin (title extensions.gin_trgm_ops);

create trigger scripts_set_updated_at before update on public.scripts
  for each row execute function public.set_updated_at();

-- Avoid/use pairs for professional wording.
create table public.wording_pairs (
  id      uuid primary key default gen_random_uuid(),
  avoid   text not null,
  use     text not null,
  context text not null default 'both' check (context in ('phone','chat','both')),
  note    text not null default '',
  tags    text[] not null default '{}',
  sort_order int not null default 0,
  status  public.content_status not null default 'published'
);

-- ---------------------------------------------------------- quick reference --

create table public.quick_reference_items (
  id         uuid primary key default gen_random_uuid(),
  slug       text not null unique,
  title      text not null,
  kicker     text not null default '',
  kind       text not null check (kind in ('script','formula','checklist','rule')),
  channel    text not null default 'both' check (channel in ('phone','chat','both')),
  -- Same block vocabulary as a lesson, so the renderer is shared.
  blocks     jsonb not null default '[]'::jsonb,
  sort_order int not null default 0,
  status     public.content_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index quick_reference_status_idx on public.quick_reference_items (status, sort_order);

create trigger quick_reference_set_updated_at before update on public.quick_reference_items
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------- sales bible --

-- §45/§78. Sections are seeded; entries are deliberately allowed to be empty
-- so the UI can show "Content not yet configured" instead of an invented price.
create table public.sales_bible_sections (
  id         uuid primary key default gen_random_uuid(),
  slug       text not null unique,
  title      text not null,
  summary    text not null default '',
  sort_order int not null default 0
);

create table public.sales_bible_entries (
  id         uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.sales_bible_sections (id) on delete cascade,
  label      text not null,
  -- Null (not empty string) means "no verified value has been supplied".
  -- The distinction matters: it is what the UI keys off to render the
  -- "Admin content required" state rather than a blank line (§78).
  value      text,
  detail     text not null default '',
  -- True once management has confirmed the value is accurate and publishable.
  verified   boolean not null default false,
  requires_approval boolean not null default false,
  sort_order int not null default 0,
  updated_by uuid references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now()
);

create index sales_bible_entries_section_idx on public.sales_bible_entries (section_id, sort_order);

create trigger sales_bible_entries_set_updated_at before update on public.sales_bible_entries
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------ competencies --

-- §31/§32: the 1-5 scale is a property of the framework, so the level labels
-- live in their own table rather than being hard-coded in the report page.
create table public.competency_levels (
  level int primary key check (level between 1 and 5),
  label text not null,
  description text not null default ''
);

create table public.competencies (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique,
  name        text not null,
  definition  text not null default '',
  cluster     text not null default 'sales'
                check (cluster in ('core','sales','chat','service')),
  behavioral_indicators text[] not null default '{}',
  sort_order  int not null default 0,
  status      public.content_status not null default 'published'
);

create table public.user_competencies (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.profiles (id) on delete cascade,
  competency_id uuid not null references public.competencies (id) on delete cascade,
  level         int  not null check (level between 1 and 5),
  assessed_by   uuid references public.profiles (id) on delete set null,
  note          text not null default '',
  assessed_at   timestamptz not null default now(),

  constraint user_competencies_unique unique (user_id, competency_id)
);

create index user_competencies_user_idx on public.user_competencies (user_id);


-- ###########################################################################
-- ## 20260910090500_delivery_and_tracking.sql
-- ###########################################################################

-- ============================================================================
-- 0006 - Assignments, progress, favourites, notifications, announcements,
--        and the activity log.
--
-- This is the layer that turns published content into a person's workload and
-- records what they did with it.
-- ============================================================================

-- ------------------------------------------------------------- assignments --

create table public.assignments (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles (id) on delete cascade,
  target_type  public.assignment_target not null,
  -- Polymorphic by design: a single "my assignments" query should not need a
  -- four-way union. Referential integrity is enforced by the trigger below,
  -- since a FK cannot point at four different tables.
  target_id    uuid not null,

  assigned_by  uuid references public.profiles (id) on delete set null,
  assigned_at  timestamptz not null default now(),
  due_at       timestamptz,
  status       public.assignment_status not null default 'not-started',
  note         text not null default '',
  completed_at timestamptz,

  -- Re-assigning the same thing to the same person should update, not stack.
  constraint assignments_unique_target unique (user_id, target_type, target_id)
);

create index assignments_user_idx    on public.assignments (user_id, status);
create index assignments_status_idx  on public.assignments (status);
create index assignments_due_idx     on public.assignments (due_at);
create index assignments_target_idx  on public.assignments (target_type, target_id);

-- Stands in for the foreign key a polymorphic column cannot have. Without it
-- an assignment could point at a deleted or non-existent module and the
-- learner's dashboard would show a row that opens nothing.
create or replace function public.assignments_check_target()
returns trigger
language plpgsql
as $$
declare
  v_exists boolean;
begin
  select case new.target_type
    when 'module'     then exists (select 1 from public.modules             where id = new.target_id)
    when 'path'       then exists (select 1 from public.learning_paths      where id = new.target_id)
    when 'assessment' then exists (select 1 from public.assessments         where id = new.target_id)
    when 'activity'   then exists (select 1 from public.training_activities where id = new.target_id)
  end into v_exists;

  if not v_exists then
    raise exception 'No % exists with id %', new.target_type, new.target_id;
  end if;
  return new;
end;
$$;

create trigger assignments_check_target
  before insert or update of target_type, target_id on public.assignments
  for each row execute function public.assignments_check_target();

-- Derives 'overdue' rather than storing it, so an assignment becomes overdue
-- by the passage of time instead of by a cron job that might not have run.
create or replace function public.assignment_effective_status(
  p_status public.assignment_status,
  p_due_at timestamptz
) returns public.assignment_status
language sql
immutable
as $$
  select case
    when p_status = 'completed' then 'completed'::public.assignment_status
    when p_due_at is not null and p_due_at < now() then 'overdue'::public.assignment_status
    else p_status
  end;
$$;

-- ---------------------------------------------------------------- progress --

-- One row per (learner, module). Lesson-level detail lives in
-- lesson_progress; this table carries the roll-up the dashboard reads.
create table public.module_progress (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  module_id  uuid not null references public.modules (id) on delete cascade,
  state      public.progress_state not null default 'not-started',
  started_at timestamptz,
  completed_at timestamptz,
  last_viewed_at timestamptz,
  last_viewed_lesson_id uuid references public.lessons (id) on delete set null,
  updated_at timestamptz not null default now(),

  constraint module_progress_unique unique (user_id, module_id)
);

create index module_progress_user_idx   on public.module_progress (user_id, state);
create index module_progress_module_idx on public.module_progress (module_id);

create trigger module_progress_set_updated_at before update on public.module_progress
  for each row execute function public.set_updated_at();

create table public.lesson_progress (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.profiles (id) on delete cascade,
  lesson_id    uuid not null references public.lessons (id) on delete cascade,
  module_id    uuid not null references public.modules (id) on delete cascade,
  completed    boolean not null default false,
  completed_at timestamptz,
  updated_at   timestamptz not null default now(),

  constraint lesson_progress_unique unique (user_id, lesson_id)
);

create index lesson_progress_user_module_idx on public.lesson_progress (user_id, module_id);

create trigger lesson_progress_set_updated_at before update on public.lesson_progress
  for each row execute function public.set_updated_at();

commit;
