-- ===========================================================================
-- KCO LMS schema - PART 5 OF 7
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;


-- The learner's own dashboard roll-up, mirroring admin_dashboard_stats().
create or replace function public.my_progress_summary()
returns jsonb
language sql
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'modules_total',     (select count(*) from public.modules where status = 'published'),
    'modules_completed', (select count(*) from public.module_progress
                           where user_id = auth.uid() and state = 'completed'),
    'modules_in_progress',(select count(*) from public.module_progress
                           where user_id = auth.uid() and state = 'in-progress'),
    'lessons_completed', (select count(*) from public.lesson_progress
                           where user_id = auth.uid() and completed),
    'assignments_open',  (select count(*) from public.assignments
                           where user_id = auth.uid() and status <> 'completed'),
    'assignments_overdue',(select count(*) from public.assignments
                           where user_id = auth.uid() and status <> 'completed'
                             and due_at is not null and due_at < now()),
    'attempts',          (select count(*) from public.assessment_attempts
                           where user_id = auth.uid() and status = 'submitted'),
    'avg_score',         coalesce((select round(avg(percentage),1) from public.assessment_attempts
                           where user_id = auth.uid() and status = 'submitted'), 0),
    'passed',            (select count(*) from public.assessment_attempts
                           where user_id = auth.uid() and status = 'submitted' and passed)
  );
$$;

-- --------------------------------------------------------------- grants ----

-- Same reasoning as 0007: strip the implicit PUBLIC grant, then hand EXECUTE
-- back to `authenticated` one function at a time. Anything omitted below is
-- reachable only from inside another definer function or a trigger.
revoke execute on all functions in schema public from public, anon;

grant execute on function public.admin_save_question(uuid, uuid, public.question_type, text, text, int, int, text, jsonb) to authenticated;
grant execute on function public.admin_assign(uuid[], public.assignment_target, uuid, timestamptz, text) to authenticated;
grant execute on function public.admin_set_user_role(uuid, public.user_role) to authenticated;
grant execute on function public.admin_set_user_status(uuid, public.user_status) to authenticated;
grant execute on function public.complete_lesson(uuid, boolean) to authenticated;
grant execute on function public.touch_module_view(uuid, uuid) to authenticated;
grant execute on function public.admin_dashboard_stats() to authenticated;
grant execute on function public.report_training_completion() to authenticated;
grant execute on function public.report_assessment_performance() to authenticated;
grant execute on function public.report_module_engagement() to authenticated;
grant execute on function public.my_progress_summary() to authenticated;
grant execute on function public.submit_assessment_attempt(uuid) to authenticated;
grant execute on function public.start_assessment_attempt(uuid) to authenticated;
grant execute on function public.log_activity(text, text, uuid, text, jsonb) to authenticated;
grant execute on function public.touch_last_login() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_active_user() to authenticated;
grant execute on function public.assignment_effective_status(public.assignment_status, timestamptz) to authenticated;


-- ###########################################################################
-- ## 20260910090900_attempt_review.sql
-- ###########################################################################

-- ============================================================================
-- 0010 - Attempt review.
--
-- §17 requires the results screen to show which answers were right, which were
-- wrong, and the explanation - while §17 equally requires that none of that is
-- available before submission.
--
-- Those two rules cannot both be satisfied by a table grant: the answer key is
-- withheld from `authenticated` at the column level (0007), so there is no
-- query a learner can run that returns it. This function is the one controlled
-- exception. It is SECURITY DEFINER, and it releases the key only when all of
-- the following hold:
--
--   * the attempt belongs to the caller (or the caller is an admin),
--   * the attempt has actually been submitted, and
--   * the assessment has show_correct_answers = true.
--
-- Miss any one and it raises. The key is therefore reachable exactly once the
-- learner can no longer use it to answer.
-- ============================================================================

create or replace function public.attempt_review(p_attempt_id uuid)
returns table (
  question_id     uuid,
  prompt          text,
  type            public.question_type,
  points          int,
  sort_order      int,
  explanation     text,
  -- What the learner picked, and what was right.
  selected_choice_ids uuid[],
  correct_choice_ids  uuid[],
  text_answer     text,
  correct_text    text,
  is_correct      boolean,
  points_awarded  int
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_attempt public.assessment_attempts;
  v_reveal  boolean;
begin
  select * into v_attempt from public.assessment_attempts where id = p_attempt_id;

  if v_attempt.id is null then
    raise exception 'Attempt not found';
  end if;

  if v_attempt.user_id <> auth.uid() and not public.is_admin() then
    raise exception 'That attempt is not yours';
  end if;

  if v_attempt.status <> 'submitted' then
    raise exception 'This attempt has not been submitted yet';
  end if;

  select a.show_correct_answers into v_reveal
    from public.assessments a where a.id = v_attempt.assessment_id;

  -- An admin reviewing someone's attempt always sees the key; a learner sees
  -- it only if the assessment was configured to reveal it.
  v_reveal := coalesce(v_reveal, true) or public.is_admin();

  return query
  select
    q.id,
    q.prompt,
    q.type,
    q.points,
    q.sort_order,
    -- The explanation is part of the feedback, so it follows the same gate.
    case when v_reveal then q.explanation else '' end,
    coalesce(ans.choice_ids, '{}'),
    case
      when v_reveal then coalesce(
        (select array_agg(c.id order by c.sort_order)
           from public.assessment_choices c
          where c.question_id = q.id and c.is_correct),
        '{}')
      else '{}'
    end,
    ans.text_answer,
    case when v_reveal then q.correct_text end,
    -- Written by the scoring function at submission, so this is the verdict
    -- that produced the score rather than a re-derivation.
    ans.is_correct,
    coalesce(ans.points_awarded, 0)
  from public.assessment_questions q
  left join public.assessment_answers ans
    on ans.question_id = q.id and ans.attempt_id = p_attempt_id
  where q.assessment_id = v_attempt.assessment_id
  order by q.sort_order;
end;
$$;

comment on function public.attempt_review(uuid) is
  'Post-submission review including the answer key. The only sanctioned path to '
  'assessment_choices.is_correct for a non-admin, gated on the attempt being '
  'submitted and owned by the caller.';

revoke execute on function public.attempt_review(uuid) from public, anon;
grant execute on function public.attempt_review(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Records an answer while an attempt is open.
--
-- Exists so the runner can save progress with one upsert per question without
-- needing to know whether a row already exists. The RLS policies on
-- assessment_answers still apply: this is SECURITY INVOKER, unlike the
-- functions above, precisely so a learner cannot use it to write into someone
-- else's attempt.
-- ---------------------------------------------------------------------------
create or replace function public.save_answer(
  p_attempt_id  uuid,
  p_question_id uuid,
  p_choice_ids  uuid[] default '{}',
  p_text_answer text default null
) returns void
language sql
set search_path = public, pg_temp
as $$
  insert into public.assessment_answers (attempt_id, question_id, choice_ids, text_answer)
  values (p_attempt_id, p_question_id, coalesce(p_choice_ids, '{}'), p_text_answer)
  on conflict (attempt_id, question_id) do update
    set choice_ids  = excluded.choice_ids,
        text_answer = excluded.text_answer,
        answered_at = now();
$$;

revoke execute on function public.save_answer(uuid, uuid, uuid[], text) from public, anon;
grant execute on function public.save_answer(uuid, uuid, uuid[], text) to authenticated;


-- ###########################################################################
-- ## 20260910091000_rbac_and_invitations.sql
-- ###########################################################################

-- ============================================================================
-- 0011 - Invitation-only accounts, and permission-based access control.
--
-- Two changes, and they are related.
--
-- 1. NOBODY CAN SIGN THEMSELVES UP.
--    `handle_new_user` now refuses any signup with no matching invitation.
--    That covers email/password AND Google OAuth, because both funnel through
--    the same trigger on auth.users - so this is not a dashboard toggle that
--    can be flipped back by accident, it is a database rule.
--
-- 2. ACCESS IS A SET OF PERMISSIONS, NOT JUST A ROLE.
--    `role` (admin | sales) stays as the coarse gate that decides who sees the
--    admin console at all. What a person may actually DO is now a permission
--    set: defaults come from their role, and an admin can grant or revoke any
--    individual permission per person.
--
--    Existing behaviour is preserved exactly: admins are granted every
--    permission by default, so `can('content.edit')` is true for an admin for
--    the same reason `is_admin()` was.
--
-- Creating the auth user itself still needs the service role key, which must
-- never reach the browser. The invitation flow is how an admin provisions an
-- account without it: the admin records who may join and with what access, and
-- the person sets their own password. The admin never learns it, which is
-- better than the alternative.
-- ============================================================================

-- =========================================================== permissions ====

create table public.permissions (
  key         text primary key check (key ~ '^[a-z_]+\.[a-z_]+$'),
  label       text not null,
  description text not null default '',
  -- Groups the admin UI's checklist. Not a security boundary.
  category    text not null,
  sort_order  int  not null default 0
);

comment on table public.permissions is
  'The catalogue of things a person can be allowed to do. Rows are seeded by '
  'this migration; the application never invents a key at runtime.';

insert into public.permissions (key, label, description, category, sort_order) values
  -- Learning content
  ('content.view_drafts', 'View drafts',        'See unpublished materials.',                     'Content',  10),
  ('content.create',      'Create materials',   'Add new modules and lessons.',                   'Content',  11),
  ('content.edit',        'Edit materials',      'Change existing modules, lessons and blocks.',  'Content',  12),
  ('content.publish',     'Publish materials',   'Make a material visible to sales users.',      'Content',  13),
  ('content.archive',     'Archive materials',   'Withdraw a material without deleting it.',     'Content',  14),
  ('categories.manage',   'Manage categories',   'Add, rename and remove categories.',           'Content',  15),

  -- Assessments
  ('assessments.create',  'Create assessments',  'Add new assessments.',                          'Assessments', 20),
  ('assessments.edit',    'Edit assessments',    'Change questions, options and answer keys.',    'Assessments', 21),
  ('assessments.publish', 'Publish assessments', 'Make an assessment available to take.',         'Assessments', 22),
  ('assessments.results', 'View all results',    'See every learner''s attempts and scores.',     'Assessments', 23),

  -- Training
  ('training.manage',     'Manage activities',   'Add and edit facilitator-led activities.',      'Training', 30),
  ('scenarios.manage',    'Manage scenarios',    'Add and edit practice scenarios.',              'Training', 31),

  -- Sales resources
  ('objections.manage',   'Manage objections',   'Edit the objection handling library.',          'Resources', 40),
  ('scripts.manage',      'Manage scripts',      'Edit the script library.',                      'Resources', 41),
  ('quickref.manage',     'Manage quick reference', 'Edit the quick reference cards.',            'Resources', 42),
  ('salesbible.edit',     'Edit Sales Bible',    'Fill in Sales Bible fields.',                   'Resources', 43),
  ('salesbible.verify',   'Verify Sales Bible',  'Mark a Sales Bible value as management-approved.', 'Resources', 44),

  -- People
  ('users.view',          'View people',         'See the team roster and account details.',      'People', 50),
  ('users.invite',        'Invite people',       'Create an invitation so someone can join.',     'People', 51),
  ('users.edit',          'Edit people',         'Change someone''s name, department or position.', 'People', 52),
  ('users.set_role',      'Change roles',        'Move someone between admin and sales.',         'People', 53),
  ('users.set_status',    'Activate / deactivate', 'Suspend or reinstate an account.',            'People', 54),
  ('users.permissions',   'Manage permissions',  'Grant or revoke individual permissions.',       'People', 55),

  -- Delivery
  ('assignments.manage',  'Assign training',     'Assign modules, paths and assessments.',        'Delivery', 60),
  ('announcements.manage','Manage announcements','Post and withdraw announcements.',              'Delivery', 61),

  -- Development
  ('competencies.manage', 'Manage competencies', 'Edit the competency framework.',                'Development', 70),
  ('competencies.rate',   'Rate competencies',   'Score a learner against the framework.',        'Development', 71),

  -- Oversight
  ('reports.view',        'View reports',        'Open the admin reports.',                       'Oversight', 80),
  ('logs.view',           'View activity log',   'Read the audit trail.',                         'Oversight', 81),
  ('settings.manage',     'Manage settings',     'Change system settings.',                       'Oversight', 82);

-- ------------------------------------------------------- role defaults ------

create table public.role_permissions (
  role           public.user_role not null,
  permission_key text not null references public.permissions (key) on delete cascade,
  primary key (role, permission_key)
);

comment on table public.role_permissions is
  'What a role can do by default. Editable, so "what an admin can do" is '
  'configuration rather than something compiled into policies.';

-- An admin gets everything. This is what keeps the pre-existing behaviour
-- identical after the policy rewrite below.
insert into public.role_permissions (role, permission_key)
select 'admin', key from public.permissions;

-- A sales user gets nothing from this table. Everything a learner does -
-- reading published content, their own progress, their own attempts - is
-- governed by ownership policies rather than by a permission, so there is
-- deliberately nothing to grant here by default.

-- --------------------------------------------------- per-person overrides ---

create table public.user_permissions (
  user_id        uuid not null references public.profiles (id) on delete cascade,
  permission_key text not null references public.permissions (key) on delete cascade,
  -- true grants a permission the role does not have; false revokes one it does.
  -- Storing the negative case explicitly is what makes "admin, but may not
  -- change roles" expressible.
  granted        boolean not null,
  granted_by     uuid references public.profiles (id) on delete set null,
  granted_at     timestamptz not null default now(),
  note           text not null default '',

  primary key (user_id, permission_key)
);

create index user_permissions_user_idx on public.user_permissions (user_id);

-- ---------------------------------------------------------------------------
-- The check.
--
-- Override first, role default second, deny third. SECURITY DEFINER for the
-- same reason `is_admin()` is: a policy on a table that consulted these tables
-- as the caller would need its own read policies, and the recursion is not
-- worth the trouble. STABLE so the planner evaluates it once per statement.
-- ---------------------------------------------------------------------------
create or replace function public.can(p_key text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    -- An explicit override always wins, in both directions.
    (select up.granted
       from public.user_permissions up
      where up.user_id = auth.uid() and up.permission_key = p_key),
    -- Otherwise the role default, but only for an active account.
    (select exists (
       select 1
         from public.profiles p
         join public.role_permissions rp on rp.role = p.role
        where p.id = auth.uid()
          and p.status = 'active'
          and rp.permission_key = p_key
     )),
    false
  );
$$;

comment on function public.can(text) is
  'True when the caller holds the named permission. Per-user override beats '
  'role default; a deactivated account holds nothing.';

/** Every permission the caller effectively holds. Powers the UI''s guards. */
create or replace function public.my_permissions()
returns setof text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select p.key
    from public.permissions p
   where public.can(p.key);
$$;

revoke execute on function public.can(text) from public, anon;
revoke execute on function public.my_permissions() from public, anon;
grant execute on function public.can(text) to authenticated;
grant execute on function public.my_permissions() to authenticated;

-- ------------------------------------------------------------------ RLS -----

alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_permissions enable row level security;

-- The catalogue is readable by anyone signed in: the UI needs the labels to
-- explain what a permission means, and knowing a permission exists is not
-- sensitive.
create policy permissions_select on public.permissions
  for select to authenticated using (public.is_active_user());

create policy role_permissions_select on public.role_permissions
  for select to authenticated using (public.is_active_user());

create policy role_permissions_manage on public.role_permissions
  for all to authenticated
  using (public.can('users.permissions')) with check (public.can('users.permissions'));

-- A person may see their own grants; changing anyone's requires the permission
-- to manage permissions - including their own, which the guard below blocks.
create policy user_permissions_select on public.user_permissions
  for select to authenticated
  using (user_id = auth.uid() or public.can('users.permissions'));

create policy user_permissions_manage on public.user_permissions
  for all to authenticated
  using (public.can('users.permissions')) with check (public.can('users.permissions'));

-- =========================================================== invitations ====

create table public.invitations (
  id           uuid primary key default gen_random_uuid(),
  -- Stored lower-cased by the trigger below so a mismatch in capitalisation
  -- cannot silently block a legitimate signup.
  email        text not null check (position('@' in email) > 1),
  role         public.user_role not null default 'sales',
  department   text,
  position     text,
  full_name    text,
  /**
   * Permissions to apply on top of the role's defaults when the invitation is
   * accepted. Chosen by the admin at invite time, which is what "choose what
   * access that sales can have" means in practice.
   */
  permissions  text[] not null default '{}',

  invited_by   uuid references public.profiles (id) on delete set null,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null default now() + interval '14 days',
  accepted_at  timestamptz,
  accepted_by  uuid references public.profiles (id) on delete set null,
  revoked_at   timestamptz,
  note         text not null default ''
);

-- One live invitation per address. A revoked or accepted one does not block a
-- new invite, which is what makes re-inviting somebody possible.
create unique index invitations_one_pending
  on public.invitations (lower(email))
  where accepted_at is null and revoked_at is null;

create index invitations_email_idx on public.invitations (lower(email));
create index invitations_created_idx on public.invitations (created_at desc);

create or replace function public.invitations_normalise_email()
returns trigger language plpgsql as $$
begin
  new.email := lower(trim(new.email));
  return new;
end;
$$;

create trigger invitations_normalise_email
  before insert or update of email on public.invitations
  for each row execute function public.invitations_normalise_email();

alter table public.invitations enable row level security;

create policy invitations_select on public.invitations
  for select to authenticated using (public.can('users.view'));

create policy invitations_manage on public.invitations
  for all to authenticated
  using (public.can('users.invite')) with check (public.can('users.invite'));

-- ---------------------------------------------------------------------------
-- Signup, rewritten.
--
-- Replaces the version in 0002. The difference: no invitation, no account.
--
-- The exception message is deliberately the same whether the address was never
-- invited, the invitation expired, or it was already used. Distinguishing them
-- would turn this endpoint into a way to discover who has been invited.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_invite public.invitations;
  v_email  text := lower(trim(new.email));
  v_name   text;
begin
  select * into v_invite
    from public.invitations
   where lower(email) = v_email
     and accepted_at is null
     and revoked_at is null
     and expires_at > now()
   order by created_at desc
   limit 1;

  if v_invite.id is null then
    raise exception
      'This platform is invitation only. Ask an administrator to create an account for you.'
      using errcode = 'insufficient_privilege';
  end if;

  -- Prefer the name the admin recorded on the invitation; fall back to what
  -- the identity provider supplied, then to the local part of the address.
  v_name := coalesce(
    nullif(trim(v_invite.full_name), ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'name', ''),
    split_part(v_email, '@', 1)
  );

  insert into public.profiles (
    id, email, full_name, avatar_url, role, status, department, position
  )
  values (
    new.id,
    v_email,
    v_name,
    nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
    v_invite.role,
    -- Active immediately: an admin already decided this person should have
    -- access, so a second approval step would be busywork.
    'active',
    v_invite.department,
    v_invite.position
  )
  on conflict (id) do nothing;

  -- Apply the extra permissions the admin picked at invite time.
  if array_length(v_invite.permissions, 1) > 0 then
    insert into public.user_permissions (user_id, permission_key, granted, granted_by, note)
    select new.id, key, true, v_invite.invited_by, 'Granted on invitation'
      from unnest(v_invite.permissions) as key
     where exists (select 1 from public.permissions p where p.key = key)
    on conflict (user_id, permission_key) do nothing;
  end if;

  update public.invitations
     set accepted_at = now(), accepted_by = new.id
   where id = v_invite.id;

  return new;
end;
$$;

commit;
