-- ===========================================================================
-- KCO LMS schema - PART 8 OF 8
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;


-- ---------------------------------------------------------------------------
-- Creating the account.
--
-- Replaces admin_invite_user. Takes a username, maps it to the internal
-- address, and records the pending account. The caller then performs the
-- signup that consumes it.
--
-- `p_email` is optional: pass a real address to create a conventional
-- email-login account, or leave it null to derive one from the username.
-- ---------------------------------------------------------------------------
create or replace function public.admin_create_account(
  p_username    text,
  p_full_name   text default null,
  p_role        public.user_role default 'sales',
  p_department  text default null,
  p_position    text default null,
  p_permissions text[] default '{}',
  p_email       text default null,
  p_note        text default ''
) returns table (invitation_id uuid, login_email text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id       uuid;
  v_username text := lower(trim(coalesce(p_username, '')));
  v_email    text;
begin
  if not public.can('users.invite') then
    raise exception 'You do not have permission to create accounts';
  end if;

  if v_username !~ '^[a-z0-9][a-z0-9._-]{2,29}$' then
    raise exception
      'A username must be 3-30 characters, lower-case, starting with a letter or number, using only letters, numbers, dot, dash or underscore.';
  end if;

  -- The internal address. Kept in step with usernameToEmail() on the client;
  -- changing the domain would orphan every existing login.
  v_email := coalesce(nullif(lower(trim(p_email)), ''), v_username || '@kco.local');

  if position('@' in v_email) < 2 then
    raise exception 'That email address is not valid';
  end if;

  if exists (select 1 from public.profiles where lower(username) = v_username) then
    raise exception 'The username "%" is already taken', v_username;
  end if;

  if exists (select 1 from public.profiles where lower(email) = v_email) then
    raise exception 'An account already exists for %', v_email;
  end if;

  -- Supersede any pending record for the same address rather than tripping
  -- the unique index, so retrying after a failed signup just works.
  update public.invitations
     set revoked_at = now()
   where lower(email) = v_email and accepted_at is null and revoked_at is null;

  insert into public.invitations
    (email, username, full_name, role, department, position, permissions, invited_by, note, expires_at)
  values
    (v_email, v_username, p_full_name, p_role, p_department, p_position,
     coalesce(p_permissions, '{}'), auth.uid(), coalesce(p_note, ''),
     -- Short window: the signup happens seconds later in the same request
     -- cycle. A day is generous and limits how long a half-created account
     -- can be claimed if the signup step fails.
     now() + interval '1 day')
  returning id into v_id;

  perform public.log_activity(
    'user.invited', 'invitation', v_id, v_username,
    jsonb_build_object('role', p_role, 'permissions', coalesce(p_permissions, '{}'))
  );

  return query select v_id, v_email;
end;
$$;

revoke execute on function public.admin_create_account(text, text, public.user_role, text, text, text[], text, text)
  from public, anon;
grant execute on function public.admin_create_account(text, text, public.user_role, text, text, text[], text, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- Cleaning up a failed creation.
--
-- If the signup step fails - a weak password, a network drop - the invitation
-- is left pending and the username looks taken. This lets the admin's browser
-- withdraw it so the same username can be retried immediately.
-- ---------------------------------------------------------------------------
create or replace function public.admin_discard_pending_account(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.can('users.invite') then
    raise exception 'You do not have permission to manage accounts';
  end if;

  delete from public.invitations
   where id = p_invitation_id and accepted_at is null;
end;
$$;

revoke execute on function public.admin_discard_pending_account(uuid) from public, anon;
grant execute on function public.admin_discard_pending_account(uuid) to authenticated;

-- A person may change their own username; the profiles_update_self policy
-- pins only role and status, so this needs no new policy. It does need the
-- format and uniqueness guarantees above, which the constraints provide.

commit;
