-- ===========================================================================
-- KCO LMS schema - PART 1 OF 8
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;

-- ---------------------------------------------------------------------------
-- PREFLIGHT: refuse to re-apply a schema that is already there.
--
-- Without this, a second run dies on `type "user_role" already exists`, which
-- is technically true and completely unhelpful.
-- ---------------------------------------------------------------------------
do $guard$
begin
  if exists (
    select 1 from pg_type t
      join pg_namespace n on n.oid = t.typnamespace
     where n.nspname = 'public' and t.typname = 'user_role'
  ) then
    raise exception
      E'The KCO schema is ALREADY APPLIED to this database.\n\n'
      'Do not run the schema parts again - nothing you need creates types.\n\n'
      'If you are trying to:\n'
      '  * create your admin login    -> run supabase/bootstrap-admin.sql\n'
      '  * load the training content  -> run supabase/seed/parts/ in order\n'
      '  * apply a NEW migration      -> run just that one file\n\n'
      'To genuinely start over (this DELETES everything):\n'
      '  drop schema public cascade; create schema public;\n'
      'then run schema-01.sql onward.';
  end if;
end
$guard$;

-- ###########################################################################
-- ## 20260910090000_extensions_and_enums.sql
-- ###########################################################################

-- ============================================================================
-- KCO Sales & Learning Management System
-- 0001 - Extensions, enums, and shared helper functions.
--
-- Every later migration depends on the vocabulary defined here. Enums are used
-- instead of free-text status columns so an invalid state cannot be written at
-- all, rather than being caught by application validation that a direct API
-- call would bypass.
-- ============================================================================

create extension if not exists "pgcrypto"  with schema extensions;  -- gen_random_uuid()
create extension if not exists "pg_trgm"   with schema extensions;  -- trigram search

-- ---------------------------------------------------------------- identity --

-- Exactly two roles (spec §8). Widening this is a deliberate migration, not a
-- config change, because every RLS policy in 0004 reads it.
create type public.user_role as enum ('admin', 'sales');

create type public.user_status as enum ('active', 'inactive', 'pending');

-- ----------------------------------------------------------------- content --

create type public.content_status as enum ('draft', 'published', 'archived');

create type public.difficulty as enum ('foundation', 'intermediate', 'advanced');

-- The block vocabulary the renderer understands. A block whose type is not in
-- this list cannot be stored, so the frontend never meets one it cannot draw.
create type public.block_type as enum (
  'heading',
  'text',
  'bullets',
  'numbered',
  'checklist',
  'callout',
  'dosdonts',
  'script',
  'comparison',
  'formula',
  'scenario',
  'quote',
  'quiz',
  'activity',
  'wording',
  'tip',
  'warning',
  'image',
  'video'
);

-- ------------------------------------------------------------- assessments --

create type public.question_type as enum (
  'multiple_choice',
  'true_false',
  'multiple_select',
  'short_answer'
);

create type public.attempt_status as enum ('in_progress', 'submitted', 'abandoned');

-- --------------------------------------------------------------- delivery ---

create type public.assignment_target as enum ('module', 'path', 'assessment', 'activity');

create type public.assignment_status as enum (
  'not-started',
  'in-progress',
  'completed',
  'overdue'
);

create type public.progress_state as enum ('not-started', 'in-progress', 'completed');

create type public.notification_kind as enum (
  'assignment',
  'announcement',
  'result',
  'content',
  'due',
  'mention'
);

create type public.announcement_priority as enum ('normal', 'important', 'critical');

-- ---------------------------------------------------------------- helpers ---

-- Keeps updated_at honest. Attached by trigger to every mutable table so an
-- application that forgets to set it cannot produce a stale timestamp.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ###########################################################################
-- ## 20260910090100_profiles.sql
-- ###########################################################################

-- ============================================================================
-- 0002 - Profiles.
--
-- Supabase Auth owns identity (auth.users); this table owns everything the
-- product knows about a person. Credentials are never duplicated here (§10).
--
-- `id` is the auth user id rather than an independent surrogate key. That makes
-- `auth.uid() = id` the cheapest possible RLS predicate - no join, no subquery -
-- which matters because every policy in 0004 evaluates it on every row.
-- ============================================================================

create table public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,

  email         text        not null unique,
  full_name     text        not null check (length(trim(full_name)) between 1 and 120),
  display_name  text        check (length(trim(display_name)) between 1 and 60),
  avatar_url    text,

  role          public.user_role   not null default 'sales',
  status        public.user_status not null default 'pending',

  department    text,
  position      text,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  last_login_at timestamptz
);

comment on table public.profiles is
  'Application identity. One row per auth.users row; never stores credentials.';
comment on column public.profiles.role is
  'Authorization source of truth. Only an admin may change it (see 0004).';

create index profiles_role_idx    on public.profiles (role);
create index profiles_status_idx  on public.profiles (status);
create index profiles_created_idx on public.profiles (created_at desc);
-- Case-insensitive lookup for the admin user table's search box.
create index profiles_name_trgm_idx on public.profiles using gin (full_name extensions.gin_trgm_ops);

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Role lookup used by every admin policy.
--
-- SECURITY DEFINER is required, not a convenience: a policy on `profiles` that
-- selected from `profiles` to find the caller's role would re-enter its own
-- RLS check and recurse. Running as the owner reads the row directly.
--
-- STABLE lets the planner call it once per statement instead of once per row.
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and p.status = 'active'
  );
$$;

comment on function public.is_admin() is
  'True when the caller is an active admin. SECURITY DEFINER to avoid RLS recursion on profiles.';

-- Signed-in and not deactivated. Used wherever "any real user" is the bar.
create or replace function public.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.status = 'active'
  );
$$;

-- ---------------------------------------------------------------------------
-- Provisioning. Fires for both email/password signup and OAuth (§9), so a
-- Google sign-in lands with a profile already in place and the app never has
-- to handle a signed-in user with no profile row.
--
-- New accounts are always 'sales' + 'pending'. Self-promotion is impossible
-- here by construction; an admin activates and assigns the role afterwards.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, role, status)
  values (
    new.id,
    new.email,
    -- OAuth providers use different keys for the same idea; fall back to the
    -- local-part of the address so full_name is never empty.
    coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      nullif(new.raw_user_meta_data ->> 'name', ''),
      split_part(new.email, '@', 1)
    ),
    nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
    'sales',
    'pending'
  )
  on conflict (id) do nothing;   -- idempotent: re-running signup is not an error
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Records the sign-in timestamp shown in the admin user table. Called by the
-- client after a successful session; safe for a user to run on their own row.
create or replace function public.touch_last_login()
returns void
language sql
security definer
set search_path = public, pg_temp
as $$
  update public.profiles set last_login_at = now() where id = auth.uid();
$$;


-- ###########################################################################
-- ## 20260910090200_content.sql
-- ###########################################################################

-- ============================================================================
-- 0003 - Learning content.
--
-- Shape:  categories -> modules -> lessons -> content_blocks
--         learning_paths -> learning_path_items -> (module | assessment)
--
-- Naming note: the DB calls the top-level unit a "module" (§11). The UI calls
-- the same thing a "Material" because that is the word the sidebar uses (§7).
-- One concept, two audiences; the mapping lives in the service layer.
-- ============================================================================

-- ------------------------------------------------------------- categories --

create table public.categories (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name        text not null check (length(trim(name)) between 1 and 80),
  description text not null default '',
  -- Token name, not a hex value: the theme resolves it, so dark mode keeps
  -- working and a category cannot introduce an off-palette colour.
  accent      text not null default 'slate'
                check (accent in ('green','blue','amber','violet','rose','slate')),
  icon        text not null default 'BookMarked',
  sort_order  int  not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index categories_sort_idx on public.categories (sort_order, name);

create trigger categories_set_updated_at before update on public.categories
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- modules --

create table public.modules (
  id            uuid primary key default gen_random_uuid(),
  slug          text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title         text not null check (length(trim(title)) between 1 and 160),
  description   text not null default '',
  category_id   uuid references public.categories (id) on delete set null,

  module_number int  not null default 0,
  status        public.content_status not null default 'draft',
  difficulty    public.difficulty     not null default 'foundation',
  duration_minutes int not null default 0 check (duration_minutes >= 0),

  -- Who may see it, and which teams it is aimed at. Empty audience would hide
  -- a module from everyone, which is never intended, so it is disallowed.
  audience      public.user_role[] not null default array['admin','sales']::public.user_role[]
                  check (cardinality(audience) > 0),
  teams         text[] not null default '{}',
  tags          text[] not null default '{}',

  thumbnail_url text,
  icon          text,

  -- §44: set when the body contains an earnings/ROI style claim that management
  -- has not signed off. The UI badges it; it does not block publishing.
  needs_claim_review boolean not null default false,

  version       int  not null default 1 check (version >= 1),
  created_by    uuid references public.profiles (id) on delete set null,
  updated_by    uuid references public.profiles (id) on delete set null,
  published_by  uuid references public.profiles (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  published_at  timestamptz,

  -- A module cannot claim to be published without a publication timestamp;
  -- reports group by published_at and a null there would silently drop rows.
  constraint modules_published_has_timestamp
    check (status <> 'published' or published_at is not null)
);

create index modules_status_idx     on public.modules (status);
create index modules_category_idx   on public.modules (category_id);
create index modules_number_idx     on public.modules (module_number);
create index modules_updated_idx    on public.modules (updated_at desc);
-- Serves the library list, which is always filtered to published first.
create index modules_status_cat_idx on public.modules (status, category_id);
create index modules_title_trgm_idx on public.modules using gin (title extensions.gin_trgm_ops);
create index modules_tags_idx       on public.modules using gin (tags);

create trigger modules_set_updated_at before update on public.modules
  for each row execute function public.set_updated_at();

-- Stamps published_at/published_by the first time a module goes live, and
-- bumps version on every content-affecting edit (§58). Doing this in the
-- database means the metadata is right regardless of which client wrote.
create or replace function public.modules_publish_metadata()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'published' and coalesce(old.status, 'draft') <> 'published' then
    new.published_at := coalesce(new.published_at, now());
    new.published_by := coalesce(new.published_by, auth.uid());
  end if;

  -- Republishing an archived module should not reset its original date, so
  -- published_at is never cleared here - only archived status changes.
  if new.title is distinct from old.title
     or new.description is distinct from old.description
     or new.status is distinct from old.status then
    new.version := old.version + 1;
  end if;

  new.updated_by := coalesce(auth.uid(), new.updated_by);
  return new;
end;
$$;

create trigger modules_publish_metadata
  before update on public.modules
  for each row execute function public.modules_publish_metadata();

-- ---------------------------------------------------------------- lessons --

create table public.lessons (
  id          uuid primary key default gen_random_uuid(),
  module_id   uuid not null references public.modules (id) on delete cascade,
  title       text not null check (length(trim(title)) between 1 and 160),
  summary     text not null default '',
  -- Position within the module. Unique per module so two lessons can never
  -- occupy the same slot and render in an arbitrary order.
  sort_order  int  not null default 0,
  status      public.content_status not null default 'published',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint lessons_unique_order unique (module_id, sort_order) deferrable initially deferred
);

create index lessons_module_idx on public.lessons (module_id, sort_order);

create trigger lessons_set_updated_at before update on public.lessons
  for each row execute function public.set_updated_at();

-- --------------------------------------------------------- content_blocks --

-- One row per block (§14) rather than one HTML blob per lesson. The typed
-- column drives the renderer; `data` carries the shape that type requires.
-- Validation of `data` lives in the Zod schemas shared by editor and seed -
-- Postgres enforces the envelope, the application enforces the payload.
create table public.content_blocks (
  id         uuid primary key default gen_random_uuid(),
  lesson_id  uuid not null references public.lessons (id) on delete cascade,
  type       public.block_type not null,
  data       jsonb not null default '{}'::jsonb,
  sort_order int   not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint content_blocks_unique_order unique (lesson_id, sort_order) deferrable initially deferred
);

create index content_blocks_lesson_idx on public.content_blocks (lesson_id, sort_order);

create trigger content_blocks_set_updated_at before update on public.content_blocks
  for each row execute function public.set_updated_at();

-- --------------------------------------------------------- learning paths --

create table public.learning_paths (
  id          uuid primary key default gen_random_uuid(),
  slug        text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title       text not null check (length(trim(title)) between 1 and 160),
  description text not null default '',
  audience    public.user_role[] not null default array['admin','sales']::public.user_role[],
  accent      text not null default 'slate'
                check (accent in ('green','blue','amber','violet','rose','slate')),
  status      public.content_status not null default 'draft',
  created_by  uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  published_at timestamptz
);

create index learning_paths_status_idx on public.learning_paths (status);

create trigger learning_paths_set_updated_at before update on public.learning_paths
  for each row execute function public.set_updated_at();

-- A path step is either a module or an assessment, never both and never
-- neither - enforced below rather than left to the application.
create table public.learning_path_items (
  id         uuid primary key default gen_random_uuid(),
  path_id    uuid not null references public.learning_paths (id) on delete cascade,
  module_id  uuid references public.modules (id) on delete cascade,
  -- FK added in 0005, once assessments exists.
  assessment_id uuid,
  sort_order int not null default 0,
  required   boolean not null default true,

  constraint path_item_exactly_one_target check (
    (module_id is not null)::int + (assessment_id is not null)::int = 1
  ),
  constraint learning_path_items_unique_order unique (path_id, sort_order) deferrable initially deferred
);

create index learning_path_items_path_idx on public.learning_path_items (path_id, sort_order);


-- ###########################################################################
-- ## 20260910090300_assessments.sql
-- ###########################################################################

-- ============================================================================
-- 0004 - Assessments, attempts, and answers.
--
-- The security-critical detail in this file is that correct answers live in
-- `assessment_choices.is_correct` and `assessment_questions.correct_text`,
-- both of which are withheld from sales users by the policies in 0007. A
-- learner's client literally cannot read the key, so "don't reveal answers
-- before submission" (§17) is enforced by the database, not by careful UI.
-- ============================================================================

create table public.assessments (
  id             uuid primary key default gen_random_uuid(),
  slug           text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title          text not null check (length(trim(title)) between 1 and 160),
  description    text not null default '',
  instructions   text not null default '',
  module_id      uuid references public.modules (id) on delete set null,

  passing_score  int not null default 80 check (passing_score between 0 and 100),
  time_limit_minutes int check (time_limit_minutes is null or time_limit_minutes > 0),
  -- 0 means unlimited. Negative would be meaningless, so it is excluded.
  attempts_allowed int not null default 3 check (attempts_allowed >= 0),
  randomize_questions boolean not null default false,
  randomize_choices   boolean not null default false,
  show_correct_answers boolean not null default true,

  status         public.content_status not null default 'draft',
  version        int not null default 1,
  created_by     uuid references public.profiles (id) on delete set null,
  updated_by     uuid references public.profiles (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  published_at   timestamptz,

  constraint assessments_published_has_timestamp
    check (status <> 'published' or published_at is not null)
);

create index assessments_status_idx on public.assessments (status);
create index assessments_module_idx on public.assessments (module_id);

create trigger assessments_set_updated_at before update on public.assessments
  for each row execute function public.set_updated_at();

-- Deferred FK from 0003, now that the target exists.
alter table public.learning_path_items
  add constraint learning_path_items_assessment_fk
  foreign key (assessment_id) references public.assessments (id) on delete cascade;

-- -------------------------------------------------------------- questions --

create table public.assessment_questions (
  id            uuid primary key default gen_random_uuid(),
  assessment_id uuid not null references public.assessments (id) on delete cascade,
  type          public.question_type not null default 'multiple_choice',
  prompt        text not null check (length(trim(prompt)) > 0),
  explanation   text not null default '',
  points        int  not null default 1 check (points > 0),
  sort_order    int  not null default 0,

  -- Only used by 'short_answer'. Compared case-insensitively and trimmed by
  -- the scoring function below.
  correct_text  text,

  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint questions_unique_order unique (assessment_id, sort_order) deferrable initially deferred,
  -- A short-answer question with no key cannot be scored, and a choice-based
  -- question with a key would be ambiguous.
  constraint questions_short_answer_has_key check (
    (type = 'short_answer' and correct_text is not null and length(trim(correct_text)) > 0)
    or (type <> 'short_answer' and correct_text is null)
  )
);

create index assessment_questions_assessment_idx
  on public.assessment_questions (assessment_id, sort_order);

create trigger assessment_questions_set_updated_at before update on public.assessment_questions
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------- choices --

create table public.assessment_choices (
  id          uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.assessment_questions (id) on delete cascade,
  text        text not null check (length(trim(text)) > 0),
  is_correct  boolean not null default false,
  sort_order  int not null default 0,

  constraint choices_unique_order unique (question_id, sort_order) deferrable initially deferred
);

create index assessment_choices_question_idx on public.assessment_choices (question_id, sort_order);

-- Guards the builder's output at write time: a choice-based question must have
-- at least two options and the right number of correct ones. Without this a
-- half-finished question could be published and would be unscoreable.
create or replace function public.validate_question_choices(p_question_id uuid)
returns void
language plpgsql
as $$
declare
  q_type   public.question_type;
  n_total  int;
  n_correct int;
begin
  select type into q_type from public.assessment_questions where id = p_question_id;
  if q_type is null or q_type = 'short_answer' then
    return;
  end if;

  select count(*), count(*) filter (where is_correct)
    into n_total, n_correct
    from public.assessment_choices where question_id = p_question_id;

  if n_total < 2 then
    raise exception 'Question % needs at least two choices (has %)', p_question_id, n_total;
  end if;

  if q_type in ('multiple_choice', 'true_false') and n_correct <> 1 then
    raise exception 'Question % must have exactly one correct choice (has %)', p_question_id, n_correct;
  end if;

  if q_type = 'multiple_select' and n_correct < 1 then
    raise exception 'Question % must have at least one correct choice', p_question_id;
  end if;
end;
$$;

commit;
