-- ===========================================================================
-- KCO LMS schema - PART 6 OF 7
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;


/**
 * Tells the sign-in screen whether an address has a usable invitation.
 *
 * Returns only a boolean, never any detail about the invitation, and is
 * callable by `anon` because the person using it does not have an account yet.
 * The information it leaks is whether a given address may register, which the
 * signup attempt itself would reveal in any case.
 */
create or replace function public.invitation_exists(p_email text)
returns boolean
language sql
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.invitations
     where lower(email) = lower(trim(p_email))
       and accepted_at is null
       and revoked_at is null
       and expires_at > now()
  );
$$;

grant execute on function public.invitation_exists(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Admin operations on invitations and permissions.
-- ---------------------------------------------------------------------------

create or replace function public.admin_invite_user(
  p_email       text,
  p_full_name   text default null,
  p_role        public.user_role default 'sales',
  p_department  text default null,
  p_position    text default null,
  p_permissions text[] default '{}',
  p_note        text default ''
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id uuid;
  v_email text := lower(trim(p_email));
begin
  if not public.can('users.invite') then
    raise exception 'You do not have permission to invite people';
  end if;

  if exists (select 1 from public.profiles where lower(email) = v_email) then
    raise exception 'An account already exists for %', v_email;
  end if;

  -- Replace any outstanding invitation rather than tripping the unique index,
  -- so re-inviting with different access is a single action.
  update public.invitations
     set revoked_at = now()
   where lower(email) = v_email and accepted_at is null and revoked_at is null;

  insert into public.invitations
    (email, full_name, role, department, position, permissions, invited_by, note)
  values
    (v_email, p_full_name, p_role, p_department, p_position,
     coalesce(p_permissions, '{}'), auth.uid(), coalesce(p_note, ''))
  returning id into v_id;

  perform public.log_activity(
    'user.invited', 'invitation', v_id, v_email,
    jsonb_build_object('role', p_role, 'permissions', coalesce(p_permissions, '{}'))
  );

  return v_id;
end;
$$;

create or replace function public.admin_revoke_invitation(p_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_email text;
begin
  if not public.can('users.invite') then
    raise exception 'You do not have permission to manage invitations';
  end if;

  update public.invitations
     set revoked_at = now()
   where id = p_id and accepted_at is null
   returning email into v_email;

  if v_email is null then
    raise exception 'That invitation does not exist or has already been accepted';
  end if;

  perform public.log_activity('user.invite_revoked', 'invitation', p_id, v_email);
end;
$$;

/**
 * Sets one permission for one person.
 *
 * `p_granted` null clears the override, returning the person to their role's
 * default - which is different from revoking, and both are needed.
 *
 * The guard at the end is the important part: it refuses a change that would
 * leave nobody able to manage permissions. Without it an admin could remove
 * their own `users.permissions` and lock the whole team out of the
 * authorization system with no way back except SQL.
 */
create or replace function public.admin_set_permission(
  p_user_id uuid,
  p_key     text,
  p_granted boolean,
  p_note    text default ''
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_name text;
  v_remaining int;
begin
  if not public.can('users.permissions') then
    raise exception 'You do not have permission to manage permissions';
  end if;

  select full_name into v_name from public.profiles where id = p_user_id;
  if v_name is null then
    raise exception 'No such user';
  end if;

  if not exists (select 1 from public.permissions where key = p_key) then
    raise exception 'Unknown permission %', p_key;
  end if;

  if p_granted is null then
    delete from public.user_permissions
     where user_id = p_user_id and permission_key = p_key;
  else
    insert into public.user_permissions (user_id, permission_key, granted, granted_by, note)
    values (p_user_id, p_key, p_granted, auth.uid(), coalesce(p_note, ''))
    on conflict (user_id, permission_key) do update
      set granted = excluded.granted,
          granted_by = excluded.granted_by,
          granted_at = now(),
          note = excluded.note;
  end if;

  if p_key = 'users.permissions' then
    select count(*) into v_remaining
      from public.profiles pr
     where pr.status = 'active'
       and coalesce(
             (select up.granted from public.user_permissions up
               where up.user_id = pr.id and up.permission_key = 'users.permissions'),
             exists (select 1 from public.role_permissions rp
                      where rp.role = pr.role and rp.permission_key = 'users.permissions')
           );

    if v_remaining = 0 then
      raise exception
        'That would leave nobody able to manage permissions. Grant it to someone else first.';
    end if;
  end if;

  perform public.log_activity(
    'user.permission_changed', 'profile', p_user_id, v_name,
    jsonb_build_object('permission', p_key, 'granted', p_granted)
  );
end;
$$;

revoke execute on function public.admin_invite_user(text, text, public.user_role, text, text, text[], text) from public, anon;
revoke execute on function public.admin_revoke_invitation(uuid) from public, anon;
revoke execute on function public.admin_set_permission(uuid, text, boolean, text) from public, anon;

grant execute on function public.admin_invite_user(text, text, public.user_role, text, text, text[], text) to authenticated;
grant execute on function public.admin_revoke_invitation(uuid) to authenticated;
grant execute on function public.admin_set_permission(uuid, text, boolean, text) to authenticated;

-- ===================================================== policy rewrite =======
--
-- The admin write policies are re-expressed in terms of permissions. Because
-- role_permissions grants an admin every key, this changes no existing
-- behaviour - it only makes the grants individually adjustable, which is the
-- whole point of the exercise.
-- ---------------------------------------------------------------------------

-- Content
drop policy modules_admin on public.modules;
create policy modules_write on public.modules
  for insert to authenticated with check (public.can('content.create'));
create policy modules_update on public.modules
  for update to authenticated
  using (public.can('content.edit') or public.can('content.publish') or public.can('content.archive'))
  with check (public.can('content.edit') or public.can('content.publish') or public.can('content.archive'));
create policy modules_delete on public.modules
  for delete to authenticated using (public.can('content.archive'));

-- Drafts become visible with a permission rather than with a role.
drop policy modules_select_published on public.modules;
create policy modules_select on public.modules
  for select to authenticated
  using (
    public.can('content.view_drafts')
    or (
      public.is_active_user()
      and status = 'published'
      and (select p.role from public.profiles p where p.id = auth.uid()) = any (audience)
    )
  );

drop policy lessons_admin on public.lessons;
create policy lessons_write on public.lessons
  for all to authenticated
  using (public.can('content.edit') or public.can('content.create'))
  with check (public.can('content.edit') or public.can('content.create'));

drop policy lessons_select on public.lessons;
create policy lessons_select on public.lessons
  for select to authenticated
  using (
    public.can('content.view_drafts')
    or (status = 'published' and exists (select 1 from public.modules m where m.id = module_id))
  );

drop policy content_blocks_admin on public.content_blocks;
create policy content_blocks_write on public.content_blocks
  for all to authenticated
  using (public.can('content.edit') or public.can('content.create'))
  with check (public.can('content.edit') or public.can('content.create'));

drop policy content_blocks_select on public.content_blocks;
create policy content_blocks_select on public.content_blocks
  for select to authenticated
  using (
    public.can('content.view_drafts')
    or exists (select 1 from public.lessons l where l.id = lesson_id)
  );

drop policy categories_admin on public.categories;
create policy categories_write on public.categories
  for all to authenticated
  using (public.can('categories.manage')) with check (public.can('categories.manage'));

drop policy learning_paths_admin on public.learning_paths;
create policy learning_paths_write on public.learning_paths
  for all to authenticated
  using (public.can('content.edit') or public.can('content.create'))
  with check (public.can('content.edit') or public.can('content.create'));

drop policy learning_path_items_admin on public.learning_path_items;
create policy learning_path_items_write on public.learning_path_items
  for all to authenticated
  using (public.can('content.edit')) with check (public.can('content.edit'));

-- Assessments
drop policy assessments_admin on public.assessments;
create policy assessments_write on public.assessments
  for insert to authenticated with check (public.can('assessments.create'));
create policy assessments_update on public.assessments
  for update to authenticated
  using (public.can('assessments.edit') or public.can('assessments.publish'))
  with check (public.can('assessments.edit') or public.can('assessments.publish'));
create policy assessments_delete on public.assessments
  for delete to authenticated using (public.can('assessments.edit'));

drop policy assessments_select on public.assessments;
create policy assessments_select on public.assessments
  for select to authenticated
  using (
    public.can('assessments.edit')
    or public.can('assessments.create')
    or (public.is_active_user() and status = 'published')
  );

drop policy assessment_questions_admin on public.assessment_questions;
create policy assessment_questions_write on public.assessment_questions
  for all to authenticated
  using (public.can('assessments.edit')) with check (public.can('assessments.edit'));

drop policy assessment_choices_admin on public.assessment_choices;
create policy assessment_choices_write on public.assessment_choices
  for all to authenticated
  using (public.can('assessments.edit')) with check (public.can('assessments.edit'));

-- Results: a learner sees their own; seeing everyone's is a permission.
drop policy attempts_select_own on public.assessment_attempts;
create policy attempts_select on public.assessment_attempts
  for select to authenticated
  using (user_id = auth.uid() or public.can('assessments.results'));

drop policy answers_select_own on public.assessment_answers;
create policy answers_select on public.assessment_answers
  for select to authenticated
  using (
    public.can('assessments.results')
    or exists (
      select 1 from public.assessment_attempts t
       where t.id = attempt_id and t.user_id = auth.uid()
    )
  );

-- Delivery
drop policy assignments_admin on public.assignments;
create policy assignments_write on public.assignments
  for all to authenticated
  using (public.can('assignments.manage')) with check (public.can('assignments.manage'));

drop policy assignments_select_own on public.assignments;
create policy assignments_select on public.assignments
  for select to authenticated
  using (user_id = auth.uid() or public.can('assignments.manage'));

drop policy announcements_admin on public.announcements;
create policy announcements_write on public.announcements
  for all to authenticated
  using (public.can('announcements.manage')) with check (public.can('announcements.manage'));

-- Oversight
drop policy activity_logs_admin_select on public.activity_logs;
create policy activity_logs_select on public.activity_logs
  for select to authenticated using (public.can('logs.view'));

drop policy activity_logs_admin_write on public.activity_logs;
create policy activity_logs_write on public.activity_logs
  for insert to authenticated with check (public.can('logs.view'));

-- People
drop policy profiles_admin_all on public.profiles;
create policy profiles_admin_read on public.profiles
  for select to authenticated using (public.can('users.view'));
create policy profiles_admin_update on public.profiles
  for update to authenticated
  using (public.can('users.edit')) with check (public.can('users.edit'));

-- Development
drop policy user_competencies_admin on public.user_competencies;
create policy user_competencies_write on public.user_competencies
  for all to authenticated
  using (public.can('competencies.rate')) with check (public.can('competencies.rate'));

-- The resource libraries created by the DO-block in 0007.
do $$
declare
  t text;
  perm text;
  pairs text[][] := array[
    array['training_activities',   'training.manage'],
    array['practice_scenarios',    'scenarios.manage'],
    array['objections',            'objections.manage'],
    array['scripts',               'scripts.manage'],
    array['wording_pairs',         'scripts.manage'],
    array['quick_reference_items', 'quickref.manage'],
    array['competencies',          'competencies.manage']
  ];
  i int;
begin
  for i in 1 .. array_length(pairs, 1) loop
    t := pairs[i][1];
    perm := pairs[i][2];

    execute format('drop policy %I on public.%I', t || '_admin', t);
    execute format($f$
      create policy %I on public.%I
        for all to authenticated
        using (public.can(%L)) with check (public.can(%L))
    $f$, t || '_write', t, perm, perm);
  end loop;
end
$$;

do $$
declare
  t text;
  tables text[] := array['competency_levels', 'sales_bible_sections'];
begin
  foreach t in array tables loop
    execute format('drop policy %I on public.%I', t || '_admin', t);
    execute format($f$
      create policy %I on public.%I
        for all to authenticated
        using (public.can('competencies.manage'))
        with check (public.can('competencies.manage'))
    $f$, t || '_write', t);
  end loop;
end
$$;

drop policy sales_bible_entries_admin on public.sales_bible_entries;
create policy sales_bible_entries_write on public.sales_bible_entries
  for all to authenticated
  using (public.can('salesbible.edit')) with check (public.can('salesbible.edit'));

-- ---------------------------------------------------------------------------
-- The guarded RPCs from 0009 predate permissions and check `is_admin()`.
-- Re-point them at the specific permission each one represents.
-- ---------------------------------------------------------------------------

create or replace function public.admin_set_user_role(
  p_user_id uuid,
  p_role    public.user_role
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admins int;
  v_current public.user_role;
  v_name text;
begin
  if not public.can('users.set_role') then
    raise exception 'You do not have permission to change roles';
  end if;

  select role, full_name into v_current, v_name from public.profiles where id = p_user_id;
  if v_current is null then
    raise exception 'No such user';
  end if;

  if v_current = 'admin' and p_role <> 'admin' then
    select count(*) into v_admins
      from public.profiles where role = 'admin' and status = 'active';
    if v_admins <= 1 then
      raise exception 'Cannot remove the last active admin';
    end if;
  end if;

  update public.profiles set role = p_role where id = p_user_id;

  perform public.log_activity('user.role_changed', 'profile', p_user_id, v_name,
    jsonb_build_object('from', v_current, 'to', p_role));
end;
$$;

create or replace function public.admin_set_user_status(
  p_user_id uuid,
  p_status  public.user_status
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_admins int;
  v_name text;
  v_role public.user_role;
begin
  if not public.can('users.set_status') then
    raise exception 'You do not have permission to change account status';
  end if;

  select full_name, role into v_name, v_role from public.profiles where id = p_user_id;
  if v_name is null then
    raise exception 'No such user';
  end if;

  if v_role = 'admin' and p_status <> 'active' then
    select count(*) into v_admins from public.profiles where role = 'admin' and status = 'active';
    if v_admins <= 1 then
      raise exception 'Cannot deactivate the last active admin';
    end if;
  end if;

  update public.profiles set status = p_status where id = p_user_id;

  perform public.log_activity('user.status_changed', 'profile', p_user_id, v_name,
    jsonb_build_object('to', p_status));
end;
$$;

create or replace function public.admin_save_question(
  p_assessment_id uuid,
  p_question_id   uuid,
  p_type          public.question_type,
  p_prompt        text,
  p_explanation   text,
  p_points        int,
  p_sort_order    int,
  p_correct_text  text,
  p_choices       jsonb
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id uuid;
  v_choice jsonb;
  v_i int := 0;
begin
  if not public.can('assessments.edit') then
    raise exception 'You do not have permission to edit assessment questions';
  end if;

  if p_question_id is null then
    insert into public.assessment_questions
      (assessment_id, type, prompt, explanation, points, sort_order, correct_text)
    values
      (p_assessment_id, p_type, p_prompt, coalesce(p_explanation,''), coalesce(p_points,1),
       coalesce(p_sort_order,0), case when p_type = 'short_answer' then p_correct_text end)
    returning id into v_id;
  else
    update public.assessment_questions
       set type = p_type,
           prompt = p_prompt,
           explanation = coalesce(p_explanation,''),
           points = coalesce(p_points,1),
           sort_order = coalesce(p_sort_order, sort_order),
           correct_text = case when p_type = 'short_answer' then p_correct_text end
     where id = p_question_id and assessment_id = p_assessment_id
     returning id into v_id;

    if v_id is null then
      raise exception 'Question % does not belong to assessment %', p_question_id, p_assessment_id;
    end if;

    delete from public.assessment_choices where question_id = v_id;
  end if;

  if p_type <> 'short_answer' then
    for v_choice in select * from jsonb_array_elements(coalesce(p_choices, '[]'::jsonb))
    loop
      insert into public.assessment_choices (question_id, text, is_correct, sort_order)
      values (v_id, v_choice ->> 'text',
              coalesce((v_choice ->> 'is_correct')::boolean, false), v_i);
      v_i := v_i + 1;
    end loop;

    perform public.validate_question_choices(v_id);
  end if;

  return v_id;
end;
$$;

create or replace function public.admin_assign(
  p_user_ids    uuid[],
  p_target_type public.assignment_target,
  p_target_id   uuid,
  p_due_at      timestamptz default null,
  p_note        text default ''
) returns int
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count int;
  v_label text;
begin
  if not public.can('assignments.manage') then
    raise exception 'You do not have permission to assign training';
  end if;

  select case p_target_type
    when 'module'     then (select title from public.modules             where id = p_target_id)
    when 'path'       then (select title from public.learning_paths      where id = p_target_id)
    when 'assessment' then (select title from public.assessments         where id = p_target_id)
    when 'activity'   then (select title from public.training_activities where id = p_target_id)
  end into v_label;

  if v_label is null then
    raise exception 'No % exists with id %', p_target_type, p_target_id;
  end if;

  with upserted as (
    insert into public.assignments (user_id, target_type, target_id, assigned_by, due_at, note)
    select uid, p_target_type, p_target_id, auth.uid(), p_due_at, coalesce(p_note,'')
      from unnest(p_user_ids) as uid
    on conflict (user_id, target_type, target_id) do update
      set due_at = excluded.due_at,
          note = excluded.note,
          assigned_by = excluded.assigned_by,
          assigned_at = now()
    returning user_id
  )
  select count(*) into v_count from upserted;

  insert into public.notifications (user_id, kind, title, body)
  select uid, 'assignment', 'New training assigned', v_label
    from unnest(p_user_ids) as uid;

  perform public.log_activity(
    'assignment.created', p_target_type::text, p_target_id, v_label,
    jsonb_build_object('recipients', coalesce(array_length(p_user_ids, 1), 0))
  );

  return v_count;
end;
$$;

create or replace function public.admin_dashboard_stats()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v jsonb;
begin
  if not public.can('reports.view') then
    raise exception 'You do not have permission to view reports';
  end if;

  select jsonb_build_object(
    'sales_users',        (select count(*) from public.profiles where role = 'sales'),
    'active_users',       (select count(*) from public.profiles where status = 'active'),
    'pending_users',      (select count(*) from public.profiles where status = 'pending'),
    'pending_invitations',(select count(*) from public.invitations
                            where accepted_at is null and revoked_at is null and expires_at > now()),
    'published_modules',  (select count(*) from public.modules where status = 'published'),
    'draft_modules',      (select count(*) from public.modules where status = 'draft'),
    'active_paths',       (select count(*) from public.learning_paths where status = 'published'),
    'published_assessments', (select count(*) from public.assessments where status = 'published'),
    'pending_assignments',(select count(*) from public.assignments where status <> 'completed'),
    'overdue_assignments',(select count(*) from public.assignments
                            where status <> 'completed' and due_at is not null and due_at < now()),
    'avg_completion',     coalesce((
        select round(avg(pct), 1) from (
          select p.id,
                 case when total.n = 0 then 0
                      else (count(mp.*) filter (where mp.state = 'completed')::numeric / total.n) * 100
                 end as pct
            from public.profiles p
            cross join (select count(*) as n from public.modules where status = 'published') total
            left join public.module_progress mp on mp.user_id = p.id
           where p.role = 'sales' and p.status = 'active'
           group by p.id, total.n
        ) per_user
      ), 0),
    'avg_assessment_score', coalesce((
        select round(avg(percentage), 1) from public.assessment_attempts where status = 'submitted'
      ), 0),
    'pass_rate', coalesce((
        select round(100.0 * count(*) filter (where passed) / nullif(count(*), 0), 1)
          from public.assessment_attempts where status = 'submitted'
      ), 0),
    'attempts_last_30d', (
        select count(*) from public.assessment_attempts
         where status = 'submitted' and submitted_at > now() - interval '30 days'
      ),
    'lessons_completed_last_7d', (
        select count(*) from public.lesson_progress
         where completed and completed_at > now() - interval '7 days'
      )
  ) into v;

  return v;
end;
$$;

commit;
