-- ===========================================================================
-- KCO LMS schema - PART 7 OF 8
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;


-- The three report functions gate on reports.view rather than is_admin().
create or replace function public.report_training_completion()
returns table (
  user_id uuid, full_name text, department text, status public.user_status,
  modules_completed bigint, modules_in_progress bigint, modules_total bigint,
  completion_percent numeric, assessments_taken bigint, avg_score numeric
)
language sql security definer set search_path = public, pg_temp
as $$
  select p.id, p.full_name, coalesce(p.department, ''), p.status,
    count(mp.*) filter (where mp.state = 'completed'),
    count(mp.*) filter (where mp.state = 'in-progress'),
    total.n,
    case when total.n = 0 then 0
         else round((count(mp.*) filter (where mp.state = 'completed')::numeric / total.n) * 100, 1)
    end,
    (select count(*) from public.assessment_attempts a
      where a.user_id = p.id and a.status = 'submitted'),
    coalesce((select round(avg(a.percentage), 1) from public.assessment_attempts a
      where a.user_id = p.id and a.status = 'submitted'), 0)
  from public.profiles p
  cross join (select count(*) as n from public.modules where status = 'published') total
  left join public.module_progress mp on mp.user_id = p.id
  where public.can('reports.view') and p.role = 'sales'
  group by p.id, p.full_name, p.department, p.status, total.n
  order by p.full_name;
$$;

create or replace function public.report_assessment_performance()
returns table (
  assessment_id uuid, title text, attempts bigint, unique_takers bigint,
  avg_score numeric, pass_rate numeric, passing_score int
)
language sql security definer set search_path = public, pg_temp
as $$
  select a.id, a.title, count(t.*), count(distinct t.user_id),
    coalesce(round(avg(t.percentage), 1), 0),
    coalesce(round(100.0 * count(*) filter (where t.passed) / nullif(count(t.*), 0), 1), 0),
    a.passing_score
  from public.assessments a
  left join public.assessment_attempts t
    on t.assessment_id = a.id and t.status = 'submitted'
  where public.can('reports.view')
  group by a.id, a.title, a.passing_score
  order by a.title;
$$;

create or replace function public.report_module_engagement()
returns table (
  module_id uuid, title text, status public.content_status,
  learners_started bigint, learners_completed bigint, completion_percent numeric
)
language sql security definer set search_path = public, pg_temp
as $$
  select m.id, m.title, m.status,
    count(mp.*) filter (where mp.state <> 'not-started'),
    count(mp.*) filter (where mp.state = 'completed'),
    coalesce(round(
      100.0 * count(mp.*) filter (where mp.state = 'completed')
      / nullif(count(mp.*) filter (where mp.state <> 'not-started'), 0), 1), 0)
  from public.modules m
  left join public.module_progress mp on mp.module_id = m.id
  where public.can('reports.view')
  group by m.id, m.title, m.status
  order by m.title;
$$;

-- Admins may open a draft assessment to test it; that is now a permission.
create or replace function public.start_assessment_attempt(p_assessment_id uuid)
returns public.assessment_attempts
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_allowed int;
  v_status  public.content_status;
  v_used    int;
  v_attempt public.assessment_attempts;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select attempts_allowed, status into v_allowed, v_status
    from public.assessments where id = p_assessment_id;

  if v_status is null then
    raise exception 'Assessment not found';
  end if;

  if v_status <> 'published' and not public.can('assessments.edit') then
    raise exception 'This assessment is not available';
  end if;

  select count(*) into v_used
    from public.assessment_attempts
   where user_id = auth.uid() and assessment_id = p_assessment_id and status = 'submitted';

  if v_allowed > 0 and v_used >= v_allowed then
    raise exception 'You have used all % attempts for this assessment', v_allowed;
  end if;

  select * into v_attempt
    from public.assessment_attempts
   where user_id = auth.uid() and assessment_id = p_assessment_id and status = 'in_progress'
   order by started_at desc limit 1;

  if v_attempt.id is not null then
    return v_attempt;
  end if;

  insert into public.assessment_attempts (assessment_id, user_id, attempt_number)
  values (p_assessment_id, auth.uid(), v_used + 1)
  returning * into v_attempt;

  return v_attempt;
end;
$$;

create or replace function public.attempt_review(p_attempt_id uuid)
returns table (
  question_id uuid, prompt text, type public.question_type, points int,
  sort_order int, explanation text,
  selected_choice_ids uuid[], correct_choice_ids uuid[],
  text_answer text, correct_text text, is_correct boolean, points_awarded int
)
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_attempt public.assessment_attempts;
  v_reveal  boolean;
begin
  select * into v_attempt from public.assessment_attempts where id = p_attempt_id;

  if v_attempt.id is null then
    raise exception 'Attempt not found';
  end if;

  if v_attempt.user_id <> auth.uid() and not public.can('assessments.results') then
    raise exception 'That attempt is not yours';
  end if;

  if v_attempt.status <> 'submitted' then
    raise exception 'This attempt has not been submitted yet';
  end if;

  select a.show_correct_answers into v_reveal
    from public.assessments a where a.id = v_attempt.assessment_id;

  v_reveal := coalesce(v_reveal, true) or public.can('assessments.results');

  return query
  select q.id, q.prompt, q.type, q.points, q.sort_order,
    case when v_reveal then q.explanation else '' end,
    coalesce(ans.choice_ids, '{}'),
    case when v_reveal then coalesce(
      (select array_agg(c.id order by c.sort_order)
         from public.assessment_choices c
        where c.question_id = q.id and c.is_correct), '{}')
      else '{}' end,
    ans.text_answer,
    case when v_reveal then q.correct_text end,
    ans.is_correct,
    coalesce(ans.points_awarded, 0)
  from public.assessment_questions q
  left join public.assessment_answers ans
    on ans.question_id = q.id and ans.attempt_id = p_attempt_id
  where q.assessment_id = v_attempt.assessment_id
  order by q.sort_order;
end;
$$;

-- The admin answer-key views gate on the assessment permission too.
create or replace view public.admin_assessment_choices
  with (security_invoker = false) as
  select c.id, c.question_id, c.text, c.is_correct, c.sort_order
    from public.assessment_choices c
   where public.can('assessments.edit');

create or replace view public.admin_assessment_questions
  with (security_invoker = false) as
  select q.id, q.assessment_id, q.type, q.prompt, q.explanation,
         q.points, q.sort_order, q.correct_text
    from public.assessment_questions q
   where public.can('assessments.edit');

revoke all on public.admin_assessment_choices   from anon;
revoke all on public.admin_assessment_questions from anon;
grant select on public.admin_assessment_choices   to authenticated;
grant select on public.admin_assessment_questions to authenticated;


-- ###########################################################################
-- ## 20260910091100_lock_down_anon.sql
-- ###########################################################################

-- ============================================================================
-- 0012 - Re-lock the privilege layer against `anon`.
--
-- THE BUG THIS FIXES
--
-- Migration 0007 runs `revoke all on all tables in schema public from anon`.
-- That reads like a policy but it is a point-in-time statement: it affects the
-- tables that exist when it runs, and nothing else.
--
-- Supabase ships `alter default privileges in schema public grant all on
-- tables to anon, authenticated`. So every table created by a LATER migration
-- silently arrives with anon privileges restored. 0011 added four tables
-- (permissions, role_permissions, user_permissions, invitations) and all four
-- came back readable at the privilege layer.
--
-- Row Level Security still held - `permissions_select` requires
-- `is_active_user()`, which is false for anon, so the response was an empty
-- array rather than data. Nothing leaked. But "denied before any policy is
-- consulted" is the posture the rest of the schema has, and losing it on a
-- subset of tables is exactly the kind of asymmetry that becomes a real hole
-- the first time somebody adds a table with a laxer policy.
--
-- WHAT TO DO IN FUTURE MIGRATIONS
--
-- End any migration that creates a table with:
--
--     select public.revoke_anon_access();
--
-- The test suite asserts that no table in `public` is readable by anon, so
-- forgetting is a test failure rather than a silent regression.
-- ============================================================================

/**
 * Strips every `anon` privilege across the public schema.
 *
 * Written as a function rather than a bare statement so later migrations have
 * one thing to call, and so the intent is named. It is deliberately
 * idempotent: running it when there is nothing to revoke is a no-op.
 *
 * Note this does NOT touch `authenticated`. That role keeps its table
 * privileges and is constrained by RLS - which is the design. `anon` is
 * different: nothing in this product is public, so an unauthenticated request
 * should fail before a policy is even evaluated.
 */
create or replace function public.revoke_anon_access()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  revoke all on all tables    in schema public from anon;
  revoke all on all sequences in schema public from anon;

  -- Functions are EXECUTE-able by PUBLIC unless told otherwise, and `anon`
  -- inherits that, so the role has to be revoked from PUBLIC as well.
  revoke all on all functions in schema public from public, anon;

  -- Hand back the two functions an unauthenticated visitor legitimately needs:
  -- the sign-in screen checks whether an address has an open invitation before
  -- asking for a password.
  grant execute on function public.invitation_exists(text) to anon;
end;
$$;

comment on function public.revoke_anon_access() is
  'Removes every anon privilege in the public schema. Call at the end of any '
  'migration that creates a table - Supabase default privileges re-grant anon '
  'access to new tables, which 0007''s one-off REVOKE cannot cover.';

-- Apply it now, catching the four tables 0011 created.
select public.revoke_anon_access();

-- The helper itself must not be callable by anon.
revoke execute on function public.revoke_anon_access() from public, anon;

-- Restore the EXECUTE grants that the blanket revoke above just removed from
-- `authenticated`. Listed explicitly rather than re-granted wholesale, so the
-- set of functions a signed-in user may call stays an audited list.
grant execute on function public.is_admin()                                    to authenticated;
grant execute on function public.is_active_user()                              to authenticated;
grant execute on function public.can(text)                                     to authenticated;
grant execute on function public.my_permissions()                              to authenticated;
grant execute on function public.log_activity(text, text, uuid, text, jsonb)   to authenticated;
grant execute on function public.touch_last_login()                            to authenticated;
grant execute on function public.complete_lesson(uuid, boolean)                to authenticated;
grant execute on function public.touch_module_view(uuid, uuid)                 to authenticated;
grant execute on function public.start_assessment_attempt(uuid)                to authenticated;
grant execute on function public.submit_assessment_attempt(uuid)               to authenticated;
grant execute on function public.save_answer(uuid, uuid, uuid[], text)         to authenticated;
grant execute on function public.attempt_review(uuid)                          to authenticated;
grant execute on function public.my_progress_summary()                          to authenticated;
grant execute on function public.admin_dashboard_stats()                        to authenticated;
grant execute on function public.report_training_completion()                   to authenticated;
grant execute on function public.report_assessment_performance()                to authenticated;
grant execute on function public.report_module_engagement()                     to authenticated;
grant execute on function public.admin_assign(uuid[], public.assignment_target, uuid, timestamptz, text)
                                                                                to authenticated;
grant execute on function public.admin_set_user_role(uuid, public.user_role)    to authenticated;
grant execute on function public.admin_set_user_status(uuid, public.user_status) to authenticated;
grant execute on function public.admin_save_question(uuid, uuid, public.question_type, text, text, int, int, text, jsonb)
                                                                                to authenticated;
grant execute on function public.admin_invite_user(text, text, public.user_role, text, text, text[], text)
                                                                                to authenticated;
grant execute on function public.admin_revoke_invitation(uuid)                  to authenticated;
grant execute on function public.admin_set_permission(uuid, text, boolean, text) to authenticated;
grant execute on function public.assignment_effective_status(public.assignment_status, timestamptz)
                                                                                to authenticated;
grant execute on function public.invitation_exists(text)                        to authenticated;
grant execute on function public.validate_question_choices(uuid)                to authenticated;


-- ###########################################################################
-- ## 20260910091200_fix_touch_module_view.sql
-- ###########################################################################

-- ============================================================================
-- 0013 - Fix touch_module_view: an uncast enum in ON CONFLICT DO UPDATE.
--
-- THE BUG
--
-- Recording that a learner opened a module failed with:
--
--     42804: column "state" is of type progress_state
--            but expression is of type text
--
-- from this line in 0009:
--
--     state = case when mp.state = 'completed' then 'completed'
--                  else 'in-progress' end
--
-- The literals in a CASE are untyped, and Postgres resolves them to `text`.
-- In the INSERT above it that is fine - the target column's type is known, so
-- the literal is coerced. Inside `ON CONFLICT DO UPDATE SET`, the CASE is
-- resolved before it is matched to the column, so it stays text and the
-- assignment is rejected.
--
-- It broke every module open, which is the first thing a learner does. It got
-- through because the test suite exercised `complete_lesson` (which assigns
-- through a typed plpgsql variable, so it coerces correctly) but never called
-- `touch_module_view` at all. The suite now calls it - see rls.test.sql.
--
-- NOTE ON URGENCY
--
-- The application no longer calls this function. `progressService.openMaterial`
-- does the same read-then-upsert directly against `module_progress`, which the
-- `module_progress_own` policy already permits - so a learner is not blocked
-- on this migration being applied.
--
-- It is still worth applying: the function is part of the schema, anything
-- else that calls it would hit the same error, and leaving a known-broken
-- function in place is how it gets called again by accident.
-- ============================================================================

create or replace function public.touch_module_view(p_module_id uuid, p_lesson_id uuid default null)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then return; end if;

  insert into public.module_progress as mp
    (user_id, module_id, state, started_at, last_viewed_at, last_viewed_lesson_id)
  values (auth.uid(), p_module_id, 'in-progress', now(), now(), p_lesson_id)
  on conflict (user_id, module_id) do update
    set last_viewed_at = now(),
        last_viewed_lesson_id = coalesce(p_lesson_id, mp.last_viewed_lesson_id),
        started_at = coalesce(mp.started_at, now()),
        -- Cast explicitly. A CASE resolves its own type before being matched
        -- to the target column, so untyped literals here come out as text and
        -- the assignment fails.
        --
        -- Viewing must never downgrade a finished module back to in-progress.
        state = case
                  when mp.state = 'completed' then 'completed'::public.progress_state
                  else 'in-progress'::public.progress_state
                end;
end;
$$;

revoke execute on function public.touch_module_view(uuid, uuid) from public, anon;
grant execute on function public.touch_module_view(uuid, uuid) to authenticated;


-- ###########################################################################
-- ## 20260910091300_username_accounts.sql
-- ###########################################################################

-- ============================================================================
-- 0014 - Username accounts.
--
-- WHAT CHANGES
--
-- An administrator now creates a working account outright - username, password,
-- role, permissions - instead of recording an invitation the person has to
-- accept. The person signs in immediately with the username and the password
-- they were given.
--
-- HOW, WITHOUT A SERVICE-ROLE KEY
--
-- Supabase Auth identifies a user by email address; there is no username
-- support to switch on. So a username is mapped to a deterministic internal
-- address:
--
--     andrea  ->  andrea@kco.local
--
-- Nothing is ever sent to it. It exists because `auth.users.email` is the
-- login identifier, and the mapping is pure string concatenation done on the
-- client, so signing in needs no lookup and leaks no information about which
-- usernames exist.
--
-- The account is created by the admin's browser calling `signUp` on a second
-- Supabase client configured with `persistSession: false`, so the admin's own
-- session is untouched. `handle_new_user` still demands an invitation, so the
-- admin's browser writes one first (it holds `users.invite`) and the signup
-- consumes it a moment later. The invitation is now an internal handshake
-- rather than something a person receives.
--
-- That is why this needs no service-role key: the privileged step is creating
-- the invitation, which RLS already permits an admin, and the unprivileged
-- step is an ordinary signup.
--
-- !! ONE PROJECT SETTING IS REQUIRED !!
--
--   Authentication -> Providers -> Email -> turn OFF "Confirm email"
--
-- A username has no mailbox, so a confirmation link can never be followed and
-- the account would be permanently unable to sign in. With it off, the account
-- works the moment it is created. Real email addresses still work; they are
-- simply not confirmed by mail either, which is the right trade for an
-- internal tool where an admin vouches for every account.
-- ============================================================================

-- --------------------------------------------------------------- profiles ---

alter table public.profiles
  add column if not exists username text;

/*
 * Lower-case, starts alphanumeric, 3-30 characters.
 *
 * Deliberately narrow: a username is typed at a sign-in prompt by someone who
 * may have been told it verbally, so ambiguity is the enemy. No spaces, no
 * capitals to remember, no unicode look-alikes.
 */
alter table public.profiles
  drop constraint if exists profiles_username_format;
alter table public.profiles
  add constraint profiles_username_format
  check (username is null or username ~ '^[a-z0-9][a-z0-9._-]{2,29}$');

-- Case-insensitive uniqueness. Two accounts differing only in capitalisation
-- would both map to the same login address, and the second signup would fail
-- with a confusing duplicate-email error instead of a clear one.
create unique index if not exists profiles_username_unique
  on public.profiles (lower(username))
  where username is not null;

comment on column public.profiles.username is
  'Sign-in name. Maps to auth.users.email as <username>@kco.local, which is '
  'never delivered to. Null for accounts created from a real email address.';

-- ------------------------------------------------------------ invitations ---

alter table public.invitations
  add column if not exists username text;

alter table public.invitations
  drop constraint if exists invitations_username_format;
alter table public.invitations
  add constraint invitations_username_format
  check (username is null or username ~ '^[a-z0-9][a-z0-9._-]{2,29}$');

/*
 * The email column keeps its `@` check.
 *
 * That constraint is what produced "violates check constraint
 * invitations_email_check" when a username was typed into the form: the value
 * had no @. It stays, because auth.users.email genuinely must be an address -
 * the fix is that the caller now supplies the mapped address rather than the
 * bare username.
 */

-- ---------------------------------------------------------------------------
-- Signup, extended to carry the username through.
--
-- Same rule as before: no invitation, no account. The only difference is that
-- the profile now also records the username the admin chose.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_invite public.invitations;
  v_email  text := lower(trim(new.email));
  v_name   text;
begin
  select * into v_invite
    from public.invitations
   where lower(email) = v_email
     and accepted_at is null
     and revoked_at is null
     and expires_at > now()
   order by created_at desc
   limit 1;

  if v_invite.id is null then
    raise exception
      'This platform is invitation only. Ask an administrator to create an account for you.'
      using errcode = 'insufficient_privilege';
  end if;

  v_name := coalesce(
    nullif(trim(v_invite.full_name), ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'name', ''),
    v_invite.username,
    split_part(v_email, '@', 1)
  );

  insert into public.profiles (
    id, email, username, full_name, avatar_url, role, status, department, position
  )
  values (
    new.id,
    v_email,
    v_invite.username,
    v_name,
    nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
    v_invite.role,
    'active',
    v_invite.department,
    v_invite.position
  )
  on conflict (id) do nothing;

  if array_length(v_invite.permissions, 1) > 0 then
    insert into public.user_permissions (user_id, permission_key, granted, granted_by, note)
    select new.id, key, true, v_invite.invited_by, 'Granted on account creation'
      from unnest(v_invite.permissions) as key
     where exists (select 1 from public.permissions p where p.key = key)
    on conflict (user_id, permission_key) do nothing;
  end if;

  update public.invitations
     set accepted_at = now(), accepted_by = new.id
   where id = v_invite.id;

  return new;
end;
$$;

commit;
