-- ===========================================================================
-- KCO LMS schema - PART 7 OF 7
--
-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and
-- regenerate. Split only because the Supabase SQL Editor rejects a snippet
-- over ~100 kB with "request entity too large".
--
-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a
-- failure rolls that part back and leaves the earlier ones applied.
-- Unlike the seed, these parts are NOT individually re-runnable: they
-- create objects, so a second run raises "already exists".
-- ===========================================================================

begin;


-- The three report functions gate on reports.view rather than is_admin().
create or replace function public.report_training_completion()
returns table (
  user_id uuid, full_name text, department text, status public.user_status,
  modules_completed bigint, modules_in_progress bigint, modules_total bigint,
  completion_percent numeric, assessments_taken bigint, avg_score numeric
)
language sql security definer set search_path = public, pg_temp
as $$
  select p.id, p.full_name, coalesce(p.department, ''), p.status,
    count(mp.*) filter (where mp.state = 'completed'),
    count(mp.*) filter (where mp.state = 'in-progress'),
    total.n,
    case when total.n = 0 then 0
         else round((count(mp.*) filter (where mp.state = 'completed')::numeric / total.n) * 100, 1)
    end,
    (select count(*) from public.assessment_attempts a
      where a.user_id = p.id and a.status = 'submitted'),
    coalesce((select round(avg(a.percentage), 1) from public.assessment_attempts a
      where a.user_id = p.id and a.status = 'submitted'), 0)
  from public.profiles p
  cross join (select count(*) as n from public.modules where status = 'published') total
  left join public.module_progress mp on mp.user_id = p.id
  where public.can('reports.view') and p.role = 'sales'
  group by p.id, p.full_name, p.department, p.status, total.n
  order by p.full_name;
$$;

create or replace function public.report_assessment_performance()
returns table (
  assessment_id uuid, title text, attempts bigint, unique_takers bigint,
  avg_score numeric, pass_rate numeric, passing_score int
)
language sql security definer set search_path = public, pg_temp
as $$
  select a.id, a.title, count(t.*), count(distinct t.user_id),
    coalesce(round(avg(t.percentage), 1), 0),
    coalesce(round(100.0 * count(*) filter (where t.passed) / nullif(count(t.*), 0), 1), 0),
    a.passing_score
  from public.assessments a
  left join public.assessment_attempts t
    on t.assessment_id = a.id and t.status = 'submitted'
  where public.can('reports.view')
  group by a.id, a.title, a.passing_score
  order by a.title;
$$;

create or replace function public.report_module_engagement()
returns table (
  module_id uuid, title text, status public.content_status,
  learners_started bigint, learners_completed bigint, completion_percent numeric
)
language sql security definer set search_path = public, pg_temp
as $$
  select m.id, m.title, m.status,
    count(mp.*) filter (where mp.state <> 'not-started'),
    count(mp.*) filter (where mp.state = 'completed'),
    coalesce(round(
      100.0 * count(mp.*) filter (where mp.state = 'completed')
      / nullif(count(mp.*) filter (where mp.state <> 'not-started'), 0), 1), 0)
  from public.modules m
  left join public.module_progress mp on mp.module_id = m.id
  where public.can('reports.view')
  group by m.id, m.title, m.status
  order by m.title;
$$;

-- Admins may open a draft assessment to test it; that is now a permission.
create or replace function public.start_assessment_attempt(p_assessment_id uuid)
returns public.assessment_attempts
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_allowed int;
  v_status  public.content_status;
  v_used    int;
  v_attempt public.assessment_attempts;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select attempts_allowed, status into v_allowed, v_status
    from public.assessments where id = p_assessment_id;

  if v_status is null then
    raise exception 'Assessment not found';
  end if;

  if v_status <> 'published' and not public.can('assessments.edit') then
    raise exception 'This assessment is not available';
  end if;

  select count(*) into v_used
    from public.assessment_attempts
   where user_id = auth.uid() and assessment_id = p_assessment_id and status = 'submitted';

  if v_allowed > 0 and v_used >= v_allowed then
    raise exception 'You have used all % attempts for this assessment', v_allowed;
  end if;

  select * into v_attempt
    from public.assessment_attempts
   where user_id = auth.uid() and assessment_id = p_assessment_id and status = 'in_progress'
   order by started_at desc limit 1;

  if v_attempt.id is not null then
    return v_attempt;
  end if;

  insert into public.assessment_attempts (assessment_id, user_id, attempt_number)
  values (p_assessment_id, auth.uid(), v_used + 1)
  returning * into v_attempt;

  return v_attempt;
end;
$$;

create or replace function public.attempt_review(p_attempt_id uuid)
returns table (
  question_id uuid, prompt text, type public.question_type, points int,
  sort_order int, explanation text,
  selected_choice_ids uuid[], correct_choice_ids uuid[],
  text_answer text, correct_text text, is_correct boolean, points_awarded int
)
language plpgsql security definer set search_path = public, pg_temp
as $$
declare
  v_attempt public.assessment_attempts;
  v_reveal  boolean;
begin
  select * into v_attempt from public.assessment_attempts where id = p_attempt_id;

  if v_attempt.id is null then
    raise exception 'Attempt not found';
  end if;

  if v_attempt.user_id <> auth.uid() and not public.can('assessments.results') then
    raise exception 'That attempt is not yours';
  end if;

  if v_attempt.status <> 'submitted' then
    raise exception 'This attempt has not been submitted yet';
  end if;

  select a.show_correct_answers into v_reveal
    from public.assessments a where a.id = v_attempt.assessment_id;

  v_reveal := coalesce(v_reveal, true) or public.can('assessments.results');

  return query
  select q.id, q.prompt, q.type, q.points, q.sort_order,
    case when v_reveal then q.explanation else '' end,
    coalesce(ans.choice_ids, '{}'),
    case when v_reveal then coalesce(
      (select array_agg(c.id order by c.sort_order)
         from public.assessment_choices c
        where c.question_id = q.id and c.is_correct), '{}')
      else '{}' end,
    ans.text_answer,
    case when v_reveal then q.correct_text end,
    ans.is_correct,
    coalesce(ans.points_awarded, 0)
  from public.assessment_questions q
  left join public.assessment_answers ans
    on ans.question_id = q.id and ans.attempt_id = p_attempt_id
  where q.assessment_id = v_attempt.assessment_id
  order by q.sort_order;
end;
$$;

-- The admin answer-key views gate on the assessment permission too.
create or replace view public.admin_assessment_choices
  with (security_invoker = false) as
  select c.id, c.question_id, c.text, c.is_correct, c.sort_order
    from public.assessment_choices c
   where public.can('assessments.edit');

create or replace view public.admin_assessment_questions
  with (security_invoker = false) as
  select q.id, q.assessment_id, q.type, q.prompt, q.explanation,
         q.points, q.sort_order, q.correct_text
    from public.assessment_questions q
   where public.can('assessments.edit');

revoke all on public.admin_assessment_choices   from anon;
revoke all on public.admin_assessment_questions from anon;
grant select on public.admin_assessment_choices   to authenticated;
grant select on public.admin_assessment_questions to authenticated;


-- ###########################################################################
-- ## 20260910091100_lock_down_anon.sql
-- ###########################################################################

-- ============================================================================
-- 0012 - Re-lock the privilege layer against `anon`.
--
-- THE BUG THIS FIXES
--
-- Migration 0007 runs `revoke all on all tables in schema public from anon`.
-- That reads like a policy but it is a point-in-time statement: it affects the
-- tables that exist when it runs, and nothing else.
--
-- Supabase ships `alter default privileges in schema public grant all on
-- tables to anon, authenticated`. So every table created by a LATER migration
-- silently arrives with anon privileges restored. 0011 added four tables
-- (permissions, role_permissions, user_permissions, invitations) and all four
-- came back readable at the privilege layer.
--
-- Row Level Security still held - `permissions_select` requires
-- `is_active_user()`, which is false for anon, so the response was an empty
-- array rather than data. Nothing leaked. But "denied before any policy is
-- consulted" is the posture the rest of the schema has, and losing it on a
-- subset of tables is exactly the kind of asymmetry that becomes a real hole
-- the first time somebody adds a table with a laxer policy.
--
-- WHAT TO DO IN FUTURE MIGRATIONS
--
-- End any migration that creates a table with:
--
--     select public.revoke_anon_access();
--
-- The test suite asserts that no table in `public` is readable by anon, so
-- forgetting is a test failure rather than a silent regression.
-- ============================================================================

/**
 * Strips every `anon` privilege across the public schema.
 *
 * Written as a function rather than a bare statement so later migrations have
 * one thing to call, and so the intent is named. It is deliberately
 * idempotent: running it when there is nothing to revoke is a no-op.
 *
 * Note this does NOT touch `authenticated`. That role keeps its table
 * privileges and is constrained by RLS - which is the design. `anon` is
 * different: nothing in this product is public, so an unauthenticated request
 * should fail before a policy is even evaluated.
 */
create or replace function public.revoke_anon_access()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  revoke all on all tables    in schema public from anon;
  revoke all on all sequences in schema public from anon;

  -- Functions are EXECUTE-able by PUBLIC unless told otherwise, and `anon`
  -- inherits that, so the role has to be revoked from PUBLIC as well.
  revoke all on all functions in schema public from public, anon;

  -- Hand back the two functions an unauthenticated visitor legitimately needs:
  -- the sign-in screen checks whether an address has an open invitation before
  -- asking for a password.
  grant execute on function public.invitation_exists(text) to anon;
end;
$$;

comment on function public.revoke_anon_access() is
  'Removes every anon privilege in the public schema. Call at the end of any '
  'migration that creates a table - Supabase default privileges re-grant anon '
  'access to new tables, which 0007''s one-off REVOKE cannot cover.';

-- Apply it now, catching the four tables 0011 created.
select public.revoke_anon_access();

-- The helper itself must not be callable by anon.
revoke execute on function public.revoke_anon_access() from public, anon;

-- Restore the EXECUTE grants that the blanket revoke above just removed from
-- `authenticated`. Listed explicitly rather than re-granted wholesale, so the
-- set of functions a signed-in user may call stays an audited list.
grant execute on function public.is_admin()                                    to authenticated;
grant execute on function public.is_active_user()                              to authenticated;
grant execute on function public.can(text)                                     to authenticated;
grant execute on function public.my_permissions()                              to authenticated;
grant execute on function public.log_activity(text, text, uuid, text, jsonb)   to authenticated;
grant execute on function public.touch_last_login()                            to authenticated;
grant execute on function public.complete_lesson(uuid, boolean)                to authenticated;
grant execute on function public.touch_module_view(uuid, uuid)                 to authenticated;
grant execute on function public.start_assessment_attempt(uuid)                to authenticated;
grant execute on function public.submit_assessment_attempt(uuid)               to authenticated;
grant execute on function public.save_answer(uuid, uuid, uuid[], text)         to authenticated;
grant execute on function public.attempt_review(uuid)                          to authenticated;
grant execute on function public.my_progress_summary()                          to authenticated;
grant execute on function public.admin_dashboard_stats()                        to authenticated;
grant execute on function public.report_training_completion()                   to authenticated;
grant execute on function public.report_assessment_performance()                to authenticated;
grant execute on function public.report_module_engagement()                     to authenticated;
grant execute on function public.admin_assign(uuid[], public.assignment_target, uuid, timestamptz, text)
                                                                                to authenticated;
grant execute on function public.admin_set_user_role(uuid, public.user_role)    to authenticated;
grant execute on function public.admin_set_user_status(uuid, public.user_status) to authenticated;
grant execute on function public.admin_save_question(uuid, uuid, public.question_type, text, text, int, int, text, jsonb)
                                                                                to authenticated;
grant execute on function public.admin_invite_user(text, text, public.user_role, text, text, text[], text)
                                                                                to authenticated;
grant execute on function public.admin_revoke_invitation(uuid)                  to authenticated;
grant execute on function public.admin_set_permission(uuid, text, boolean, text) to authenticated;
grant execute on function public.assignment_effective_status(public.assignment_status, timestamptz)
                                                                                to authenticated;
grant execute on function public.invitation_exists(text)                        to authenticated;
grant execute on function public.validate_question_choices(uuid)                to authenticated;

commit;
