import type { Notification } from '@/types'
import { useLocalStorage } from '@/hooks/useLocalStorage'

/**
 * Which notification kinds reach the bell. Stored per browser, and read by both
 * the Settings toggles and the menu itself so the switches are real.
 *
 * Announcements and mentions are always delivered - they are addressed to the
 * person, not generated by their own activity.
 */
export interface NotificationPrefs {
  assignments: boolean
  results: boolean
  content: boolean
}

const KEYS = {
  assignments: 'kco.notify.assignments',
  results: 'kco.notify.results',
  content: 'kco.notify.content',
} as const

export function useNotificationPrefs() {
  const [assignments, setAssignments] = useLocalStorage(KEYS.assignments, true)
  const [results, setResults] = useLocalStorage(KEYS.results, true)
  const [content, setContent] = useLocalStorage(KEYS.content, true)

  return {
    prefs: { assignments, results, content },
    setAssignments,
    setResults,
    setContent,
  }
}

export function isDelivered(kind: Notification['kind'], prefs: NotificationPrefs): boolean {
  switch (kind) {
    case 'assignment':
      return prefs.assignments
    case 'result':
      return prefs.results
    case 'content':
      return prefs.content
    case 'announcement':
    case 'mention':
      return true
  }
}
