#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Turns supabase/migrations/*.sql into two things:
#
#   supabase/schema.sql          one file, for `psql -f` and CI
#   supabase/schema-parts/       the same schema split for the SQL Editor
#
# Two outputs because the Supabase SQL Editor rejects a snippet over roughly
# 100 kB ("request entity too large"), and the schema is 156 kB. The parts are
# what you paste; the single file is for anything driving psql directly.
#
#   ./scripts/bundle-schema.sh
# ---------------------------------------------------------------------------
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/schema.sql"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

HEADER=$(cat <<'H'
-- ===========================================================================
-- KCO Sales & Learning Management System - complete schema
--
-- GENERATED by scripts/bundle-schema.sh from supabase/migrations/*.sql.
-- Do not edit this file; edit the migrations and regenerate.
--
-- REQUIREMENTS
--   * A DEDICATED Supabase project. This script issues schema-wide REVOKEs
--     and creates public.profiles; running it in a database shared with
--     another application will break that application.
--   * Run once, on an empty project. It is not idempotent - re-running raises
--     "already exists", which is the intended safety net.
-- ===========================================================================
H
)

# The migrations, concatenated, with no transaction of their own. This is the
# input to both outputs - the single file wraps it, the splitter chops it.
{
  for f in "$ROOT"/supabase/migrations/*.sql; do
    printf -- '-- ###########################################################################\n'
    printf -- '-- ## %s\n' "$(basename "$f")"
    printf -- '-- ###########################################################################\n\n'
    cat "$f"
    printf '\n\n'
  done
} > "$TMP/raw.sql"

# The post-apply check, kept separate so it can be its own final part and is
# never wrapped in a transaction it does not need.
cat > "$TMP/verify.sql" <<'V'
-- ===========================================================================
-- Post-apply check. Measured on a clean apply of every migration:
--
--   tables 35 | views 2 | enums 12 | policies 77 | functions 33
--
-- and every table with RLS enabled.
--
-- tables_without_rls MUST be 0; anything else means a table is exposed.
-- A zero in any other column means something did not apply.
-- ===========================================================================
select
  (select count(*) from pg_tables  where schemaname = 'public')            as tables,
  (select count(*) from pg_views   where schemaname = 'public')            as views,
  (select count(*) from pg_type t join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typtype = 'e')                        as enums,
  (select count(*) from pg_policies where schemaname = 'public')           as policies,
  (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public')                                            as functions,
  (select count(*) from pg_tables where schemaname = 'public' and not rowsecurity)
                                                                           as tables_without_rls;
V

# ---- single file -----------------------------------------------------------
{
  echo "$HEADER"
  echo
  echo "-- The whole file runs in one transaction. Any error rolls it all back."
  echo "begin;"
  echo
  cat "$TMP/raw.sql"
  echo "commit;"
  echo
  cat "$TMP/verify.sql"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"

# ---- split parts -----------------------------------------------------------
# 25 kB budget, matching the seed parts that the editor accepts. Deliberately
# well under the observed failure point rather than close to it.
echo
echo "==> split for the SQL Editor"
PARTS="$ROOT/supabase/schema-parts"
rm -rf "$PARTS"
python3 "$ROOT/scripts/split-sql.py" "$TMP/raw.sql" "$PARTS" schema 25000 "KCO LMS schema"

# A preflight guard on part 1.
#
# Re-running the schema fails with `type "user_role" already exists`, which
# says nothing about the actual mistake. This turns that into a sentence that
# tells you what happened and what to do instead.
GUARD="$TMP/guard.sql"
cat > "$GUARD" <<'G'
-- ---------------------------------------------------------------------------
-- PREFLIGHT: refuse to re-apply a schema that is already there.
--
-- Without this, a second run dies on `type "user_role" already exists`, which
-- is technically true and completely unhelpful.
-- ---------------------------------------------------------------------------
do $guard$
begin
  if exists (
    select 1 from pg_type t
      join pg_namespace n on n.oid = t.typnamespace
     where n.nspname = 'public' and t.typname = 'user_role'
  ) then
    raise exception
      E'The KCO schema is ALREADY APPLIED to this database.\n\n'
      'Do not run the schema parts again - nothing you need creates types.\n\n'
      'If you are trying to:\n'
      '  * create your admin login    -> run supabase/bootstrap-admin.sql\n'
      '  * load the training content  -> run supabase/seed/parts/ in order\n'
      '  * apply a NEW migration      -> run just that one file\n\n'
      'To genuinely start over (this DELETES everything):\n'
      '  drop schema public cascade; create schema public;\n'
      'then run schema-01.sql onward.';
  end if;
end
$guard$;

G

# Prepend it to part 1, after that part's own header comment.
PART1="$PARTS/schema-01.sql"
if [ -f "$PART1" ]; then
  awk '
    /^begin;$/ && !done { print; print ""; while ((getline line < GUARD) > 0) print line; done=1; next }
    { print }
  ' GUARD="$GUARD" "$PART1" > "$PART1.tmp" && mv "$PART1.tmp" "$PART1"
  echo "  (preflight guard prepended to schema-01.sql)"
fi

# The check goes last, as its own read-only part.
cp "$TMP/verify.sql" "$PARTS/schema-99-verify.sql"
echo "  $PARTS/schema-99-verify.sql"
