#!/usr/bin/env python3
"""
Split a SQL file into parts small enough to paste into the Supabase SQL Editor.

The editor rejects a snippet over roughly 100 kB with "request entity too
large", so a 156 kB schema has to arrive in pieces. Cutting a file at a fixed
byte offset would tear a statement in half, so this walks the SQL properly and
only ever breaks *between* top-level statements.

The scanner has to understand four kinds of region, because a semicolon inside
any of them is not a statement terminator:

  - line comments      -- ...
  - block comments     /* ... */          (Postgres nests these)
  - single-quoted text  '...''...'
  - dollar-quoted text  $$ ... $$ / $tag$ ... $tag$

Dollar quoting is the one that matters most here: every trigger function and
DO block in this schema is dollar-quoted and full of semicolons.

Usage:
    split-sql.py INPUT OUTDIR PREFIX [MAX_BYTES] [LABEL]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

DOLLAR_TAG = re.compile(r"\$[A-Za-z_][A-Za-z0-9_]*\$|\$\$")


def split_statements(sql: str) -> list[str]:
    """Split into top-level statements, keeping their trailing semicolon."""
    statements: list[str] = []
    start = 0
    i = 0
    n = len(sql)
    block_depth = 0

    while i < n:
        ch = sql[i]

        # ---- block comment (nesting, as Postgres does) --------------------
        if block_depth:
            if sql.startswith("/*", i):
                block_depth += 1
                i += 2
            elif sql.startswith("*/", i):
                block_depth -= 1
                i += 2
            else:
                i += 1
            continue

        if sql.startswith("/*", i):
            block_depth = 1
            i += 2
            continue

        # ---- line comment --------------------------------------------------
        if sql.startswith("--", i):
            nl = sql.find("\n", i)
            i = n if nl == -1 else nl + 1
            continue

        # ---- single-quoted string ('' is an escaped quote) -----------------
        if ch == "'":
            i += 1
            while i < n:
                if sql[i] == "'":
                    if i + 1 < n and sql[i + 1] == "'":
                        i += 2
                        continue
                    i += 1
                    break
                i += 1
            continue

        # ---- dollar-quoted string ------------------------------------------
        if ch == "$":
            m = DOLLAR_TAG.match(sql, i)
            if m:
                tag = m.group(0)
                end = sql.find(tag, m.end())
                # An unterminated tag means the file is malformed; treat the
                # rest as opaque rather than silently mis-splitting it.
                i = n if end == -1 else end + len(tag)
                continue

        # ---- statement terminator ------------------------------------------
        if ch == ";":
            statements.append(sql[start : i + 1])
            start = i + 1
            i += 1
            continue

        i += 1

    tail = sql[start:]
    if tail.strip():
        statements.append(tail)

    return statements


def pack(statements: list[str], max_bytes: int) -> list[str]:
    """Greedily group statements into chunks under the byte budget."""
    chunks: list[str] = []
    buf: list[str] = []
    size = 0

    for statement in statements:
        b = len(statement.encode())

        # A single statement over budget cannot be split further - emit it
        # alone and let the caller see the size in the manifest.
        if buf and size + b > max_bytes:
            chunks.append("".join(buf))
            buf, size = [], 0

        buf.append(statement)
        size += b

    if buf:
        chunks.append("".join(buf))

    return chunks


def main() -> int:
    if len(sys.argv) < 4:
        print(__doc__)
        return 2

    src = Path(sys.argv[1])
    outdir = Path(sys.argv[2])
    prefix = sys.argv[3]
    max_bytes = int(sys.argv[4]) if len(sys.argv) > 4 else 60_000

    # The caller may hand us a temp file; the manifest should name the thing a
    # reader recognises, not the scratch path it happened to arrive in.
    label = sys.argv[5] if len(sys.argv) > 5 else src.name

    sql = src.read_text()
    chunks = pack(split_statements(sql), max_bytes)

    outdir.mkdir(parents=True, exist_ok=True)
    for old in outdir.glob(f"{prefix}-*.sql"):
        old.unlink()

    total = len(chunks)
    rows = []

    for index, chunk in enumerate(chunks, start=1):
        name = f"{prefix}-{index:02d}.sql"
        header = (
            "-- ===========================================================================\n"
            f"-- {label} - PART {index} OF {total}\n"
            "--\n"
            "-- GENERATED by scripts/split-sql.py. Do not edit; edit the source and\n"
            "-- regenerate. Split only because the Supabase SQL Editor rejects a snippet\n"
            "-- over ~100 kB with \"request entity too large\".\n"
            "--\n"
            "-- RUN THE PARTS IN FILENAME ORDER. Each part is one transaction, so a\n"
            "-- failure rolls that part back and leaves the earlier ones applied.\n"
            "-- Unlike the seed, these parts are NOT individually re-runnable: they\n"
            "-- create objects, so a second run raises \"already exists\".\n"
            "-- ===========================================================================\n"
            "\nbegin;\n"
        )
        body = f"{header}{chunk.rstrip()}\n\ncommit;\n"
        path = outdir / name
        path.write_text(body)
        rows.append((name, len(body.encode())))

    manifest = outdir / f"{prefix}-README.md"
    lines = [
        f"# {label}, split for the SQL Editor",
        "",
        "GENERATED by `scripts/split-sql.py` - do not edit.",
        "",
        "Paste and run these in order:",
        "",
        "| # | File | Size |",
        "| - | ---- | ---- |",
        *(f"| {i} | `{name}` | {size // 1024 + 1} kB |" for i, (name, size) in enumerate(rows, 1)),
        "",
        "Each part is a transaction. They are not individually re-runnable - if you",
        "need to start over, drop the schema and run from part 1.",
        "",
    ]
    manifest.write_text("\n".join(lines))

    for name, size in rows:
        print(f"  {outdir}/{name}  {size // 1024 + 1} kB")
    print(f"  {manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
